### ISSUE TITLE
Failed to write webdriver.io test cases on Radio component

### ISSUE THREAD

**Issue by zhaoyi0113** [palantir/blueprint#1050]
I am using `Radio` component as below but I can't write a test case to select that radio component through `webdriver.io`. 

```
import {Radio} from '@blueprintjs/core';
<Radio className='...' label={showLabel ? field.label : ''} checked={field.get('value')}
        onChange={onChange} />
```

After inspect the dom element, I see that `Radio` will render below dom structure:

```
<label class="pt-control pt-radio">
      <input type="radio" class="radio" id="hostRadio--2" name="hostRadio" value="false" label="" placeholder="">
         <span class="pt-control-indicator"></span>
</label>
```
when I try to select the `input` dom through webdriver, I got below error message:
```
unknown error: Element <input type="radio" class="hostRadio-radio-input hostRadio-radio" id="hostRadio--2" name="hostRadio" value="false" label="" placeholder=""> is not clickable at point (40, 155). Other element would receive the click: <span class="pt-control-indicator"></span>
```

it seems that there is some javascript logic to prevent me selecting this dom element. 
What is the correct way to make the radio selected?

**Comment by giladgray** [comment]
this seems like a quirk of your test environment, because clicking on the `.pt-control-indicator` should work just fine as the click handler is on the `label` (parent). unfortunately, the fix is going to fall on you @zhaoyi0113 to adjust your code so that it works in your environment. try moving the target over a few pixels or targeting the `label` element itself.

**Comment by zhaoyi0113** [comment]
Thanks for this information
