### ISSUE TITLE
[DateRangeInput] external controls to `.open()` or `.close()` date picker popover

### ISSUE THREAD

**Issue by haosharon** [palantir/blueprint#1053]
We want to trigger the datepicker to be open or closed sometimes based on focus events. 

It's a bit cumbersome to track popoverState externally and pass that down because there's a lot of complex logic that goes into computing the date picker open state - it would be nice to just be able to trigger actions (based on focus / blur etc)

**Comment by adidahiya** [comment]
This feels a little weird... it sounds like a new API to allow users to switch between uncontrolled & controlled mode during the component's lifecycle. I'd be curious to see what the code looks like with and without this new API and how this change the space of possible configurations that need to be unit tested.

**Comment by cmslewis** [comment]
Agree that it feels weird, and I'm definitely open to feedback (cc @haosharon for additional context). Desired workflow is:

1. Click on a button.
2. Reveal a `DateRangeInput` with the popover initially open.
3. Defer to default (i.e. uncontrolled) popover open/close behavior thereafter.

You could accomplish this with a manual `startInputRef.focus()` from a parent component in `componentDidUpdate`, or you could set `popoverProps.isOpen={true}` and then hope that `onInteraction` will actually be invoked whenever the popover's open/close state would change (this isn't the case now but is being fixed in #1046). Maybe those approaches alone will be sufficient?

**Comment by haosharon** [comment]
Yea - we are able to accomplice [1-3] with a manual `startInputRef.focus()`. However, for the sake of consistency we also expect the button to be able to close the popover (so that users can toggle it open/close).

The absolute correct solution is to control it ourselves, but my worry is the code to enforce that in DateRangePicker will be very brittle because there seems to be some complicated interactions between `state.isOpen` and `popover.onInteraction`

**Comment by adidahiya** [comment]
Decided against this in #1055. The recommendation here is to get a ref on the input and call `setState()` on your own, which is exactly what these instance methods would've done anyway.
