### ISSUE TITLE
Bourbon warnings

### ISSUE THREAD

**Issue by thejjmiller** [palantir/blueprint#1062]
Can you please update your use of the bourbon strip-units function? It is throwing lots of errors when references the SCSS files in the src directory.

WARNING: [Bourbon] [Deprecation] `strip-units` is deprecated and will be removed in 5.0.0 and replaced by the `strip-unit` function.
14:12:32 Backtrace:
14:12:32 	node_modules/bourbon/app/assets/stylesheets/functions/_strip-units.scss:18, in function `strip-units`
14:12:32 	node_modules/@blueprintjs/core/src/common/_icons.scss:50, in mixin `pt-icon`
14:12:32 	node_modules/@blueprintjs/core/src/components/forms/_common.scss:249

**Comment by giladgray** [comment]
we cannot update our usage because we're still on Bourbon 4.x. the message is a pre-emptive warning of a breaking change in the latest major version. #875 proposes removing bourbon dependency entirely (we use precisely two mixins).

@thejjmiller you can disable bourbon's warnings locally quite easily: 

```scss
$output-bourbon-deprecation-warnings: false;
```

https://github.com/palantir/blueprint/blob/f565570f6e442a686398ce0c12c7d7afd3dcf006/packages/core/src/blueprint.scss#L8-L9

**Comment by giladgray** [comment]
actually, this issue has been addressed by the lines of code linked above, and in https://github.com/palantir/blueprint/issues/674#issuecomment-281849984.

@thejjmiller you are seeing these warnings because you're importing src .scss files directly (instead of the root blueprint.scss file) so you'll need to manually disable bourbon warnings using the code snippet above.

**Comment by thejjmiller** [comment]
Thank you! we are including the src scss files because we are customizing some of the blueprint fonts/variables.

Thanks for the $output-bourbon-deprecation-warnings: false; hint. That really helps.
