### ISSUE TITLE
Bad focus cell on loading table 

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1077]
When a table with a focus cell is loading, we have this empty sad focus cell 

![image](https://cloud.githubusercontent.com/assets/24398123/25922128/dc15007c-358c-11e7-8641-869486709fb2.png)

### Bug report

- __Package version(s)__: 1.13.0
- __Browser and OS versions__: Mac chrome 
 Live in action: https://pl.ntr/eU

**Comment by tgreenwatts** [comment]
Same goes for empty tables and ghost cells

**Comment by gscshoyru** [comment]
The root cause of this issue is what happens when you have a table region that goes outside the bounds of the table itself. The question is how best to handle such cases. 

From looking at this, it seems like the options are either a) hide regions that go outside the bounds of the table altogether, or b) try to display as much of the region intersects the table, and only "hide" regions that are entirely outside the table. 

Does anyone have thoughts on which of these two things make more sense?

**Comment by adidahiya** [comment]
I'd just go with (a) as the simpler option for now. We can revisit if we get feedback that advocates for a more complex approach.

**Comment by llorca** [comment]
+1 with (a), seems more than reasonable. From my lens, if a region ends up outside of the bounds of the table, it's a bug. Haven't seen any practical use cases for out of bounds regions so far
