### ISSUE TITLE
NumericInput NaN

### ISSUE THREAD

**Issue by thejjmiller** [palantir/blueprint#1119]
There is a problem with the NumericInput when typing in a single - character and only using the numeric part of the handleValueChange event.

One though on a way to fix this is to create a updateOnBlur option that would wait to through the valueChange event until you blur off, this way if the thing you enter is not a number it can be reverted.

**Comment by cmslewis** [comment]
@thejjmiller This is expected behavior. Given that `NumericInput` supports all `HTMLInputProps` in addition to its own API, can you just hook into `onBlur` yourself? While there is precedent in our `Slider` for `onRelease` as distinct from `onChange`, that's essentially equivalent to `onBlur` and `onValueChange` for `NumericInput`, so I don't think it makes sense to add an extra prop here.

**Comment by thejjmiller** [comment]
Yeah we can use the onBlur ourselves but since we use the NumericInput component throughout our application we are going to create our own NumericInput wrapper component so that we don't have to implement the state management of that everywhere we use the component.

**Comment by cmslewis** [comment]
Sounds good. @giladgray if you have thoughts here, feel free to chime in, but I'll close for now.
