### ISSUE TITLE
Responsive layout, istn't that comes out of the box

### ISSUE THREAD

**Issue by avifatal** [palantir/blueprint#1155]
Hi,
I have made my initial layot really fast.
I use reflexbox to help with the layout (as i saw it is recemmended here).

When it comes to responsive, it does not work for me. see the following animated gif: https://www.screencast.com/t/zykhydjEjh

Isn't the framwork responsive out of the box, the top nav bar for example, isnt it responzive? 
Thanks.

(BTW, if you have an admin layout for example, ill be glad to have a link. thanks)

**Comment by giladgray** [comment]
@avifatal **Blueprint is optimized for desktop applications.** It is not a responsive or mobile framework, because our company does hardly any mobile development--it's just not a priority. This is mentioned first thing in the [README](https://github.com/palantir/blueprint#blueprint-), but I see now it's not mentioned on the docs site (oops).

> It is optimized for building complex, data-dense web interfaces for desktop applications. If you rely heavily on mobile interactions and are looking for a mobile-first UI toolkit, this may not be for you.

**So no, the framework is not responsive out of the box.** You may create responsive layouts using Blueprint components, which likely requires writing some custom CSS (for instance, mobile navbars). 

That said, we will accept PRs adding mobile support (see #265 for a perfect example).

**Comment by adidahiya** [comment]
desktop applications need responsive layouts too, to accommodate various screen sizes. it's not just a question of mobile vs. everything else.

[collapsible list](http://blueprintjs.com/docs/#core/components/collapsible-list) is one component which helps with responsive layout. but otherwise it's all pretty manual and has to be implemented at the application level -- there isn't really any responsive CSS in Blueprint based on media queries and such. we'd consider adding more responsive support to components if there was demand for it (for example, integrating `<Tabs>` with `<CollapsibleList>`).
