### ISSUE TITLE
Table selection/context menu bugginess 

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#1187]
### Bug report

- __Package version(s)__: Latest
- __Browser and OS versions__: Mac Sierra

#### Steps to reproduce

There are actually 2 things happening here, the first, and more important one for me, is that it doesn't seem like the Table component handles context menu clicks in the usual way: 
![asdfasdfasd](https://cloud.githubusercontent.com/assets/2730609/26752157/71884442-47fe-11e7-94be-ba1d4420cfc8.gif)

As you can see (on the docs page itself), when I right click above in your example table, the selected region doesn't change. I believe this is because the table `onSelection` prop does not get fired for right-clicks. I am running into this same issue with my own Table as well but am not sure quite how to solve it. Any help would be appreciated.

The second, smaller issue , is that for some reason opening the context menu causes the whole page to shift slightly. You can see this in the video as well if you look closely. I also find this to be the case when implementing my own blueprint tables. Does anyone know why this is happening?

Thanks very much!

**Comment by llorca** [comment]
Thanks for the report! The first issue you mentioned is tracked here: https://github.com/palantir/blueprint/issues/1083

Regarding the page shifting slightly when opening a context menu, I'm not sure what's happening, we'll investigate.

**Comment by tgreenwatts** [comment]
@cmslewis is this still an issue?

**Comment by cmslewis** [comment]
@tnrich

The page shifts because we apply an `overflow: hidden` rule to the entire page when a modal popover is shown, to prevent scrolling. This causes the page scrollbar to hide and the page content to shift rightward to recenter itself in the newly reclaimed horizontal real estate. Native OSes are able to prevent scrolling without hiding the scrollbar; we aren't at the moment. :/

On your other point, I agree that right-clicking on a cell should select it.

**Comment by pringshia** [comment]
@cmslewis 
Regarding the page shift, this may work for the body instead:

```
body.pt-overlay-open {
    position: fixed;
    overflow: scroll;
    width: 100%;
}
```

This prevents scrolling while also showing the scroll bar which gets rid of the jump. However, the catch is that if your page never had a scrollbar to begin with (because it wasn't longer than the viewport height, than you'll end up getting a jump anyway, this time in the other direction (from no scroll bar -> scrollbar)
