### ISSUE TITLE
Virtualized Selects

### ISSUE THREAD

**Issue by glentakahashi** [palantir/blueprint#1190]
This is an FR for the upcoming Selects.

Selects should be virtualized for large lists

**Comment by giladgray** [comment]
I can guarantee you that the `Select` component will not be virtualized any time soon, because that's beyond the scope of a single component. My ideal implementation for this is to support composition with a library like [react-virtualized](https://github.com/bvaughn/react-virtualized) through `InputList`'s `renderer` prop.

**Comment by giladgray** [comment]
closing along with #1191 for the same reason: new `itemListRenderer` prop makes this composition possible.
