### ISSUE TITLE
Performant Filtering in Selects

### ISSUE THREAD

**Issue by glentakahashi** [palantir/blueprint#1191]
FR for the upcoming selects.

When filtering in a select with 1000's of elements, if filtering is done without pagination, the element can lag a lot. The select should optionally automatically paginate when filtering, so that if I type "A" into the box, it doesn't do a comparison on every single value in the select, and only loads as many matching results as can be displayed.

Can describe more in person if needed

**Comment by giladgray** [comment]
The `Select` component does not take any steps to ensure performance when filtering, but it does provide some hooks to allow you to implement your own behavior if you know your data scale is above the usual safe limits. For instance, use `itemListPredicate` to process the entire list once (or only a subset of it) rather than operating on each item. You can also simply do your own filtering logic by controlling the input using `inputProps`.

**Comment by giladgray** [comment]
#2252 added an `itemListRenderer` prop which you could use to compose a virtualized list into the `Select`.

Closing this issue for now, can re-open in the future but we have no plans to bake in support for this.
