### ISSUE TITLE
Global hotkeys do not work when focused on an InputGroup

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/blueprint#1216]
It seems like `InputGroup` or perhaps native `input` is swallowing the event and my hotkey action is never triggered. @adidahiya mentioned that:

> there’s a special mousetrap-global plugin to get around this, for example. not for free with the default mousetrap library.

Is this something BP could eventually handle for us?

**Comment by llorca** [comment]
Definitely something we should support! Can't tell you exactly when we'll be able to get to it

**Comment by giladgray** [comment]
**wait hold up, this is a _by design_ situation**, and is the norm for hotkeys libraries: hotkeys do not fire from text inputs because you typically want to _type_ in a text field, not trigger random UI actions. 

other major hotkeys libraries that ignore text inputs:
- mousetrap https://craig.is/killing/mice#api.bind.text-fields
- keymaster https://github.com/madrobby/keymaster#filter-key-presses

see our own [source code](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/hotkeys/hotkeysEvents.ts#L91).

i could see a prop `<Hotkey allowInTextInput />` to support this.

**Comment by michael-yx-wu** [comment]
That makes sense since you probably don't want hotkeys like `shift + letter` to trigger while you're typing.

For some context, I'm building a spotlight-search-like component that requires me to be able to quickly show / hide the component via a hotkey. The component is effectively a glorified `InputGroup`. +1 to having some sort of prop like `allowInTextInput`.

**Comment by llorca** [comment]
Yeah, that's the common use case where you need hotkeys within an input. `Select` and the upcoming `Suggest` work the same.

@michael-yx-wu slightly off topic, but if you're combining `InputList` and `Overlay`, I would want it as a first class Blueprint component

**Comment by dmackerman** [comment]
Noticed this as well. I think by design it makes sense for most cases, but there are definitely cases (like CMD+ENTER to Submit) where you **do** want Keyboard interaction to work inside of `input`.
