### ISSUE TITLE
404 when selecting docs version.

### ISSUE THREAD

**Issue by andjonno** [palantir/blueprint#129]
<img width="696" alt="screen shot 2016-11-13 at 7 05 35 pm" src="https://cloud.githubusercontent.com/assets/1277106/20244596/4d92a384-a9d4-11e6-98e2-3c225790a85d.png">
<img width="676" alt="screenshot 2016-11-13 07 06 00" src="https://cloud.githubusercontent.com/assets/1277106/20244597/52f3c682-a9d4-11e6-985f-26a6b53c7681.png">

**Comment by cyu06** [comment]
In #64, we're still deciding how to host the older versions of the docs so that in the future rather than the 404 you flag, it'll show prior versions.

**Comment by adidahiya** [comment]
Based on the proposal we agreed upon in #64, we should probably remove this version switcher for now -- we only have one major version published.

One thing that will help document our APIs going forward is supporting a the `@since` JSDoc flag in our props tables so that users will know about API fields added in minor versions.
