### ISSUE TITLE
[DatePicker] Allow multiple date selection

### ISSUE THREAD

**Issue by prashnts** [palantir/blueprint#1298]
`react-day-picker` [supports picking multiple dates][1] by passing in an array to `selectedDays` prop. In current implementation, this is not possible due to `value` prop required to be a `Date` type [(source)][2].

I think adding another component might be the way to go here. As always, happy to open a PR once the implementation is clear. 🙂 

[1]: http://react-day-picker.js.org/examples/selecting-multiple.html
[2]: https://github.com/palantir/blueprint/blob/master/packages/datetime/src/datePicker.tsx#L55

**Comment by cmslewis** [comment]
Thanks, @prashnts! We've considered this in the past. We _could_ just extend `DatePicker` to handle this. From an interaction perspective, you could either <kbd>Shift</kbd>-click or <kbd>Cmd</kbd>-click to select multiple dates (which leaves existing plain-click behavior unaffected), or perhaps you could simply toggle each day's selected state individually on click (which does affect the current behavior—maybe there could even be a prop to toggle this mode).

A couple of our team members are on vacation this week. I'd prefer to hold off on this until they get back so that we can have a more thorough discussion on our end.

**Comment by giladgray** [comment]
don't want to support arrays
