### ISSUE TITLE
Apply Blueprint Formatting To DatePicker Dropdowns

### ISSUE THREAD

**Issue by phegstrom** [palantir/blueprint#1433]
### Feature Request

Component: DatePicker

Update the formatting of the dropdown menu for the Month and Year in the datepicker. Currently the menu is not blueprint style. Or make the dropdown configurable (enable/disable).

Maybe it'd be better to remove the dropdown altogether and use a "<" or "<<" to denote changing year/month? Something like:
`<<`  `<`  August 2017 `>`  `>>`

#### Current View
![screen shot 2017-08-10 at 1 53 45 pm](https://user-images.githubusercontent.com/5938022/29185062-23b149ea-7dd6-11e7-909c-2586b5d91324.png)

**Comment by llorca** [comment]
AFAIK it's not possible to customize the look of `<option>`s (one [SO answer](https://stackoverflow.com/questions/7208786/how-to-style-the-option-of-a-html-select)). We already removed the `appearance` from `<select>` -- I don't see any value in reimplementing this with a custom select component.

**Comment by giladgray** [comment]
we made an intentional choice to use native `<select>` elements here cuz they gave the best experience across the board (with the least effort). arrow buttons are not sufficient here because they require too many clicks to change the month from March to September (6, vs 2 with the dropdown).

while i appreciate the request for more sexy blueprint menus, the value is minimal and the effort measurable, so i'm going to close this out.
