### ISSUE TITLE
[Table] Feature request: Add a table footer 

### ISSUE THREAD

**Issue by vaenow** [palantir/blueprint#1449]
Hey guys!
Thank you for your table, it helps me a lot in my work.

**Table Footer**: just like a frozen row attach the table's bottom

**Comment by cmslewis** [comment]
Hi @vaenow, we just did a fairly major internal refactor to introduce [Frozen rows & columns](https://github.com/palantir/blueprint/pull/1445) into our `Table`. Take a look at that and see if it's workable for your use case.

We discussed the idea of sticky footers when we designed the aforementioned new feature, and we ultimately chose _not_ to support them given our use cases here at Palantir. Turns out that supporting sticky "headers" (left/top) and sticky "footers" (right/bottom) together leads to some tricky, unintuitive UX where those regions overlap.

It's possible we could tweak the feature to allow consumers to enable _either_ sticky headers or sticky footers at one time, but that's not a priority for us right now.

Are you able to get by with just sticky headers?

**Comment by gxqs416122** [comment]
I also Hope to add a summary function at the footer，I think this is also very important and the general feature

**Comment by giladgray** [comment]
@gxqs416122 @vaenow if you're wanting to put non-table-cell items in a footer (like summary details), then simply add a `<div>` after the `<Table>` and put what you want in there, with some custom styles so it stays attached to the bottom.

**Comment by tgreenwatts** [comment]
I'm going to close this out, we're not planning on supporting a table footer. If you feel strongly you can make a PR and we'll iterate with you on it
