### ISSUE TITLE
Allow "no selection" state and removing selection in Select

### ISSUE THREAD

**Issue by shuyangli** [palantir/blueprint#1556]
I'd like to use `Select` in a component where "no selection" is a legal state, and it doesn't seem like the component supports the concept of "no selection" today :(

**Comment by llorca** [comment]
@shuyangli try adding custom behavior via the `noResults` prop

**Comment by shuyangli** [comment]
I think the "no selection" state should belong to the top level. In the sample at http://blueprintjs.com/docs/#labs.select, before choosing anything, "The Shawshank Redemption" is selected by default; whereas we want the default to be "no selection". We should probably natively support this; adding a new option that says "no selection" seems like a hack.

**Comment by llorca** [comment]
It's not technically selected until you click on it or press enter. "The Shawshank Redemption" is focused when you open the select because it's the first item, and that focused state is used for keyboard navigation. I'm not sure I understand your issue, if you need to validate something outside of the items that are provided, you could try adding custom behavior via the `noResults` prop

**Comment by adidahiya** [comment]
I think we need an empty / "non ideal" state for Select. This is what I see when I load the docs before I interact with them -- it looks like "The Shawshank Redemption" is already selected:

![image](https://user-images.githubusercontent.com/723999/30359352-21664bca-9818-11e7-99ed-35550f07e580.png)

It's the same idea as `<input placeholder="..."/>`.

Also +1 for the ability to clear the selection. It's not strictly necessary but nice to have.

**Comment by llorca** [comment]
That's because [the example is made this way](https://github.com/palantir/blueprint/blob/master/packages/labs/examples/selectExample.tsx#L31). You already have full control over what the select target is.

We actually use the `(No selection)` pattern in the example [a few lines below](https://github.com/palantir/blueprint/blob/master/packages/labs/examples/selectExample.tsx#L59) but it doesn't show up because we use a default value. We can fix the docs example.

**Comment by jonavila** [comment]
@llorca Might be good to have built-in option to clear the selection. I ended up using a <ButtonGroup> with a clear <Button> to the right of the select. Seemed easier and cleaner than having do add a fake <MenuItem> and changing the default itemListRenderer

**Comment by giladgray** [comment]
@shuyangli @jonavila the `Select` component knows nothing about the actual selected item, just that the user clicked on it via `onItemSelect`. so you can quite easily implement this behavior as is. in fact, we do this on the docs site in some examples (check out icons).

**Comment by shuyangli** [comment]
I don't think this is applicable anymore! The current `Select` api wraps around a view that the consumer provides (whereas I don't believe it was the case previously in labs). Closing :)
