### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by sufuf3** [palantir/blueprint#1558]
Hi @giladgray @cmslewis ,
I'm a member of cdnjs. We are going to host this library.

What the files should need to be added in cdnjs?
(I know that `blueprint.css*` and `core.bundle.js*` which under `dist` from npm @blueprintjs/core need to be added, but what about other files?)

If you have any suggestions, please let me know.

Thank you.

cdnjs/cdnjs#9745
cdnjs/cdnjs#9667

**Comment by giladgray** [comment]
@sufuf3 you are correct: `blueprint.css` and `core.bundle.js` are the two most important files. 

next up in importance are`variables.{less,scss}`. 

the individual `.js` or `.d.ts` files are not critical to host because they're used by developers and typically require a bundle or compile step before runtime in the browser. not sure if it's even practical to host them all as there's gotta be close to 100 separate files there?

**Comment by giladgray** [comment]
additional note: every package.json lists several "main" files, which should give you a good place to start in each package.

https://github.com/palantir/blueprint/blob/master/packages/core/package.json#L5-L8

**Comment by sufuf3** [comment]
@giladgray Thank you very much.
