### ISSUE TITLE
Virtualised Menu to improve rendering performance for labs/Select with many options

### ISSUE THREAD

**Issue by olivergeorge** [palantir/blueprint#1607]
Using Menu for labs/Select lists can lead to slow performance where there are many options.

Table doesn't have this problem because rendering is only done on visible cells.  I think the same technique would be useful for the new labs select lists.

**Comment by tnrich** [comment]
Hey @olivergeorge 

I totally agree that an easy way to virtualize the Menu would be awesome! That said, if you're only going to be rendering a few thousand items and not millions then maybe the following trick could help: 

I've found after doing a bit of profiling that a lot of the cost for rendering the default Select with a bunch of options comes from having to mount each individual MenuItem: https://codesandbox.io/s/42rp2q017w

![image](https://user-images.githubusercontent.com/2730609/57101113-616edc80-6cd5-11e9-8d36-67feca762fc4.png)

By having the itemRenderer return a <div> instead of a <MenuItem> it speeds things up a lot: 
```
<div onClick={handleClick} key={film.rank}
      className={classnames("bp3-menu-item",{
        "bp3.active": modifiers.active,
        "bp3-disabled": modifiers.disabled,
      }) }>{text}</div>
```
https://codesandbox.io/s/qkx89rzw79

**Comment by adidahiya** [comment]
Closing in favor of #2632, which is more up to date
