### ISSUE TITLE
[DatePicker] Expose selected as a modifier

### ISSUE THREAD

**Issue by thisbejim** [palantir/blueprint#166]
Currently when you try to use ```selected``` as a DatePicker modifier it is ignored by the component. 

This feature is useful if you are trying to select multiple, individual dates that are not in a range, as described in this [react-day-picker issue](https://github.com/gpbl/react-day-picker/issues/229).

**Comment by vijaysharmase** [comment]
@adidahiya any update on this issue #166? We are not able to use this component just because of this problem. Please update the DateInput component.

**Comment by llorca** [comment]
@vijaysharmase This issue doesn't seem related to `DateInput` -- you mean `DatePicker`, right?

**Comment by giladgray** [comment]
@thisbejim @vijaysharmase this feature is not a priority for the team (we don't deal in non-contiguous dates) so we will not be tackling it ourselves, but we'd happily accept a (well-tested) PR.

as an easier workaround, i would suggest that you introduce your own modifier for this rather than trying to reuse `selected` (which `DatePicker` claims as its own), and copy/modify the styles in your app directly.
