### ISSUE TITLE
Feature request: multiselect input

### ISSUE THREAD

**Issue by neevany** [palantir/blueprint#168]
https://jedwatson.github.io/react-select/

**Comment by giladgray** [comment]
see https://github.com/palantir/blueprint/blob/410f8dc6d5e55788a414162ddc78aa0756e016c0/packages/docs/src/components/navigator.tsx for a raw proof-of-concept of this sort of thing using Blueprint components. it almost just works!

**Comment by cmslewis** [comment]
_Personal note:_ As distinct from the Typeahead discussion in #118, I think this issue is requesting a component that specifically enables multiple selections at once, like this:

![image](https://cloud.githubusercontent.com/assets/443450/20579317/e64db3bc-b180-11e6-9dfc-e584ba117b15.png)

If we pursue the Typeahead, we should consider how it works vis-à-vis multi-selection. Should one be a composition that includes the other? Should they be baked into the same component? etc.

**Comment by cmocanu** [comment]
Shouldn't this be closed?

**Comment by llorca** [comment]
@cmocanu yup correct, there was a few duplicate issues
