### ISSUE TITLE
[Table] Add better visual indicator at frozen-row/-column boundary

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1685]
Perhaps a thicker border like Google Sheets does

**Comment by cmslewis** [comment]
Challenge: cells need to know how wide the frozen-pane border will be in order to calculate the correct `left` offset at which they should be painted.

**Comment by cmslewis** [comment]
@llorca thoughts?

**Comment by llorca** [comment]
2px border sounds good

**Comment by michael-yx-wu** [comment]
I can work on this if no one else is. I tried box-shadow on the quadrants themselves just now but it looks ugly because the shadows overlap and end up being darker on the top-left quadrant. Unfortunately `inset` box shadows don't show up on the quadrants either.

I'm going to try passing the border info down to the header cell and body cell level.
