### ISSUE TITLE
TimezonePicker issues

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#1703]
__Package version(s)__: labs 0.11.0

Using TZP for the first time in my app and encountering a number of usability issues:

- [ ] `min-width` on Popover content seems unnecessary. we should probably just remove it and let apps set it if needed. @brieb any reason it was there in the first place?
- [ ] `TimezoneDisplayFormat` options are awkward, not sure they're all useful.
  - `GMT -07:00` is not possible at the moment.
  - can we also accept a moment format string?
- [ ] how to default to current timezone with controlled `value`? `TimezonePicker.getUserTimezone()`?
- [ ] `value` is not currently useful;  we should probably return a higher-fidelity object that includes name & offset.
  - `"America/Los_Angeles"` isn't a useful value, least of all with moment itself:
  - `moment().zone(arg)` wants an offset string like `"-07:00"` or an offset number like `420`.

**Comment by brieb** [comment]
Thanks for filing these! Glad to hear you're using it in your app. :)

The purpose of the min-width was so that the popover doesn't change size as you type.
![untitled](https://user-images.githubusercontent.com/723547/31478369-c0188fae-aec4-11e7-903f-5a182d421443.gif)

Looking back on it, `TimezoneDisplayFormat` does seem pretty awkward. Unless I've missed something, the formatting options for timezones is limited/nonexistent (https://momentjs.com/docs/#/parsing/string-format/). So, one idea could be a user-defined formatter `formatTimezone({ abbreviation, offset, name }) => string`

In an effort to not require the user to know anything about moment timezone, I like your idea of adding a static method on the component for getting the user's current timezone.

Providing "America/Los_Angeles" as the value is robust to DST. We can give back the offset as well, though the user will have to know that the offset is with respect to the date that they passed in (or the default date of now). So, maybe we'd need to pass back the reference date in that object as well? The [UTC Offset] docs (linked to from the deprecated [moment.zone](https://momentjs.com/docs/#/manipulating/timezone-offset/) function you mentioned) call out this issue. 
> Setting the UTC offset by supplying minutes. Note that once you set an offset, it's fixed and won't change on its own (i.e there are no DST rules). If you want an actual time zone -- time in a particular location, like America/Los_Angeles, consider moment-timezone.

**Comment by giladgray** [comment]
@brieb thanks for the context! hope you're doing well out there!

-------

I think it's safe to remove the `min-width` here. The problem you describe is a general issue with `Select`-style components and should be solved at a higher level (I have a few ideas).

----

You're right that moment's TZ formatting options are limited Formatting function sounds like the way to go here! Will update description.

----

_Oh snap_ timezone vs offset! Thanks for clarifying that, will have to keep such things in mind.

So I'm thinking of adding a second argument to `onChange` that will receive the full metadata object: `onChange(timezoneName: string, metadata: ITimezoneMetadata)`. Then consumers will have easy access to `offset` and other data which they can store as necessary, seems to solve all my own consumption problems.

**Comment by llorca** [comment]
I was in favor of the `min-width` as well. Width changing after every key down is annoying, and we know exactly what content is in this time picker dropdown, so doesn't it make sense to have a `min-width`?

**Comment by giladgray** [comment]
I don't disagree that it's an issue but as I said above, **the `min-width` thing is an issue with _all `Select`-style components_, not just this one.** So it should be solved at the `Select` level, not at the `TZP` level. 

Case in point: My app is by default only 300px wide (yeah I know) so `min-width: 370px` was an immediate blocker. I have written styles that I can apply to an inline `Select` to make the menu width match exactly the button width so it will never change when the user types. See the conflict there?
