### ISSUE TITLE
Submenu closes before user can access the submenu.

### ISSUE THREAD

**Issue by JPaveg** [palantir/blueprint#1726]
### Bug report

- __Package version(s)__: 1.31.0
- __Browser and OS versions__: Chrome 61 x64, Windows 10

#### Steps to reproduce

https://streamable.com/w6rpg

1. Navigate to http://blueprintjs.com/docs/#core/components/menu.sample-usage
2. Mouse over any menu item with a sub menu
3. Try to move mouse over to submenu, submenu closes.

#### Actual behavior

Submenu closes when trying to access it.

#### Expected behavior

For the submenu not to close when trying to access it.

The only way to access the submenu is to move the mouse fast enough to not trigger the mouseleave event.

**Comment by msmonto** [comment]
I believe this may be the source:
https://github.com/palantir/blueprint/commit/87939cb6b3f502c58ceea975a16d2b0f59ee100b#diff-95e6e4963e613c7199475a5aeea00fc8

I changed it back to `position: relative` and it's working as it was previously for me. 

I'm not sure what this is breaking though, i assume that change to absolute positioning was fixing something else... please advise

**Comment by cmslewis** [comment]
@llorca this is caused by your IE fix (well, more like "fix" at this point 😄). Here's a GIF. Note that if there's a no-man's-land between the target and submenu that closes the menu if you cross it too slowly. 

![2017-11-06 09 25 33](https://user-images.githubusercontent.com/443450/32454584-7e4f6aba-c2d4-11e7-9df3-480ae7f3acba.gif)
