### ISSUE TITLE
advice for side navigation bar 

### ISSUE THREAD

**Issue by aityahiaidir** [palantir/blueprint#1768]
The question on the sidebar has already been asked in the past, but I came across this [awesome sidebar](https://dribbble.com/shots/3647198-Sidebar) made with Bluprint, I would like to get something similar, what component could I use to get approximately a same result.

I see that he used Tabs as containers in another container can be panel.

**Comment by giladgray** [comment]
@aityahiaidir that dribbble shot (created by @pkwi, who's been on the blueprint core team since day one 😄) showcases a bunch of existing components like `Tree`, `Tabs`, and `Checkbox`. 

Blueprint does not provide any container or layout components; we suggest using CSS flex box for layouts. CSS transitions on `flex-basis` or `width` make short work of slick drawer interactions.

**Comment by johnnyz** [comment]
That would be absolutely killer to see some of the base code for this dribble. I presume still not available anywhere?
