### ISSUE TITLE
Overlay doesn't stretch 100% height

### ISSUE THREAD

**Issue by bravedick** [palantir/blueprint#183]
### Bug Report

- __Package version(s)__: 1.0.1

#### Actual behavior:

Overlay scrolls:

![image](https://cloud.githubusercontent.com/assets/988471/20343589/a40aeb5c-abf7-11e6-9b66-1640882ace5a.png)

#### Expected behavior:

Overlay should not be scrollable (position: fixed; and body="overflow: hidden;" while overlay is opened to prevent scrolling under overlay)

**Comment by adidahiya** [comment]
What browser and OS versions are you using? (note that this prompt is in the issue template...)

**Comment by giladgray** [comment]
ah i'll bet the docs redesign had something to do with this, now that `body` is the scroll container (instead of some deep child element). 

still, browser + OS versions would be very helpful.

**Comment by bravedick** [comment]
OSX 10.12.1
Chrome 54.0.2840.71

**Comment by adidahiya** [comment]
looks like the docs are generally not taking up the full window height:

![image](https://cloud.githubusercontent.com/assets/723999/20365781/39e8bb9a-ac16-11e6-919b-572a4c1b0fc9.png)

**Comment by giladgray** [comment]
@adidahiya i don't have that window height issue when viewing blueprintjs.com/docs on my box. my versions are same as @bravedick.

i do however have Overlay scrolling issues. this seems to be a regression in #148 due to using the `window` as the scroll container (instead of a `position(absolute, 0)` div under my control) in combination with `position: absolute` overlays. two things likely need to happen in `Overlay`:

1. use `position: fixed` so scroll position won't affect their screen-covering potential
2. add a class to `body` that sets `overflow: hidden` to prevent window scrolling. this class could be prop-configurable and used only when non-inline.

**Comment by adidahiya** [comment]
How about switching back to using `body` as the scroll container? It seems suspect that we need to change the Overlay implementation to address this issue since we haven't seen similar reports of this kind of thing before...

**Comment by giladgray** [comment]
we weren't using `body` as the scroll container. using any explicit element as the scroll container provides the same experience: you have to click on that container once in order to scroll with the keyboard (including page up/down). using the window is preferable for long text-heavy pages like this so i'd like to try to make this work.

the fix pretty much amounts to switching from `position: absolute` to `position: fixed`. my concern is that it may amount to a breaking change 😨

**Comment by giladgray** [comment]
@adidahiya I opened #187 to demonstrate the scroll container inconsistencies. very frustrating stuff.

**Comment by adidahiya** [comment]
Heads up @cmslewis, I'm still seeing this issue with the docs global hotkey dialog in the v1.2 docs in Chrome (the regular Overlay example has been fixed though). That same dialog is also unusable in Firefox due to #231.

**Comment by cmslewis** [comment]
Interesting. Thanks for the heads-up. 👍

**Comment by cmslewis** [comment]
Looks like that one is being rendered inline, hence the problem you're seeing (the overlay has the `.pt-overlay-inline` class that I just introduced in v1.2.0). I wonder if simply rendering the global hotkey dialog non-inline will be the appropriate fix.
