### ISSUE TITLE
[Table] Tables are now less functional due to removal of ellipse  

### ISSUE THREAD

**Issue by Sam-Kramer** [palantir/blueprint#1845]
As it appears, the ellipse's are now not shown by default, and will only be exposed when hitting a certain character limit rather then when the text is truncated by column width. 

Why I disagree with this:

- The arbitrary limit isn't shown to the end user, which creates confusion when using the interface. I originally thought this was a bug, only later to find out it was only for text over a certain character length. 
- The workaround is rather tedious (copy+paste into a notepad, as the tooltip doesn't work), and forces user's to use outside programs, such as notepad. Expanding the column is also not an option, as a lot of these columns would take up the whole screen, but need to be used in conjunction with other columns.

**Comment by cmslewis** [comment]
_From #1846:_

@Sam-Kramer The reality is that aggressively including the **`···`** popover trigger in every cell absolutely destroys performance, because the `TruncatedFormat` cell wrapper has to constantly re-measure its contents in the DOM to see if they need to be truncated. The result: DOM thrashing:

https://codepen.io/cmslewis/pen/dVYRRE

To revert the behavior, explicitly set `detectTruncation={true}` in your `TruncatedFormat` components, or use [`resizeRowsByApproximateHeight`](http://blueprintjs.com/docs/#table-js.instance-methods) to automatically resize row heights to fit cell content, rather than relying on truncation popovers.

---

That said, @tgreenwatts: I just had a terrible, horrible, no good, very bad idea to improve scroll performance, which might make these **`···`** things much less costly.

**Comment by tgreenwatts** [comment]
we're trying to add the ellipsis back but more performantly here - https://github.com/palantir/blueprint/issues/1816
