### ISSUE TITLE
[Table] Tooltip does not display for any row/column in a table

### ISSUE THREAD

**Issue by Sam-Kramer** [palantir/blueprint#1846]
### Bug report

Blueprint (table) 1.29.1

Chrome: Version 58.0.3029.81
OS: Windows 7 Pro Service Pack 1

#### Steps to reproduce

1. Hover over any row on a table that is truncated, a tooltip should popup and display the row's full value

#### Actual behavior

No tooltip is displayed 

#### Expected behavior

A tooltip should display

**Comment by cmslewis** [comment]
The reality is that aggressively including the **`···`** popover trigger in every cell absolutely destroys performance, because the `TruncatedFormat` cell wrapper has to constantly re-measure its contents in the DOM to see if they need to be truncated.

---

That said, @tgreenwatts: I might have a terrible, horrible, no good, very bad idea to improve scroll performance, which would make these **`···`** things much less costly.

**Comment by cmslewis** [comment]
@Sam-Kramer I'd love if you could include a GIF. Are you saying that even if **`···`** icons are showing, clicking on them does not show a popover with the full cell content? (Note that you have to click, not hover, as indicated by the `cursor: grab` styling on the target).

**Comment by Sam-Kramer** [comment]
Hi Chris, I filed a separate ticket for ellipses, but this is for the actual tooltip displayed via Chrome (see: http://jsfiddle.net/ricksuggs/cDhEL/). Was I under the wrong impression that this has never been the case?

**Comment by cmslewis** [comment]
@Sam-Kramer "Tooltip" is a first-class component in Blueprint ([link](http://blueprintjs.com/docs/#core/components/tooltip)). Are you talking about the native browser tooltip shown when you hover elements having a `title` attribute?

**Comment by giladgray** [comment]
closing stale issue. @Sam-Kramer feel free to re-open with answers to questions above.
