### ISSUE TITLE
When using line wrapping in tables, medium length columns are oversized

### ISSUE THREAD

**Issue by titatoverheks** [palantir/blueprint#1904]
### Bug report

Contour 3.39.2
Chrome latest version Mac OS

#### Steps to reproduce

See this analysis on Papaya: https://papaya.yojoe.local/shares/links/yef2f6qa362s4
1. Open a table in contour that has really long columns and medium length columns.
2. Enable line wrapping in the table.

#### Actual behavior
The medium length columns are oversized: 
![image](https://user-images.githubusercontent.com/20539693/33961109-c91ec634-e044-11e7-9893-338492ef9a11.png)

#### Expected behavior

The table gets resized in such a way that the bottom of the cell aligns with the bottom of the text.

**Comment by cmslewis** [comment]
Not a bug; this is an expected artifact of the resizeRowsByApproximateCellHeight behavior. The choices when resizing rows with wrapped text are:

1. Slow: render all the text in the DOM, measure it, resize all cells. This leads to DOM thrashing when you scroll.

2. Fast: approximate the cell size based on the font characteristics and the number of characters in each cell.

We opt for the latter now; otherwise, scroll performance is terrible. Don't expect this to change anytime soon.
