### ISSUE TITLE
[Button] disabled button's tabindex should be `-1`

### ISSUE THREAD

**Issue by jiangyijie27** [palantir/blueprint#1955]
#### Actual behavior
![image](https://user-images.githubusercontent.com/7429808/34239811-f7695e36-e644-11e7-9c06-34da7922ab27.png)

If I keypress `Tab`, the disabled button will get focused though no style will be added to it. 
So it'll take 3 `Tab`s to navigate to the first button on the second line.

#### Expected behavior
Disabled button's should not be keyboard-navigable, `tabindex` of which should be `-1`.

**Comment by giladgray** [comment]
@jiangyijie27 the purpose of that CSS example (the `:disabled` attribute) is to demonstrate how it _does not work_ on anchor tags, only on button tags.

that said, setting `tabIndex={-1}` on the `AnchorButton` component is a completely reasonable request and very easy to change here: https://github.com/palantir/blueprint/blob/master/packages/core/src/components/button/buttons.tsx#L42

we'd happily accept a PR for this.

**Comment by jaamison** [comment]
@giladgray In addition to setting `AnchorButton`s tabIndex to -1 if !!props.disabled (overridable by user of course), it seems like it would also make sense to default to tabindex="0" (absent a user-specified `tabIndex` prop) in order to standardize the behavior of Button & AnchorButton to the maximum extent possible.

It looks like there's a default value for the prop in the source, but the latest docs seem to indicate that this is something that must be done manually. Let me know what you think and I'll submit a PR.

**Comment by giladgray** [comment]
@jaamison sure a PR would be welcome 👍
