### ISSUE TITLE
Remove all deprecated props

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#2019]
I'm still seeing things like this in the 2.0.0-beta.1 docs:

![image](https://user-images.githubusercontent.com/723999/35109481-84c43a20-fc44-11e7-96e1-68b944b9f952.png)

**Comment by giladgray** [comment]
things that are deprecated:

- [ ]  `DateInput` `popoverPosition` (screenshot above)
- [ ] `ColumnHeaderCell` `enableColumnInteractionBar`: deprecated since blueprintjs/table v1.27.0; pass this prop to `Table` instead.
- [ ] `HeaderCell` `menu`: deprecated since v1.17.0; use `menuRenderer` instead.
- [ ] `IInternalHeaderCellProps` `isReorderable`: deprecated since 1.21.0; pass `isReorderable` to `ColumnHeader` or `RowHeader` instead.
- [ ] `Table` `Utils` re-exports a bunch of `CoreUtils`

@cmslewis @themadcreator could one of you take on the table deprecations?

**Comment by adidahiya** [comment]
I'll take this over
