### ISSUE TITLE
Docs for Electron

### ISSUE THREAD

**Issue by briant-spindance** [palantir/blueprint#202]
Would be nice to have some docs for getting Blueprint up and running with Electron.

**Comment by giladgray** [comment]
we've never used Blueprint in Electron so I wouldn't even know where to start.

@briant-spindance do you have any interest in writing these docs? or at least enumerating the issues we'd have to resolve before BP can be used in Electron?

**Comment by bbenezech** [comment]
The 2 things sound orthogonal. @briant-spindance Do you have issues with TS and Electron?
You can have a look at https://github.com/claudioc/electron-typescript-react-quick-start or https://github.com/robdaemon/typescript-electron-quickstart

But in any case TS is not required to run blueprint JS.

**Comment by forman** [comment]
@briant-spindance we've just kicked off an electron project where we selected blueprint to be the core UI component library: https://github.com/CCI-Tools/cate-desktop. We use TypeScript. One day it will be the GUI for climate analysis toolbox.

Note since we are HTML/CSS/TypeScript beginners, the tools stack is the bare minimum, so no webpack, no babel, we just use tsc and electron builder.

**Comment by briankc** [comment]
I am using Blueprint in an Electron app without issue (no webpack, using electron-prebuilt-compile, though I'm not sure that makes any difference or not).

**Comment by P0oOOOo0YA** [comment]
maybe an official boilerplate would be a better option. @giladgray I'm quoting from official documentation 

> It is optimized for building complex data-dense interfaces for **desktop applications**.

And you say you have never used it with electron? so what do you mean by desktop applications? I have seen many electron apps use ant design. Why someone should choose blueprint instead? (In the context of desktop app)
