### ISSUE TITLE
[Overlay] Nested overlays close all overlays when inner content is clicked

### ISSUE THREAD

**Issue by tyscorp** [palantir/blueprint#2030]
### Bug report

- __Package version(s)__: v1.x and v2.x
- __Browser and OS versions__: Irrelevant
#### Steps to reproduce

1. Create nested overlays/popovers
2. Click the content of a nested popover.

Screencast of the issue on the docs [here](https://cl.ly/373Q0w192H1b).

#### Actual behavior

All the popovers close.

#### Expected behavior

All popovers remain open.

I have fixed this locally by patching `Overlay`. My solution works by propagating depth via context. Every overlay reads the current depth and then sets the new depth to +1. I then override [handleDocumentClick](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/overlay/overlay.tsx#L348-L356) and if a nested overlay was clicked, only close the descendants.

The source code for this patch is [here](https://gist.github.com/tyscorp/2bc90d8c3c90cbd701a63aaffb87c45f). I currrently use the DOM to store data but I think another solution would be possible.

I'd be interested in making a PR with a better solution if wanted.

**Comment by giladgray** [comment]
💯  bug report! thanks for the screencast and patch link!

oof this is some nasty interaction, cuz each nested `Overlay` is in a separate `Portal`. 
we already maintain [`Overlay.overlayStack`](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/overlay/overlay.tsx#L137) with refs of nested `Overlay` components. I wonder if that could be used instead of context / DOM data?
