### ISSUE TITLE
[timezone] remove moment-timezone dependency?

### ISSUE THREAD

**Issue by giladgray** [palantir/blueprint#2120]
here's what I'd like to do with `TimezonePicker` for 2.0:

1. remove `moment-timezone` dependency
1. add `timezones: ITimezoneItem[]` required prop: user passes array of known timezones from whatever library they wish
    - this should replace `private timezoneItems` and `private initialTimezoneItems` 
    - maybe add a prop to `ITimezoneItem` to indicate if it should appear in initial items? (item shown when query is empty)
1. move component back into `datetime` pkg since it no longer has this extra huge dependency
1. kill `timezone` package

**Comment by adidahiya** [comment]
5. create `@blueprintjs/datetime-moment-timezone` to expose the 100 or so lines of code we use to build the timezone picker in our docs to make the break as seamless as possible

**Comment by giladgray** [comment]
@adidahiya 

`datetime`, `datetime-moment`, `datetime-moment-timezone`? three packages?

**Comment by giladgray** [comment]
```js
// this module only imports moment:
import { utils... } from "datetime-moment";

// this module imports moment-timezone:
import { timezoneUtils } from "datetime-moment/timezone";

**Comment by adidahiya** [comment]
1. I don't like submodule imports because it's better to simply ban them across the board and consider the package root as the public API boundary.
2. If we agree to point (1), then both `moment` and `moment-timezone` libraries get bundled if anyone imports from `@blueprintjs/datetime-moment` with your proposal. In the typical case, it seems like moment-timezone with timezone data is about 50% of the size of moment.
3. Therefore, we should split out packages that pull in extra dependencies.

**Comment by giladgray** [comment]
2 - that is explicitly _not_ my proposal. i'm proposing that `moment-timezone` would only be brought in if you import from the `/timezone` submodule.

**Comment by adidahiya** [comment]
well, point 1 above rules out submodules like that

**Comment by giladgray** [comment]
change of plan! replacing `moment-timezone` with `spacetime` package, as suggested by @clekili

**Comment by giladgray** [comment]
re-change of plan: sticking with `moment-timezone` but refactoring component to be a little better.
