### ISSUE TITLE
[Table] drag and drop row re-ordering

### ISSUE THREAD

**Issue by toddself** [palantir/blueprint#213]
Looking to implement drag and drop re-ordering of rows for the table component, but not 100% how to do best do this.

Since the component doesn't contain data, either an interface would have to be provided to explain the transaction that occurred.

Something like
```
onDragDrop: function (originalIndex, newIndex) {}
```

And possibly a prop to enable/disable it (you'd likely have to set the selection mode to rows only?

This way the user could perform the array update via whatever mechanism they need to correctly maintain state for the dataset.

Any thoughts or comments on how best to attack this?

I see there's some drag and drop stuff implemented for selection, so ideally that could be re-purposed?

**Comment by llorca** [comment]
@themadcreator any thoughts?

**Comment by themadcreator** [comment]
We'll definitely want visual feedback while the user is dragging the column. Maybe not necessarily the fully rendered column because it would be pretty annoying to try to render the fixed header.

You may find the approach we used for the resize handle to be a good place to start.

You could utilize the "guide" layer that the resize handle uses to indicate where the column will be moved to when dropped.

Another issue to look out for is the number of overloaded interactions on the header. We potentially have click to select, click to edit name, a popout menu, and then a space for arbitrary components added by users.

For example, currently click+drag on the column header will select a range of columns.

**Comment by toddself** [comment]
Our primary use-case for this is a spreadsheet style system where the columns are not-reorderable, so likely just will implement a version for rows at first, which have a much less overloaded metaphor in terms of UI complexity as well.

Our current product uses slickgrid which does a ghosted "drag" element and then gives you a very thick line for the destination, so my thoughts on this were similar in terms of UI.

**Comment by themadcreator** [comment]
Oh sure, row re-arrange would be basically equivalent to column re-arrange. There is also already row resize handling, so the stuff I said above still applies.
