### ISSUE TITLE
No abbility to ContextMenu.show after modal dialog

### ISSUE THREAD

**Issue by avin** [palantir/blueprint#2131]
As ContextMenu.show uses single DOM element, if modal popover made after first time ContextMenu.show - new menu is behind modal dialog popover.

**Comment by giladgray** [comment]
this behavior is most certainly intentional, and kind of par for the course. modals open in a stack simply due to DOM ordering, so if you open a Dialog over a Popover (context menu), it's going to cover it.

**Comment by adidahiya** [comment]
what if you want to show a context menu on an item in a Dialog?

**Comment by avin** [comment]
have to use dirty hack with setup z-index on selector `.pt-context-menu + .pt-portal`

**Comment by adidahiya** [comment]
not sure how my comment got deleted, but I'm pretty sure the issue is here, where we only ever create the context menu portal container element once per instance of blueprint: https://github.com/palantir/blueprint/blob/383caf34557a986c5c0c4ce56290b18e3732576b/packages/core/src/components/context-menu/contextMenu.tsx#L119

**Comment by giladgray** [comment]
oh ok that's reasonable. we can make a new element each time.
