### ISSUE TITLE
pt-fill unsupported in suggest/multiselect components

### ISSUE THREAD

**Issue by siftikha** [palantir/blueprint#2137]
### Bug report or Feature Request

blueprintjs/select 2.0.0
Chrome, OSX

#### Steps to reproduce

Try to make a suggest/multiselect with pt-fill

#### Actual behavior

The multiselect or suggest fails to fill the container
#### Expected behavior

The multi-select or suggest ought to fill the container

**Comment by mindcrash** [comment]
I have achieved this partially by overriding .pt-popover-wrapper with a custom class and telling it to use the full width of whatever element it is sitting in:

```css
.pt-popover-wrapper.ns-my-popover-wrapper {
 width: 100%;
}
```

The popover is still a bit of a pain however, because it is rendered within a portal outside of the tree (although something does seem to happen there because the arrow is moving towards the center when applying the style above).

**Comment by giladgray** [comment]
@mindcrash the arrow has a mind of its own. if you are able to not use a portal for this popover then you can easily size it to the button!
