### ISSUE TITLE
Add a progressbar to indicate the duration of the toast

### ISSUE THREAD

**Issue by ConneXNL** [palantir/blueprint#216]
Really missing this to make the Toast component competitive with other toast libraries.

A good implementation of a progress duration indicator can be seen at:
http://izitoast.marcelodolce.com/

Here are the styles and javascript that implements the behavior:
https://github.com/dolce/iziToast/blob/master/js/iziToast.js#L178-L236
https://github.com/dolce/iziToast/blob/master/css/iziToast.css#L29-L60

**Comment by adidahiya** [comment]
That behavior actually feels a little distracting to me. In a real application, you typically want to limit the use of motion in your UI to just the essentials, and an indicator of toast duration probably doesn't meet that threshold for being useful enough to be in the core UI kit. 

If you want this in your own app, you could probably come up with a CSS-only solution for toasts of a known duration (default 5s). Also curious to hear @llorca's thoughts.

**Comment by llorca** [comment]
I generally agree with Adi's note about not overusing motion. I also believe that end users shouldn't even have to worry about such a timeout: the toast should be visually distracting when appearing so users notice it, and as a developer you should be mindful of the duration of the timeout so that your users have enough time to read/interact with it.

On the bright side, it's quite trivial to implement! If you choose to do so, Blueprint won't get in your way 👍

**Comment by giladgray** [comment]
Yes we chose deliberately to not include such a progress bar because it was too distracting. Fortunately, it's quite easy to add your own if you really want one.

Closing this issue as it's been "resolved."
