### ISSUE TITLE
Clicking menu item in docs v1 cycles through items

### ISSUE THREAD

**Issue by imawuman** [palantir/blueprint#2171]
![blueprintdocs](https://user-images.githubusercontent.com/3641039/36508843-b7653324-1712-11e8-801d-6b4b1ec65fcd.gif)

**Comment by imawuman** [comment]
Couldn't find existing so created new one

**Comment by adidahiya** [comment]
same as #2148, but that one was prematurely closed. It's clear that this is still an issue in the v1 docs.

**Comment by will-stone** [comment]
I've found the same issue on v2 docs too, using Firefox 58.

**Comment by danielbh** [comment]
The culprit seems to be [here](https://github.com/palantir/blueprint/blob/develop/packages/docs-theme/src/components/documentation.tsx#L223). When you set  the offset argument which is currently 100 to 122 or greater the bug appears fixed. I believe it has something to do with the fact that `.docs-anchor` elements have  -120 top-margin. I haven't submitted a PR because  I still have no idea why this bug is happening, only what appears to fix it. What are your thoughts @adidahiya ?

**Comment by danielbh** [comment]
To add to that 121 works most of the time, but not for these two links 
<img width="227" alt="screen shot 2018-03-12 at 11 00 02 pm" src="https://user-images.githubusercontent.com/6653234/37320287-63dab7b0-2649-11e8-9c06-9f6ff02a6b60.png">

**Comment by giladgray** [comment]
fixed in #2237
