### ISSUE TITLE
[Core/Menus] `pt-text-overflow-ellipsis` cuts off descenders for menu items

### ISSUE THREAD

**Issue by will-stone** [palantir/blueprint#2177]
### Bug report

- __Package version(s)__: 2.0.0-rc.2
- __Browser and OS versions__: Chrome 64, macOS Sierra 10.12.6

#### Steps to reproduce

1. Create a MenuItem with text that has descenders e.g. "g", "y" etc.

#### Actual behavior

<img width="259" alt="blueprint documentation 2018-02-23 13-44-48" src="https://user-images.githubusercontent.com/654103/36597352-c271d120-18a0-11e8-837a-d7c6f0488f4a.png">

#### Expected behavior

All text is visible.

This looks to be related to #1689

**Comment by adidahiya** [comment]
I think this is a regression in 2.0, or at least in the 2.0 documentation. Descenders are not cut off in 1.x menu items: http://blueprintjs.com/docs/v1/#core/components/menu.menu-item

**Comment by giladgray** [comment]
yikes, definitely due to the flex stuff. should be easy to resolve. i'm on it.

**Comment by reiv** [comment]
Can we reopen this? It doesn't seem fixed, at least not for all browser/font combinations. Here
 are some screenshots from testing on Chrome and Firefox (Windows only, sorry):

![menu-clipped-descenders](https://user-images.githubusercontent.com/205631/37544134-4619f7e0-2964-11e8-829f-f2c03ee2ee53.png)

The culprit is definitely `line-height` (currently `16px` for `MenuItem`s), which doesn't leave enough room for some fonts' descenders, and `overflow: hidden` from `pt-text-overflow-ellipsis` prevents overflow; zoom level is also a factor here, and apparently browsers have different interpretations as well. The current "one-size-fits-all" approach is unfortunately not good enough :disappointed:.

Here's a [JSFiddle](https://jsfiddle.net/v1gh3n4t/11/) for testing -- it uses `core@^2.0.0-rc.3` but the screenshots were taken using the latest `develop`.

@giladgray @adidahiya

**Comment by giladgray** [comment]
@reiv sure, it is reopened. think you could submit a fix?

**Comment by reiv** [comment]
@giladgray I'll see what I can do. I was hoping the fix would be as easy as replacing `overflow: hidden` with `overflow-x: hidden`, but that doesn't work quite the way you'd expect it to.

**Comment by giladgray** [comment]
in my experience, one should never use `overflow-x/y` as they don't do what you think/hope they do

**Comment by reiv** [comment]
Would we run into trouble elsewhere if we removed the `line-height` rule from `pt-menu-item`? Reading the SCSS gives the impression that line-height was only being used for centering the icon, but since `pt-menu-item` is a flex container, we can use `align-self: center` on the icon to line things up instead.
[JSFiddle](https://jsfiddle.net/v1gh3n4t/19/)
