### ISSUE TITLE
[Table] Unrequired cells rerendering

### ISSUE THREAD

**Issue by alxmiron** [palantir/blueprint#2183]
Hello Blueprint team
If I use table component as read-only table, where all cells can be rendered only once, how can I achieve that? I see, that all cells re-render on each scroll event now

**Comment by llorca** [comment]
Couple of suggestions:
- have you tried passing `RenderMode.NONE` to [`renderMode`](http://blueprintjs.com/docs/v1/#table-js.instance-methods)?
- could also try using the static HTML table if you don't need all the features

**Comment by adidahiya** [comment]
@AlexMarvelo what do you mean by "can be rendered only once"? Do you mean that the rows / cols / cels never change based other parts of your UI and they are non-editable? How many cells do you have? What exactly is being re-rendered on each scroll event (i.e. which function is being called excessively)? There's probably some optimizations we can make here, just want to make sure I pinpoint your issues.

**Comment by AlexMarvelo** [comment]
@llorca 
* In my case the table can be enough big with data, imported by a user. That's why table package is better than static HTML table, because of truncation function and resizing
* As I know, `RenderMode.NONE` just controls how re-rendering will be performed - by batches or all at once. But it doesn't disable re-rendering itself

@adidahiya 
Yes, amount of rows/cols/cells and their content don't change. But I don't know them in build time. All data are imported by a user.
On each scroll event the `renderCell` param is invoked (see attachment). Because of that, if I scroll enough fast, I can see some lags.

I suppose, in performance reasons, cells re-rendering should be only on resize, editing, selection, but not on scrolling. What do you think?

![feb-27-2018 12-40-01](https://user-images.githubusercontent.com/10484318/36724858-255fc2be-1bbd-11e8-9f35-6825b3e8b62c.gif)

**Comment by atav32** [comment]
@AlexMarvelo could use [React Table](https://github.com/react-tools/react-table) instead

**Comment by giladgray** [comment]
this request is not possible with the Table implementation, as the cells are virtualized so only the visible ones are rendered. the visible cells must be updated on scroll.
