### ISSUE TITLE
[Tab] Consider allowing tab content as children

### ISSUE THREAD

**Issue by aequasi** [palantir/blueprint#2202]
It seems to make more sense to me to allow specifying the content of a tab as children, instead of the title. Example:

```
<Tabs>
	<Tab id="rx" title="React">
		Some Content for the React Panel
	</Tab>
</Tabs>
```

This, imo, makes more sense than using the children as a title, since simple tabs require smashing of ugly code into the `panel` attribute:

```
<Tabs>
	<Tab id="rx" title="React" panel={<div><h1>Why I like React: </h1><ul><li>Clean</li><li>Fun!</li><li>Fast</li></ul></div>} />
</Tabs
```

Would introduce more bloat to the codebase to put that panel into its own React component.

**Comment by giladgray** [comment]
@aequasi I thought long and hard about what to do with `Tab` `children` and decided that they would be synonymous with `title` to support the panel-less use case: omitting the `panel` prop because you just want the cool slider animation, or you'll render the content elsewhere in your React tree. 

**Consider:** If you think of the `Tabs` container as the **list of clickable tab buttons**, then `children` as `title` makes much more sense, and `children` as `panel` breaks the natural DOM flow.

Additionally, I find that my panels are almost always complex enough to warrant their own subcomponents, so passing `panel={<MyPanelCmp />}` works very nicely. 

Would some documentation clear up this issue?

**Comment by aequasi** [comment]
No, documentation isn't an issue here, just a usability concern. Children as the title is (again, imo) less developer friendly. 

Thinking of `Tab` as just a button seems to be counter-intuitive, and unlike other solutions that have already been developed.

Another counterpoint: I've never had a title for a tab that has been so complex that it needed to be a child element.

From the stance of it being just a button, it makes sense, but I have an issue with it just being a button linked to another panel I guess

**Comment by adidahiya** [comment]
>  since simple tabs require smashing of ugly code into the panel attribute

this seems like a contrived example. as @giladgray said, most tab panels will be complex enough that separating them into their own component (it could be a simple function... that's not much "bloat") makes the code more readable.

for now, closing as won't fix.
