### ISSUE TITLE
Question: is there any codepen/jsfiddle/... allowing to try out features/reproduce bugs?

### ISSUE THREAD

**Issue by pcdv** [palantir/blueprint#2308]
Hi and thanks for the blueprint library, it helped me turn an application from butt-ugly to professional-grade in a few weeks while becoming a lot more productive :)

I found a small glitch in Table + Tabs combination and I wanted to submit an issue with a link to codepen or any alternative. I didn't find any and my attempts to create one failed miserably!

It would be nice if the docs or contributing guidelines included such a link. I'm thinking of something like https://codepen.io/anon/pen/OvRJzW with latest react and blueprint versions.

Thanks

**Comment by reiv** [comment]
@pcdv The docs have [instructions](http://blueprintjs.com/docs/v2/#blueprint/getting-started.cdn-consumption) on how to get the libs and all the necessary dependencies from CDN. Otherwise, here's a quick [JSFiddle](https://jsfiddle.net/tp0qcezv/) I threw together with everything and the kitchen sink included.

**Comment by pcdv** [comment]
Cool, thanks. Reproduced the bug in https://jsfiddle.net/6uLwv7c3/3/

**Comment by pcdv** [comment]
Submitted #2313 for the table/tab issue.

**Comment by pcdv** [comment]
In case someone stumbles upon this issue, there is now another very good option: codesandbox

https://codesandbox.io/s/31444v7975
