### ISSUE TITLE
Opening any popover scrolls to bottom of page in Firefox

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#231]
### Bug Report

- __Package version(s)__: 1.0.1 (blueprintjs.com)
- __Browser and OS versions__: FF 46 & 50, macOS 10.12

#### Describe the issue:

Clicking on any popover scrolls to the bottom of its overlay, which is now the bottom of the page (related: https://github.com/palantir/blueprint/pull/186#issuecomment-261658643).

**Comment by giladgray** [comment]
this is due to `position: absolute` nature of overlays. i think we should make them all `position: fixed` as in https://github.com/palantir/blueprint/issues/183#issuecomment-261074255

**Comment by giladgray** [comment]
related to #183

**Comment by cmslewis** [comment]
Okay, so building off of my work in #276, I'm now seeing the following behavior:

- *Chrome*: All popovers work as expected
- *Firefox*: All popovers _misbehave_ except for the "Input" example.
- *Safari*: All popovers _work_ except for the "Input" example.

So that's interesting. Lest I forget, the offending line seems to be in `Overlay/bringFocusedInsideOverlay` (linked [here](https://github.com/palantir/blueprint/blob/a90bf1a4e5c20d7b379001c3f2de788271aaedf6/packages/core/src/components/overlay/overlay.tsx#L287)):

`containerElement.focus()`

This is triggered by the `Portal`'s `onChildrenMount` callback.

Okay, diving back in.

**Comment by cmslewis** [comment]
In Firefox, looks like we're trying to `.focus` on the popover container before it was visible. Since the popover exists in a portal element at the bottom of the page, the browser is scrolling down to bring the portal into view before trying to focus it. Adding a `setTimeout` around the `containerElem.focus()` solves that issue.

But Safari appears to have a different problem: it's scrolling the page when `Portal` invokes `ReactDOM.unstable_renderSubtreeIntoContainer`.

Diving back in.

**Comment by adidahiya** [comment]
By the way, I'm also seeing this issue with the Overlay example in Firefox.

**Comment by cmslewis** [comment]
Been investigating this for awhile. Two interim takeaways:

1. Setting `.pt-portal` to `position: fixed` fixes the scrolling-to-the-bottom-of-the-page issue.
2. BUT setting `.pt-portal` to `position: fixed` introduces a new bug where tethered content os moved outside of its React parent due to this snippet of code in tether.js:
![image](https://cloud.githubusercontent.com/assets/443450/20904608/2a75e870-baf5-11e6-8e0b-72fd7221b6e7.png)

This leads to badness. Trying a workaround where we hotswap the position setting quickly (e.g. set to `static` for the render and tether updating, then immediately reset to `fixed`). But it's not working great at the moment.

More to come, I hope.

**Comment by adidahiya** [comment]
> I'm trying a workaround where we hot-swap the position setting quickly (e.g. set to static for the render and tether updating, then immediately reset to fixed

this sounds horrific, FWIW 😆

**Comment by cmslewis** [comment]
This whole thing is horrific. -.-

**Comment by giladgray** [comment]
@cmslewis yeah tether will do that moving thing sometimes... 
this may be useful: http://tether.io/#element-moving ⚔

**Comment by michael-yx-wu** [comment]
This also happens with context menus. For example, try right clicking on the table sortable example.
