### ISSUE TITLE
Select does not display the full list with initialContent=null and filterable=false

### ISSUE THREAD

**Issue by LittlePony** [palantir/blueprint#2336]
### Bug report

- __Package version(s)__: 2.0.0
- __Browser and OS versions__: Chrome 65, Windows

#### Actual behavior

Select does not display the full list with initialContent=null and filterable=false

#### Expected behavior

I'm not sure that this is normal behavior. if this is so then this issue - feature request

**Comment by reiv** [comment]
Repro [here](https://jsfiddle.net/ktmrdf33/9/). I think this is because of this check here:

https://github.com/palantir/blueprint/blob/e53d5d4c266d8a00c03c2b4079debee91e8337d1/packages/select/src/common/itemListRenderer.ts#L60-L62

Should work if we write `!= null` instead of `!== undefined`. Will PR in a second.

**Comment by llorca** [comment]
amazing. thank @reiv!

**Comment by reiv** [comment]
@LittlePony It turns out this *is* normal behavior according to the docs, which say [this](http://blueprintjs.com/docs/v2/#select/select-component.javascript-api) about `initialContent`:

"If explicit null, nothing will be rendered when query is empty."

So the correct approach would be to either omit `initialContent` (it's optional anyway) or explicitly set it to `undefined`, -- `null` is a special case.
