### ISSUE TITLE
<Button> Specifying type/role?

### ISSUE THREAD

**Issue by orecus** [palantir/blueprint#242]
I would like to suggest an improvement to the <button> component. I have a use case where I would like to change the type/role from 'button' to 'submit' but in the current component it seems to be hardcoded when i looked at the source.

In my use-case i would like to use the component together with formsy-react, which seems to need the type=submit to trigger (atleast in my code), for now i've solved it by creating a simple button component where I can set the type when needed inside the forms but i would prefer to just use the supplied component.

Would it be possible to consider this for the next update?

Also, if I want to suggest a few new components for the future, would you prefer one issue per suggestion or could I assemble my suggestions to one issue?

**Comment by adidahiya** [comment]
Specifying type / role for buttons: that make sense; we'd accept a PR for that. It should just be a matter of reordering the props [here](https://github.com/palantir/blueprint/blob/9ae28710616f813c4d168e40c0e299d32ceb75a2/packages/core/src/components/button/buttons.tsx#L35) so that user-provided props get spread _after_ `type` (but keep the other ones in their current intentional order).

Filing issues: this issue you filed here was well-scoped and appropriate 👍 . I don't have a general rule -- use your judgement about whether issues belong together as a single issue. If it's a bunch of small enhancements to the same component or a single root problem that propagates an issue to many components, prefer a single issue. Otherwise, more generally, FRs for separate components should be filed separately.

**Comment by giladgray** [comment]
Hah I had fixed this in #229 by putting type/role before the spreads, but that one never merged. Easy to resolve!

**Comment by orecus** [comment]
Thanks @adidahiya! I think it would be a small but great improvement, even though it seems that `formsy-react` is stalled and I'm looking at other options instead but the same problem might show itself in other similar options. :)

Regarding Issues: Great to know, I have a few suggestions on new components and improvements. I'll gather my thoughts and once I have them all sorted out I'll start adding issues for them! :+1:

**Comment by paulpooch** [comment]
Yeah I was having issues with redux-form not submitting because of this.

**Comment by paulpooch** [comment]
Hey I found a temporary workaround to this.... just put a stupid hidden submit button next to your pretty Blueprint Button.  I've actually wrapped this combo into it's own component.

```
<form>
  
  // inputs here
  
  <span>
    <Blueprint.Button>Submit</Blueprint.Button>
    <button type="submit" style={{ display: 'none' }} />
  </span>
</form>
```
