### ISSUE TITLE
Hotkey popup sorting

### ISSUE THREAD

**Issue by switz** [palantir/blueprint#2439]
### Bug report

- __Package version(s)__: 2.2.0
- __Browser and OS versions__: Mac Chrome Version 65.0.3325.181 (Official Build) (64-bit)

#### Steps to reproduce

1. Add hotkeys
2. Press `?` to open the hotkey popup

#### Actual behavior

Hotkeys are not grouped together and are out of order

#### Expected behavior

Hotkeys should be grouped together and remain in the order they are defined.

<img width="560" alt="screen shot 2018-04-30 at 4 19 13 pm" src="https://user-images.githubusercontent.com/990166/39448227-4b8fafe8-4c92-11e8-92c3-e8e7fd5a5bc7.png">

**Comment by giladgray** [comment]
@switz these hotkeys are in fact grouped as expected, you just have a lot of them in the "Default Hotkeys" group. 

i'll agree the order is not ideal. would alphabetization be better? any other concrete suggestions for API changes to resolve your issue?

**Comment by switz** [comment]
Perhaps I misunderstood how the grouping should work. In the image, the `Playback` group has one hotkey at the top and some at the bottom. Is that intended? I expected each group to show all of its own hotkeys together.

For sorting, it seems like the hotkeys could be placed in the order the groups are defined (first defined group shows up first, and so on) and then each hotkey be sorted in the order defined.

If we wanted to get fancy we could add a `sortBy` prop to hotkeys or a `groupSorting` array to the `<Hotkeys>` component, but I think that may be overkill.

As an aside, a `hideInPopup` prop or the ability to group multiple hotkeys that share an event might be a nice addon. But that might not be in your scope (some of my hotkeys have multiple combo shortcuts).

I'm also building out custom hotkeys for my users, so I wonder if you'd accept a PR for a `<HotkeyTarget />` component that let users input a hotkey (perhaps built into the hotkey popup).

Anyway, thanks for the work on this library. It's awesome 😃

**Comment by StommePoes** [comment]
Something to be aware of if hotkeys do end up being reassigned for clarity: WCAG 2.1 is now a recommendation of the W3C and some of your hotkeys are single character-key shortcuts: https://www.w3.org/TR/WCAG21/#character-key-shortcuts

**Comment by jeroenvisser101** [comment]
I noticed this behaviour as well, and digging through the code, it seems like this code is responsible for it:

https://github.com/palantir/blueprint/blob/009651c71e897f5e711a4928959d229fbf822aa8/packages/core/src/components/hotkeys/hotkeys.tsx#L47-L56

I think we could easily solve this in two different ways:

1. If both compared hotkeys are global, ignore and do the localeCompare, like so:
   ```ts
   hotkeys.sort((a, b) => {
     if (a.global && !b.global) {
         return -1;
     }
     if (b.global && !a.global) {
         return 1;
     }
     return a.group.localeCompare(b.group);
   });
   ```
2. We first reduce the list of hotkeys to a list of hotkey groups, and then loop over those in the section below. That would mean that we don't have to keep the name of the last group around, since we already have a list of groups. We can also then decide to (optionally) sort the hotkeys by label:
https://github.com/palantir/blueprint/blob/009651c71e897f5e711a4928959d229fbf822aa8/packages/core/src/components/hotkeys/hotkeys.tsx#L58-L67

**Comment by jeroenvisser101** [comment]
I've drafted a PR for solution 1. The algorithm is changed a little for readability, but should be the same.
