### ISSUE TITLE
[TagInput] Warning: A component is changing an uncontrolled input of type undefined to be controlled.

### ISSUE THREAD

**Issue by fsenart** [palantir/blueprint#2483]
### Bug report

- __Package version(s)__: core 2.3.1
- __Browser and OS versions__: latest chrome on mac or linux

#### Steps to reproduce

Run the doc example of TagInput:
- http://blueprintjs.com/docs/v2/#core/components/tag-input
- https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/core-examples/tagInputExample.tsx

#### Actual behavior
On key down, when writing something in the input:

> Warning: A component is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

#### Expected behavior

No warning

#### Possible solution

`inputValue ` is by default `undefined`. To remove this warning there are two possible solutions:

1. One should add an empty `inputValue` when using `TagInput`: 
    ```
    <TagInput ... inputValue=""/>
    ```
2. Patch https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/tag-input/tagInput.tsx#L178 to have a default empty string for `inputValue`.

#### Remarks

When exploring the current live doc with React Dev Tools, the initial `inputValue` state is set to an empty string. But can't figure out how, where or when this default empty string is set. Also when using `TagInput` locally the React Dev Tools shows that the initial `inputValue` state is not set.

**Comment by stephensong** [comment]
Fwiw, I have been sporadically seeing the same warning, only on Checkbox components, and I was never able to nail it down, as it seemed to go away of it's own accord.

On reading the above, I am guessing that it actually comes from supplying a falsy value for checked (undefined or null) rather than an explicit false.  

I confess I tend to rely rather to much on falsiness, but it seems to work just fine for all my SQL stuff, which is why I keep doing it.  But if anyone wanted to put an extra !! into the Checkbox component, I expect there would be many people who would prefer not to have to figure it out for themselves.

Many thanks for your great software.
