### ISSUE TITLE
All Table rows are not rendered inside tab panel

### ISSUE THREAD

**Issue by dineshvgp** [palantir/blueprint#2624]
Source code: [codesandbox link](https://codesandbox.io/s/mmn3y1j288)

Steps to reproduce:
1. Please  [click this link](https://mmn3y1j288.codesandbox.io/) to open the app in a new window.
2. Click Invitees and Registrants tab.
3. There are only 4 rows displayed instead of 10. But if we scroll, the remaining rows are getting displayed.
4. Now load, Invitees and Registrants tab directly by [clicking this link](https://mmn3y1j288.codesandbox.io/invitees).
5. We can see all 10 rows getting displayed.

I seriously have no idea about the 3rd point, why it is behaving that way.

**Comment by dineshvgp** [comment]
Update:
Passing `renderActiveTabPanelOnly={true}` to tabs component fixed this.

**Comment by giladgray** [comment]
@dineshvgp this is due to how table computes its dimensions. when it's not visible (hidden tab panel) it can't accurately compute its appearance. enabling `renderActiveTabPanelOnly={true}` is definitely a correct way to solve this, though it will cause the table instance to be destroyed and remounted when switching tabs (which is easy to account for, you just have to be aware). 

another approach could be to add a call to `forceUpdate()` after switching tabs to cause the table to re-measure itself.
