### ISSUE TITLE
Can not find documentation how to use custom SVG icon with Blueprintjs components

### ISSUE THREAD

**Issue by avkonst** [palantir/blueprint#2643]
#### Environment

- __Package version(s)__: 2.3.1
- __Browser and OS versions__: n/a

#### Question

I can see release notes for version 2 mention that custom SVG icons can be used. However, I can not find in the documentation how to add or refer to a custom icon. It would be good to have an example how to use a custom icon imported from these 2 packages: http://react-icons.github.io/react-icons/index.html and https://github.com/leungwensen/svg-icon

Thanks in advance

**Comment by giladgray** [comment]
@avkonst this is not spelled out in the docs but it's as easy as `<Button icon={<ReactIcon />} />`

**Comment by petersobolev** [comment]
I'm using BlueprintJS in my project (I really like it), but there is a problem using custom SVG icons. There are couple solutions, but no one of them is perfect. 

Simplest solution is:

```
const my_icon = <svg data-icon="my_icon" width="16" height="16" viewBox="0 0 1024 1024">
    <desc>my_icon</desc>
    <path d="..."></path>
  </svg>
```

It works more or less for cases like this:

```
<Button
    icon={my_icon}
/>

<Button
    icon=<Icon icon={my_icon} />
/>

<Icon icon={my_icon} />
```

but color is always inherited from parent tag and I can't change it using <Icon .. color=../> or <Icon .. style={{color:..}} and have to wrap <Icon/> with <span> or like that.

The second problem with DateInput fields. Solution I mentioned works but icon is drawn outside of date field. My solution is quite cumbersome (but it works):

```
export const my_icon = <span icon="my_icon" className="bp3-icon">
  <svg data-icon="my_icon" width="16" height="16" viewBox="0 0 1024 1024">
    <desc>my_icon</desc>
    <path d="...">
    </path>
  </svg>
</span>


<DateInput 
    leftIcon: <Icon icon={my_icon}/>,
    ... 
/>

```


P.S. Also it seems there are no ways to set custom icon using strings: icon="my_icon" because <Icon/> used only constants imported in icon\icon.tsx
