### ISSUE TITLE
[FormGroup] Auto-generate the labelFor/id

### ISSUE THREAD

**Issue by r03** [palantir/blueprint#2686]
#### Feature request

Maybe it is possible to auto-generate the labelFor/id in a FormGroup if no values are given?

#### Examples

The FormGroup could then be make like this:
```
<FormGroup
    helperText="Helper text with details..."
    label="Label A"
    labelInfo="(required)"
>
    <InputGroup placeholder="Placeholder text" />
</FormGroup>
```

The result would be something like this:
```
const id = uniqueId("id_");

<FormGroup
    helperText="Helper text with details..."
    label="Label A"
    labelFor={id}
    labelInfo="(required)"
>
    <InputGroup id={id} placeholder="Placeholder text" />
</FormGroup>
```

**Comment by giladgray** [comment]
@r03 it is not possible to generate the ID inside the component for a number of reasons:

1. the only link btw FormGroup and Input is in the parent: the FormGroup doesn't know about its children, nor should it.
1. generating an ID would not be stable across re-renders and is simply a non-starter in server-side rendering (for the client to generate the same ID as the server, and for it to be unique).
1. your code sample `uniqueId()` is about as simple as it gets, and doesn't require any fancy logic in blueprint. use whatever strategy you like for generating your own IDs. so simple and so maintainable.

so that's your answer.

**Comment by r03** [comment]
Thanks for your answer !
