### ISSUE TITLE
Set "initial" selectedItem with Suggest (and maybe Select)?

### ISSUE THREAD

**Issue by indigoviolet** [palantir/blueprint#2784]
#### Environment

- __Package version(s)__: 3.1

#### Question

Is there a way to pass in the selected item in a `Suggest` and use it in a controlled manner? (This is currently `state.selectedItem`)?

**Comment by indigoviolet** [comment]
I guess I just have to fall back to `Select` and control the target directly.

**Comment by giladgray** [comment]
@indigoviolet there is not but I'd happily review a PR to add `props.selectedItem?`

**Comment by alexpriceonline** [comment]
Really need this! I've not used TS before though, do you have a development flow I should follow?

**Comment by giladgray** [comment]
@alexpriceonline https://github.com/palantir/blueprint/blob/develop/CONTRIBUTING.md 👍 👍

**Comment by giladgray** [comment]
oops this issue is not actually fixed. we've added controlled support in #2874 but no "initial" support. 

cc @danilotorrisi if you wanna hit this with `defaultSelectedItem`

**Comment by danilotorrisi** [comment]
Sure, I can easily add the defaultSelectedItem in another PR. What do you think should happen if both defaultSelectedItem and selectedItem is provided? IMHO the controlled selectedItem should always win over default uncontrolled item, what.

**Comment by giladgray** [comment]
@danilotorrisi controlled props always win over uncontrolled, you are correct.

**Comment by ChristianIvicevic** [comment]
Sorry for necro-ing this issue, but I noticed that this behavior only exists for Suggest, but not for Select. Is there any plans to implement that one as well?

**Comment by adidahiya** [comment]
@ChristianIvicevic you get to render the children, and the initial selected item for Select. So you have control over what is displayed there. I don't think you need a new prop to do that: https://github.com/palantir/blueprint/blob/0750f4d5fd9775bbada07feb588abf9666d55ad6/packages/docs-app/src/examples/select-examples/selectExample.tsx#L120

**Comment by ChristianIvicevic** [comment]
Sorry for not being too detailed. I was referring to the active item in the popover of the Select. For instance, the button in the following screenshot has the selected value as expected but I can't easily select the corresponding item in the popover as it clashes with keyboard input:

![Screenshot 2021-02-08 at 17 26 03](https://user-images.githubusercontent.com/45569997/107248779-ed797080-6a32-11eb-8495-54e4872f2880.png)

For instance if my item renderer sets `MenuItem.active` to `true` for the currently selected element, I can no longer display the focused element when pressing the arrow buttons.

In the best-case I'd like for the active item and selected item to be uncontrolled and being able to set the default active item since I only listen to `onItemSelect` and `MenuItem.onClick` respectively.

**Comment by adidahiya** [comment]
@ChristianIvicevic use `activeItem` and `onActiveItemChange`
