### ISSUE TITLE
Date range picker picker broken in month of December

### ISSUE THREAD

**Issue by gscshoyru** [palantir/blueprint#289]
### Bug report

- __Package version(s)__: 1.1.0
- __Browser and OS versions__: Chrome (latest) on macOS

#### Steps to reproduce

1. Have the date in your computer be December first. Or probably any day in December. 
2. Go to http://blueprintjs.com/docs/#components.datetime.daterangepicker. 

#### Actual behavior

Shows December 2016 as the month on the left, and January _1996_ as the month on the right. 
Furthermore, you can go back a month with the arrow keys to get you something sensible, but it seems impossible to go _past_ 2016 now, even picking a year from the dropdown doesn't seem to work. 

#### Expected behavior

Shows January 2017, also lets you navigate past 2016.

**Comment by giladgray** [comment]
this is actually expected behavior _for the default DRP props_: `maxDate` defaults to the end of the current year, which just happens to be this month. (why? because future dates are rarely useful in analytical apps--it's all data from the past.)

![image](https://cloud.githubusercontent.com/assets/464822/20807977/c0a5db7c-b7b5-11e6-8168-338a886d8b2e.png)

I'll agree that the "wrapping" behavior is awkward, but that happens inside `react-day-picker`, a third-party library that has served us very well thus far.

**Comment by gscshoyru** [comment]
Didn't realize about the default max date behavior, that makes a certain amount of sense. 

If we can't avoid the wrapping behavior because of the component we're using (which I get) then maybe just detect if we're opening a date at the end of our range, and go back a month instead of wrapping funny.

**Comment by llorca** [comment]
So, the bug here is actually that the date range picker should never display months that are out of range. If you look at the [docs](http://blueprintjs.com/docs/#components.datetime.daterangepicker), January 1996 is showing although it's out of range. If you click on the left arrow near December, you'll see that there's no right arrow to go back to January 1996.

I think the fix is to simply have the last month of the available range be displayed on the right side of the range picker.

**Comment by VimLeSai** [comment]
in DateRangePicker in the first calendar, I'm not able to select December because it is like that December will be on another calendar only. so can do something so I can it in both calendar?
