### ISSUE TITLE
provide defaults for itemRenderer and tagRenderer in Select/Multiselect

### ISSUE THREAD

**Issue by tnrich** [palantir/blueprint#2973]
I don't know why defaults weren't provided for the item and tag renderers. Is there any reason for this? Seems like a no brainer to me.. 

The way it stands seems like a good way to have a ton of slight differences in selects throughout your app.

Just my 2 cents :)

**Comment by giladgray** [comment]
I cannot provide defaults because the item type is generic, so `Select` literally knows _nothing_ (and can never know anything) about the given data. it could be an object with 50 keys or it could be a number. 

this is why `itemDisabled` exists - teach the component how to tell if a generic item is disabled.

**Comment by giladgray** [comment]
the best option here would be a `SimpleSelect` wrapper that uses a known item type like `IOptionProps`. but defaults do not work in the general case.

**Comment by tnrich** [comment]
Why not have the default assume you're being passed a list of options like: 

```
const options = [
  { value: 'chocolate', label: 'Chocolate' },
  { value: 'strawberry', label: 'Strawberry' },
  { value: 'vanilla', label: 'Vanilla' }
]
```

while maintaining the ability to easily override that if necessary?
