### ISSUE TITLE
Plans with version 2?

### ISSUE THREAD

**Issue by westrem** [palantir/blueprint#2997]
#### Environment

- __Package version(s)__: 2.*

#### Question

Hi there,
I'd just like to know, if there's somewhere information on what is the expected roadmap/support period for Blueprint v2.* 

Like, if there are some expectations that this version will be maintained for X upcoming period and then will be deprecated totally in favour of v3.* etc

In our company we are currently using v2 and we would like to know what we can expect and whether migrating to v3 is something we should do rather sooner or if we are good with sticking to v2 for some time more.

Thank you

**Comment by giladgray** [comment]
Hi @westrem, glad to hear your company is using Blueprint! Unfortunately v2 was deprecated in favor of v3 _the moment it came out._ Turns out v2 was unusable by most of Palantir due to its hard dependency on React 16 😢

So please upgrade to v3 and profit with the rest of us! The migration is not hard and is definitely worth it (especially since we'll never see another 2.x release).

**Comment by giladgray** [comment]
@westrem out of curiosity, how are you using Blueprint? anything you can share? i love seeing it in the wild!
