### ISSUE TITLE
Omnibar initial and empty content not shown when using `itemListPredicate`

### ISSUE THREAD

**Issue by kousun12** [palantir/blueprint#3174]
#### Environment

- __Package version(s)__: 
```
    "@blueprintjs/core": "^3.9.0",
    "@blueprintjs/select": "^3.3.0"
```
- __Browser and OS versions__: Chrome, OSX

#### Steps to reproduce
A basic Omnibar with an `itemListPredicate` that always returns everything does not show results initially or on empty string queries.

```javascript
const list = ['foo', 'bar']
  <Omnibar
    items={list}
    itemListPredicate={() => list}
    itemRenderer={s => s}
  />
```

#### Actual behavior

The results list is not shown despite, returning a list of results.

#### Expected behavior

A result list is shown initially, and also on empty string queries (type, then delete all text). From the docstring:

```javascript
    /**
     * React content to render when query is empty.
     * If omitted, all items will be rendered (or result of `itemListPredicate` with empty query).
     * If explicit `null`, nothing will be rendered when query is empty.
     *
     * This prop is ignored if a custom `itemListRenderer` is supplied.
     */
    initialContent?: React.ReactNode | null;
```

**Comment by giladgray** [comment]
@kousun12 you haven't provided either the `initialContent` or `noResults` props above so of course they don't appear. also, `noResults` only appears in all items are filtered away, but your predicate never allows that state. and finally, omnibar by default does not show any `initialContent` ([it defaults to `null`](https://github.com/palantir/blueprint/blob/develop/packages/select/src/components/omnibar/omnibar.tsx#L68))

not sure there's a real bug here.
