### ISSUE TITLE
Memory leak in automated testing with jest

### ISSUE THREAD

**Issue by Creosteanu** [palantir/blueprint#3188]
#### Environment

- __Package version(s)__: 3+ (tested from 3.0.1 to latest)
- __Browser and OS versions__: jest - tested with ubuntu and windows

#### Steps to reproduce

1. https://gitlab.com/creosteanu/jest-blueprint-leak
2. yarn
3. yarn test
4. watch the memory usage rise to infinity

#### Actual behavior

Memory increases with each new test file.

#### Expected behavior

Memory usage does not increase across test files.

#### Possible solution

Nodejs heap inspection seems to reveal that the problem is surrounding HTMLSelectElement although I am not certain.

The provided example project is pretty specific and should allow easy reproduction (and hopefully fixing).

We are relying on Blueprint as a core component of our react stack and the current problem is an impediment for our automated tests.

Please advise.

**Comment by giladgray** [comment]
@Creosteanu please continue investigating, not enough information above. we don't use jest on Blueprint because we rely on a real browser environment so I can't offer immediate support for this.

**Comment by Creosteanu** [comment]
@giladgray I went deep down the rabbit hole to find the true source of this.

As always in our industry, the true culprit is Internet Explorer.

The source comes from a IE fix written in 2015 inside the dom4 dependency of blueprint. The fix creates a circular reference which carries over from one test execution to the next and creates a monster.

I have adjusted the provided repo example to showcase the exact problem.

I have created a fork of dom4 and submitted a merge request to the original library. I will let you know if it gets accepted. The PR can be found here: https://github.com/WebReflection/dom4/pull/48.

**Comment by Creosteanu** [comment]
@giladgray this is unexpected. It seems dom4 repository owner @WebReflection incorporated a relevant safeguard after my PR.

Regenerating the lock file will take the new dom4 release which resolves the problem!

This issue can be closed.

**Comment by WebReflection** [comment]
> As always in our industry, the true culprit is Internet Explorer.

😂 ... so true ... **however** ...

> The fix creates a circular reference which carries over from one test execution to the next and creates a monster.

The elephant in the room is that @giladgray running code on real environment would've never had any issue with `dom4` while jest doesn't cleanup its DOM environment after each execution test.

Jest is accordingly a very memory leak prone environment to run any test. I'd suggest you switch to real browsers, even headless, since there are various solutions these days, and you know you actually run a real, fresh new env, each time, not one that caries and leaks previous test results / patches.

This is beyond dom4, and if I were you, I'd file an issue in Jest repository too.

Thanks for pointing out the issue and further explaining it, though 👋

**Comment by giladgray** [comment]
@WebReflection coming in hot! 

thanks for figuring this out @Creosteanu. i'll upgrade our dom4 dependency version so this gets brought in by default.
