### ISSUE TITLE
Icon titles don't show as tooltips

### ISSUE THREAD

**Issue by invliD** [palantir/blueprint#3214]
#### Steps to reproduce

1. `<Icon icon="error" title="No good!" />`

#### Actual behavior

The title is not shown in a tooltip

#### Expected behavior

The title is shown as a browser tooltip, like any other element's `title` prop

#### Possible solution

Put the title on the span around the icon, not in a `desc` element inside the icon.

The current purpose of `title` seems to be what should be called `alt`

**Comment by giladgray** [comment]
little context here: https://github.com/palantir/blueprint/issues/2321, https://github.com/palantir/blueprint/issues/2410. the original browser tooltip behavior was very obnoxious because _every_ icon would get a browser tooltip, so i switched the SVG element to one that provides the same a11y but doesn't show a tooltip.

i see valid uses for _occasional_ browser tooltips, but it can't be the default behavior.

given that, we can't repurpose the existing `title` prop as that would be an API break (per the docs: "This string does not appear in normal browsers...").

@invliD @gabeboning how about adding an `htmlTitle` prop that sets `title` on the wrapper DOM element? in v4 we can switch the names around.

**Comment by giladgray** [comment]
fixed in #3216
