### ISSUE TITLE
Customise the hotkeys dialog text

### ISSUE THREAD

**Issue by lyptt** [palantir/blueprint#3228]
#### Environment

- __Package version(s)__: 
"@blueprintjs/core": "^3.10.0"
"react": "^16.6.3"
- __Browser and OS versions__: 
Any, any

#### Question

Is it possible to customise the text that appears on the hotkeys dialog e.g. "Global hotkeys"? The text updates automatically for the hotkey entries themselves, but I don't appear to have an option for the title itself.

On a related note, is it possible to tweak the values of the key names themselves too? This is all in the name of i18n, so I'm trying to make sure I can have as much as possible be translatable.

**Comment by giladgray** [comment]
@lyptt none of these things are currently possible. I am definitely happy to discuss proposals and review PRs!

**Comment by warpdesign** [comment]
I am currently translating my blueprint app and just noticed there was no way to change the "Global hotkeys" text. Unfortunately this means I have to disable the hotkeys dialog because there is no way I can let appear some random English strings in my localized app.

@giladgray any idea what would be the best way to implement it? Maybe I can look into it if you point me in the right direction.

**Comment by giladgray** [comment]
@lyptt @warpdesign there is a [`setHotkeysDialogProps()` method](([source](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/hotkeys/hotkeysDialog.tsx#L140))) exported from the root that should be used to set props on the dialog singleton.

@warpdesign to implement this, you'll need to add some new props to the hotkeys dialog to allow customizing that text.

**Comment by warpdesign** [comment]
Also, there are some text that may appear in the shortcuts themselves, like `mod + right' would show <kbd>⌘</kbd> + <kbd>→ right</kbd>.

I guess right shouldn't appear, or there should be a way to customize it too.
