### ISSUE TITLE
In latest version, popover is visible even though element is not within viewable space.

### ISSUE THREAD

**Issue by mvangelist** [palantir/blueprint#3250]
#### Environment

v3.9.0 

#### Steps to reproduce

Seeing this in project implementation as well as when using the demo page (https://blueprintjs.com/docs/#core/components/popover) the popover is still visible when element is scrolled out of the visible space. Using v2.3.1 from demo page, the popover works correctly.

Settings:

Click (target-only) 
Position: right
preventOverflow: scroll to parent

#### Actual behavior

Popover is still visible when element is scrolled out of view-able space. 

#### Expected behavior

Popover should hide if element is not within view-able space.

#### Possible solution

Hide popover when element is not in view-able space.

**Comment by jaamison** [comment]
This is expected and by design. This behavior is governed by the underlying Popper.js library. In turn, Popper.js handles all such behavior using pluggable modifiers that you can customize and configure. `<Popover>` takes a `modifiers` prop that gets passed directly to the underlying Popper instance, so you are free to override any (well, almost any) Popper.js config options.


In your case, you may be interested in Popper's built-in hide modifier ([https://popper.js.org/popper-documentation.html#modifiers..hide](https://popper.js.org/popper-documentation.html#modifiers..hide)). 


Try experimenting with:
```jsx
<Popover
  modifiers={{
    hide: {
      enabled: true
    }
  }}
/>
```


in conjunction with your existing overflow settings.

**Comment by mvangelist** [comment]
Thanks for looking.  I have tried that and without the blueprint wrapper, it works.  But with it,  it does not.  However,  in v2 of blueprint, it still worked also. It appears to be broken in v3.

**Comment by mvangelist** [comment]
In the steps to reproduce, i put the settings there.  Same settings were used in v2 and v3 page on blueprint's site. I've tried both scroll to parent and viewport.

**Comment by adidahiya** [comment]
We might revisit this when upgrading to Popper.js v2 (#4023) but I'm closing this for now as a stale issue
