### ISSUE TITLE
Popover crashes the application when running on IE 11

### ISSUE THREAD

**Issue by budaaaa** [palantir/blueprint#3346]
#### Environment

- __Package version(s)__:  ^2.3.1"
- __Browser and OS versions__: Windows 7, IE 11

#### Steps to reproduce

1. Create a simple popover

```
<Popover
   interactionKind="hover"
   content={<div className="u-padding-10">Popover content! </div>}
   position="top-left"
>
  <span className="u-cursor-pointer">Text</span>
</Popover>
```

2. Run app on IE 11
3. Try to hover the popover

#### Actual behavior

App crashes throwing the following error 
TypeError: Object doesn't support property or method 'closest'
TypeError: Object doesn't support property or method 'remove'

#### Expected behavior
Popover should appear

#### Possible solution

Adding the following Polyfill should solve the problem

```
if (!('remove' in Element.prototype)) {
	Element.prototype.remove = function() {
		if (this.parentNode) {
			this.parentNode.removeChild(this);
		}
	};
}

if (!Element.prototype.matches) {
	Element.prototype.matches = Element.prototype.msMatchesSelector ||
		Element.prototype.webkitMatchesSelector;
}

if (!Element.prototype.closest) {
	Element.prototype.closest = function(s) {
		let el = this;

		do {
			if (el.matches(s)) return el;
			el = el.parentElement || el.parentNode;
		} while (el !== null && el.nodeType === 1);
		return null;
	};
}
```

**Comment by adidahiya** [comment]
You need to make sure dom4 is on the page. It should be getting imported into your bundle (if you're using a packager) [through this line](https://github.com/palantir/blueprint/blob/a44ce29f957c8268ef6452081e721b28eaef2c33/packages/core/src/components/index.ts#L11). Otherwise if you are using the already bundled blueprint core JS file, you need to bring your own dom4 (see the usage docs).

**Comment by budaaaa** [comment]
Thanks!
