### ISSUE TITLE
[DateInput] Crash when the date is typed manually

### ISSUE THREAD

**Issue by TheAifam5** [palantir/blueprint#3394]
#### Environment

- __Package version(s)__:
```
    "@blueprintjs/core": "~3.14.1",
    "@blueprintjs/datetime": "~3.7.1",
    "@blueprintjs/icons": "~3.6.0",
    "@blueprintjs/select": "~3.7.0",
```
- __Browser and OS versions__: Firefox 66.0b12 on ArchLinux

#### Steps to reproduce

1. Install DateTime package
2. Bind onChange and inputProps.onChange to set the value in state
3. Bind value property to state
4. Type the date manually.

Binding only "onChange" property (not from inputProps") will does also a crash after the user press on Enter.

#### Actual behavior
Type something like: 02/02/2 <- Next number will crash the page.

#### Expected behavior

OnError callback should be called instead crashing.

#### Possible solution

None

**Comment by adidahiya** [comment]
Can you share the code where you're using `<DateInput>`? Typing a date in the documentation example doesn't crash the page, so we'll need more info to debug this problem.

**Comment by TheAifam5** [comment]
Example code...


```ts
// Props
const name = 'birthday';
const defaultValue = new Date();
const browserLocale = (window.navigator as any).userLanguage || window.navigator.language;
const value = "0001-01-01T00:00:00Z"; // or undefined

// Rendering (FunctionComponent)
const handleChange = (selectedDate: Date | null, isUserChange: boolean) => {
    formik.setFieldValue(name, selectedDate ? selectedDate : undefined);
};

const value = moment(_.get(formik.values, name, defaultValue)).toDate();
const momentFormatter = getMomentFormatter('L');

return (
    <DateInput
        {...momentFormatter}
        locale={browserLocale}
        {...dateProps}
        value={value}
        inputProps={{
            onChange: formik.handleChange,
            onBlur: formik.handleBlur,
            name,
        }}
        onChange={handleChange}
    />
);
```

**Comment by adidahiya** [comment]
btw, `inputProps.onChange` and `inputProps.onBlur` get ignored by DateInput... [see this code](https://github.com/palantir/blueprint/blob/a9197188d73058f850c01355b23197a53df5299f/packages/datetime/src/dateInput.tsx#L214)

what is `formik`? Is it possible for you to create a minimal bug repro based on [this code sandbox](https://codesandbox.io/s/nko3k41y60)?

**Comment by silviodeligios** [comment]
I have the same issue without using formik, when I type a date out of range the whole page crash... this don't seems to happen in the documentation example, i can't understand why

**Comment by silviodeligios** [comment]
in my case the problem came out when i add the moment locale utils:
``` es6
import MomentLocaleUtils from 'react-day-picker/moment'

<DateInput
    localeUtils={MomentLocaleUtils}
/>
```

**Comment by silviodeligios** [comment]
> btw, `inputProps.onChange` and `inputProps.onBlur` get ignored by DateInput... [see this code](https://github.com/palantir/blueprint/blob/a9197188d73058f850c01355b23197a53df5299f/packages/datetime/src/dateInput.tsx#L214)
> 
> what is `formik`? Is it possible for you to create a minimal bug repro based on [this code sandbox](https://codesandbox.io/s/nko3k41y60)?

Please take a look at [this sandbox](https://codesandbox.io/s/romantic-lake-bony4?fontsize=14), if you try to write an out of range date manually the page will crash

**Comment by adidahiya** [comment]
works fine for me

![2019-06-18 12 20 16](https://user-images.githubusercontent.com/723999/59701377-81922680-91c3-11e9-903d-2ce217b29e0f.gif)

**Comment by silviodeligios** [comment]
Sorry my bad, i was using the wrong format, try to wrote 21/12/1991 to see the error. maybe it's not a date range error but if you use the wrong format alla the page crash

**Comment by vasco3** [comment]
I noticed that maxDate is set to December 31st of the current year and it seems there is no way to override that prop.

**Comment by barrymay** [comment]
Hi @adidahiya I think the code sandbox below shows the problem well with the blowing up example referred to by a number of other devs:  
https://codesandbox.io/s/angry-morse-hn3rm?file=/src/App.js

To see the problem:
- Enter 1/1/1999.  Hit 'enter'
- The app blows up

I was trying to figure out why the blueprint docs don't have this problem, but the reason (from what I can tell) is that DatePicker's validateProps doesn't get run in production mode, so hence production runs would behave ok as no thrown Error would occur. 

ErrorBoundaries (as has been suggested in other GitHub issues) don't appear to be a good workaround for this IMO, because you don't want the component to blow up in the first place due to this situation.  From my perspective, I just want it to report "Out of range" and allow the user to fix it.

I feel the best short-term alternative is to have the blueprint team create an internal-to-blueprint DatePicker override with a validateProps function that doesn't throw, and use that inside DateInput (if you feel validateProps for DatePicker is helpful to start with).  

Happy to hear any alternatives you can suggest! Thanks in advance.

**Comment by adidahiya** [comment]
This is essentially the same issue as https://github.com/palantir/blueprint/issues/3407 and https://github.com/palantir/blueprint/issues/2965. I created https://github.com/palantir/blueprint/issues/4251 to combine these tickets and present my current thoughts on the issue.
