### ISSUE TITLE
Active tab indicator doesn't update when font is changed

### ISSUE THREAD

**Issue by shravan2x** [palantir/blueprint#3491]
#### Environment

- __Package version(s)__: 3.15.1
- __Browser and OS versions__: Chrome 73

#### Steps to reproduce

1. Create a tabs component that uses an external font

#### Actual behavior

The active tab indicator is misaligned because it used the width of the original font.

#### Expected behavior

The indicator should have recalculated the new width if possible. Otherwise, an API method could be added to recalculate it.

**Comment by shravan2x** [comment]
Another idea is a `renderActiveTabIndicator` method that users could just pass in.

**Comment by shravan2x** [comment]
@adidahiya Has this been resolved with a recent change?

**Comment by adidahiya** [comment]
No, I'm just cleaning up old issues which don't have any progress and apparently low interest from the community.

I would recommend adjusting your font styling so that the fallback font and the custom font end up displaying with similar layout dimensions (width/height). Also consider adjusting properties like `font-display` ([see this article](https://web.dev/avoid-invisible-text/)).
