### ISSUE TITLE
[Table] all EditableCell re-render every time on focus change in Table with enableFocusedCell={true}

### ISSUE THREAD

**Issue by HZ-labs** [palantir/blueprint#3642]
#### Environment

- __Package version(s)__: @blueprintjs/core: 3.17.1, @blueprintjs/table: 3.6.0
- __Browser and OS versions__: 

Link to a minimal repro: https://codesandbox.io/s/blueprintjs-rerender-editablecell-enablefocusedcell-t7uf8

#### Steps to reproduce

1. Create Table with enableFocusedCell = true and EditableCell
1. Click on some Cell

#### Actual behavior

http://g.recordit.co/PQ3R4HDBgf.gif
![PQ3R4HDBgf](https://user-images.githubusercontent.com/1663933/60589702-d37da380-9da2-11e9-82f9-8727945eef07.gif)

#### Expected behavior

Update Cell only if it is changed
like enableFocusedCell = false:
http://g.recordit.co/SwS3Rd7mwH.gif
![SwS3Rd7mwH](https://user-images.githubusercontent.com/1663933/60589720-dd9fa200-9da2-11e9-8123-6719d05717fa.gif)

**Comment by tanmoyopenroot** [comment]
Hi @HZ-labs,
The re-rendering was due to the passing of an anonymous function.

![Screenshot from 2019-07-09 14-54-32](https://user-images.githubusercontent.com/25791025/60876480-98bfb380-a259-11e9-87db-1f23319a4aa3.png)

Therefore after every shallow comparing the props `shouldComponentUpdate` would return true.

check `shouldComponentUpdate` function
[https://github.com/palantir/blueprint/blob/develop/packages/table/src/cell/editableCell.tsx#L116](url)

It's your codesandbox example with some tweaks [https://codesandbox.io/s/blueprintjs-rerender-editablecell-enablefocusedcell-w2spw](url)
