### ISSUE TITLE
is there any way to change basic color intent (primary, success, danger, etc) with choosing color in variables.scss ?

### ISSUE THREAD

**Issue by renjiza** [palantir/blueprint#3673]
i used version 3.*
for example intent color primary i see intent "success" color put on $green3 color from variable

i want to change this intent color with $forest3,

is any way to do that ?

thanks before

**Comment by adidahiya** [comment]
You can build blueprint.css yourself using the Blueprint Sass sources distributed in the `/src` folder in the NPM package. All the variables are set as [`!default` values](https://sass-lang.com/documentation/variables#default-values) which you can override. For example, you can change intent color aliases: https://github.com/palantir/blueprint/blob/1bfd1e42303d2626bfc3923eec2195ab4dc696d2/packages/core/src/common/_color-aliases.scss#L4

Instead of using `@import "~@blueprintjs/core/lib/css/blueprint.css"`, you would import `"~@blueprintjs/core/src/blueprint.scss"` _after_ changing the relevant variables.

**Comment by renjiza** [comment]
i dont know why on me its doesn't work
on top of my index.scss (all my style is in here)

@import '~normalize.css/normalize';
$ns: ns;
@import '~@blueprintjs/core/lib/scss/variables';
@import "~@blueprintjs/core/src/blueprint.scss";
@import '~@blueprintjs/icons/lib/css/blueprint-icons.css';

on node_modules/@blueprintjs/core/src/common/_color-aliases.scss
i try change to $pt-intent-primary: $indigo3 !default;

doesnt change for on my example 
<Button text="example button" intent={Intent.PRIMARY} />

do i miss something ?

**Comment by renjiza** [comment]
its work , but when i hover the button its still take blue color

**Comment by adidahiya** [comment]
@renjiza you'll have to adjust more variables, like this one:

https://github.com/palantir/blueprint/blob/1bfd1e42303d2626bfc3923eec2195ab4dc696d2/packages/core/src/components/button/_common.scss#L89

There's no first-class support for doing this kind of theming, so you'll have to dig through the Sass source to figure out all the necessary adjustments.

**Comment by renjiza** [comment]
okay, thank you so much

**Comment by jufemaiz** [comment]
> no first-class support for doing this kind of theming

Damn. There goes where I was headed.

**Comment by dapte** [comment]
me too
