### ISSUE TITLE
Docs for DateRange show the wrong type (null should be undefined)

### ISSUE THREAD

**Issue by elilambnz** [palantir/blueprint#3838]
#### Environment

- __Package version(s)__: @blueprintjs/datetime 3.9.2
- __Browser and OS versions__: N/A

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-wrskg

```
Type 'null[]' is missing the following properties from type '[Date | undefined, Date | undefined]': 0, 1ts(2739)
dateRangePicker.d.ts(75, 5): The expected type comes from property 'value' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<DateRangePicker> & Pick<Readonly<IDateRangePickerProps> & Readonly<{ children?: ReactNode; }>, "children"> & Partial<Pick<...>> & Partial<...>'
```

**Comment by adidahiya** [comment]
The error message tells you which types are supported; you may use `undefined` instead of `null`. Is there a particular reason you need to use `null` for the start and end?

**Comment by elilambnz** [comment]
There's no particular reason I need to use `null`, this is simply a result of following the [documentation](https://blueprintjs.com/docs/#datetime/daterangepicker.date-ranges) of the DateRangePicker component. It's also used in the [code example](https://github.com/palantir/blueprint/blob/abcfe1d450be522c0a0d469ab751b99f5776a2e1/packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx#L79).

After a quick look at the source code, I initially thought that if I changed it to `undefined` that it would break the non-null checks. But of course `!= null` is still falsey for `undefined`. Thanks JavaScript!

Nonetheless, this still causes type errors if following exactly how the documentation does it.

**Comment by adidahiya** [comment]
Hmm sorry about that, it looks like the documentation at https://blueprintjs.com/docs/#datetime/daterangepicker.date-ranges is wrong... it should use `undefined` instead of `null`. Should be an easy PR to fix this!

As for the code example... `null` is actually used in the component state of `DateRangePickerExample`, but it is never sent to `DateRangePicker` itself since the example uses the component in an "uncontrolled" manner... yeah I understand that's a bit confusing, perhaps it's worth a small refactor.
