### ISSUE TITLE
Bug: Inconsistencies between dark mode and light mode in buttons/group

### ISSUE THREAD

**Issue by isakkeyten** [palantir/blueprint#3863]
#### Environment

- __Package version(s)__: 3.17.2
- __Browser and OS versions__: Chrome Version 78.0.3904.97 Windows 1709 16299.1451

[Code sandbox with problem](https://codesandbox.io/s/brave-chaplygin-n623d)

#### Steps to reproduce

1. Click Toggle button
2. See the buttongroup size grow 

#### Actual behavior

buttongroup size grow 
![image](https://user-images.githubusercontent.com/18152578/69340025-dd774480-0c66-11ea-9d47-49e2d1cc1547.png)
![image](https://user-images.githubusercontent.com/18152578/69340064-eec05100-0c66-11ea-80e6-9e98015b0895.png)

293px -> 297px
#### Expected behavior

no size difference, only colors

#### Possible solution

..

**Comment by adidahiya** [comment]
Yep, this is intentional. It's a compromise we had to accept in the design to get the exact colors we wanted with the buttons (borders, shadows, etc) in both color schemes. I don't have all the details of the design decision to share right now but this is something we iterated on for a long time before coming to the current design. It's unlikely to change.

**Comment by isakkeyten** [comment]
Ok thanks for clearing this out for me, and thank you for the quick reply.
