### ISSUE TITLE
Hiding and showing NumericInput with a min value causes the value to be rounded

### ISSUE THREAD

**Issue by yuchen-w** [palantir/blueprint#3889]
#### Environment

- __Package version(s)__: 3.20, 2.21, 3.22
- __Browser and OS versions__: Chrome 78

https://codesandbox.io/s/zen-khorana-1l2yb?fontsize=14&hidenavigation=1&theme=dark

#### Steps to reproduce

1. Press show hide
1. Type decimal number e.g. 10.5 into the numeric input box
1. Press show/hide to hide the number field
1. Press show/hide to show the number field

#### Actual behavior

When you restore a hidden number input box, the pre-populated number gets rounded to the nearest integer instead of staying as a decimal

#### Expected behavior

Expect value to not be decimal

Not sure what the solution might be, but I assume this isn't expected behaviour?

**Comment by igorlysak** [comment]
I have similar issue but it's not related to mount\unmount of `NumericInput` component. I think it's more about default decimal value and I think root cause of this issue is here https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/numericInput.tsx#L218
Second parameter of function `NumericInput.getSanitizedValue` is `stepMaxPrecision ` which is then pass to `toMaxPrecision` from `numericInputUtils.jsx`. But in line 218 there is a comment `delta` but delta is last parameter of `NumericInput.getSanitizedValue`. So I guess this code should be like this:
```ts
const stepMaxPrecision = NumericInput.getStepMaxPrecision(props);

const sanitizedValue =
    value !== NumericInput.VALUE_EMPTY
        ? NumericInput.getSanitizedValue(value, stepMaxPrecision, props.min, props.max, /* delta */ 0)
        : NumericInput.VALUE_EMPTY;
```
But again this is only an assumption

**Comment by adidahiya** [comment]
I think @igorlysak's fix is correct, but please let me know if it doesn't resolve your issue in the next release (this week)
