### ISSUE TITLE
Expose onChange function of NumericInput

### ISSUE THREAD

**Issue by strusoftsawen** [palantir/blueprint#3943]
`<NumericInput>` does not expose `onChange(e:ChangeEvent<HTMLInputElement>)` the same way as `<InputGroup>`. Instead, `onValueChange(n:number, s:string)` is exposed, with no information about which input is changing. This means that, annoyingly, one change handler is needed for each numeric input. Should be trivial to expose the change event of the `<input>` within.

**Comment by adidahiya** [comment]
> with no information about which input is changing

I'm a little confused by this; there's only one input in a `NumericInput` component.

Can you demonstrate your issue with a code sandbox? I don't see why you need the change event of the underlying `<input>`. Note that you can attach your own DOM event handler using the `inputRef` prop, but that's a little different from a React event handler like you suggested.

**Comment by strusoftsawen** [comment]
Thanks for the response. Here is a sandbox illustrating what I wish to achieve: https://codesandbox.io/s/react-typescript-xuly5

As you can see, one handleChange() method is used to deal with the onChange events of the various InputGroups. However, if I wish to use a NumericInput, there is no onChange event so I have to define one event handler for each of them. Even if there may be a way to work around this as you say, it would be neat if I could use the same logic as the InputGroups.

Let me know if I have misunderstood anything about the use of NumericInput.

**Comment by strusoftsawen** [comment]
@adidahiya Any update on this? My groups is looking to generate InputGroups and NumericInputs extensively based on data and share the same onChange event handler, but this is currently not possible.

**Comment by adidahiya** [comment]
@strusoftsawen I pushed a PR which should accomplish what you want, please check it out: https://github.com/palantir/blueprint/pull/3982

**Comment by strusoftsawen** [comment]
@adidahiya awesome, looks exactly like what I need. Apparently it wasn't included in the 3.24.0 package release, but I'm looking forward to using it once it's released.

**Comment by rkulinski** [comment]
@adidahiya I think this issue should be reopened. To be frank it seems insane that two very similar components `InputGroup` and `NumericInput` (naming is also wierd) have very different API. I think proper `onChange` method is required here.

**Comment by adidahiya** [comment]
@rkulinski I don't think you'll get very far in open source conversations with that kind of language in your comment. Most of the API decisions in Blueprint come with tradeoffs and the names have been chosen for a reason. If you have a concrete criticism of or proposal for what you'd like to see in the NumericInput component, please file a new issue and use the issue template.

**Comment by chetanism** [comment]
Hi, I recently ran into this issue and took some time to get to the problem and figure out a workaround. I am leaving it here just in case someone else stumbles through same problem. 

I am using react-hook-form along with blueprint-js. I added a `NumericInput` in a simple form and soon ran into problems. The workaround was to use the `useController` API provided by react-hook-form to translate the `onValueChange` event to `onChange`. Hope this helps anyone running into this issue.

That said, I would second the opinion to expose the `onChange` event as well. The underlying inputs i.e. a text input and number input in raw HTML behave quite similarly and I suppose the general expectation of any developer or library (such as react-hook-form) authors would be same. 

I suppose the main reason to not expose the onChange event might be because of the +/- buttons that may change the input value without the underlying input triggering any event, nonetheless I just want to raise my hand in support of having an `onChange` event in future if possible.

Thx.
