### ISSUE TITLE
Blueprint Table doesn't respond to column size changes immediately in 3.8.3

### ISSUE THREAD

**Issue by acolombi** [palantir/blueprint#3948]
#### Environment

- Blueprint Table 3.8.3
- Chrome 79, macOS Catalina

#### Issue Summary

When we upgraded to Blueprint Table 3.8.3 we noticed our app's reaction to user column resizing isn't happening until after the user clicks again. Here's GIFs of 3.7.1 and 3.8.3

#### 3.7.1

![2020-01-29 18 13 44](https://user-images.githubusercontent.com/707331/73414392-8a9fb600-42c3-11ea-86ab-fcf69f7ea308.gif)

#### 3.8.3

![2020-01-29 18 15 18](https://user-images.githubusercontent.com/707331/73414396-8ffd0080-42c3-11ea-9b7d-fca757a57836.gif)

**Comment by theaeolianmachine** [comment]
In addition to this, we're also seeing where it doesn't render most of the rows in the table until after a long delay, making it seem like there are only a few rows. I'm pretty sure it also requires a click or some form of interaction in order to get them to load (this was recorded by another teammate).

![table_issue](https://user-images.githubusercontent.com/440353/73478324-bca82b00-434a-11ea-84a6-fc3dbbdc9ca8.gif)

**Comment by adidahiya** [comment]
I think both issues are due to lingering problems we still have with the table after refactoring React lifecycle methods in 3.8.0... for now I would recommend downgrading to 3.7 until these are resolved https://github.com/palantir/blueprint/milestone/41

**Comment by rogozind** [comment]
any plans to fix this? This issue prevents a lot of people from upgrading to table 3.8.

**Comment by adidahiya** [comment]
fixed in table v4.0.0-rc.1
