### ISSUE TITLE
Upgrade to Popper.js v2.0

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#4023]
[v2 docs](https://popper.js.org/docs/v2/)

**Comment by LoiKos** [comment]
You may consider using [React-Popper v2](https://popper.js.org/react-popper/) i think it would be easier for you

**Comment by adidahiya** [comment]
We're [already using](https://github.com/palantir/blueprint/blob/f896892084105939d5ee4af6fd1c3c4e27608625/packages/core/src/components/popover/popover.tsx#L21) react-popper.

**Comment by alex-kinokon** [comment]
Will this be in 4.0?

**Comment by adidahiya** [comment]
@proteriax yes, likely, but I don't have a concrete timeline for 4.0 yet

**Comment by justinbhopper** [comment]
@adidahiya ~Are there plans to transition @blueprintjs/core and @blueprintjs/select to use Popover.js v2.0?  I would have thought the v4.0 milestone would be a good opportunity to make the switch, since it would undoubtedly be a breaking change to the API.~

Ignore this comment.  I see this is exactly what has been done on the v4 branch.
