### ISSUE TITLE
Tag element has no Y padding when "large" and "multiline"

### ISSUE THREAD

**Issue by albemala** [palantir/blueprint#4037]
#### Environment

- __Package version(s)__: 3.24.0
- __Browser and OS versions__: Firefox 75 / macOS 10.14

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/festive-wing-j7s4e

#### Steps to reproduce

1. Create a Tag element
2. Set it to be "large" and "multiline"
3. Set a long text as its content

#### Actual behavior

The Tag element has no top and bottom padding

#### Expected behavior

The Tag element should have top and bottom margins, with same size as the left and right ones.

**Comment by Eusbolh** [comment]
I believe this problem is directly related to `large` prop rather than `multiline`. Originally, `bp3-large` class has `padding: 0 $tag-padding-large;` property, and `bp3-tag` class has `min-height: $tag-height;` property. When the tag content is not multiline, there are 5px gaps on top and bottom due to that `min-height` property. This is why it seems like that the problem occurs only on multiline + large.

This can be fixed by adding top and bottom padding properties to `bp3-large` class. I added a PR regarding this issue by following the current ratio between horizontal and vertical padding for single line `large` tags.
