### ISSUE TITLE
TypeSript errors with any component in yarn berry workspace configuration

### ISSUE THREAD

**Issue by w1th0utnam3** [palantir/blueprint#4056]
I want to use Blueprint in a TypeScript React app inside of a yarn berry workspace. unfortunately this doesn't seem to be possible at the moment as it results in TypeScript errors like

```
TypeScript error in U:/Temp/test/packages/app/src/index.tsx(11,5):
JSX element type 'Button' is not a constructor function for JSX elements.
  Type 'Button' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, refs  TS2605

     9 |   <React.StrictMode>
    10 |     <App />
  > 11 |     <Button text="Button"/>
       |     ^
    12 |   </React.StrictMode>,
    13 |   document.getElementById('root')
    14 | );
```

I guess `tsc` does not find the type definitions of Blueprint? Without a workspace, everything works fine with the same versions of involved packages.

#### Environment

- __Package version(s)__: @blueprintjs/core@3.25.0, yarn@2.0.0-rc.27
- __Browser and OS versions__: Windows 10

**Repository with minimal repro: https://github.com/w1th0utnam3/bp_workspace_bug**

#### Steps to reproduce

1. create `package.json` with workspace setup
```
{
    "private": true,
    "workspaces": [
        "packages/*"
    ]
}
```
2. `mkdir packages`
3. `cd packages`
4. `yarn dlx create-react-app app --template typescript`
5. Remove `node_modules`, `yarn.lock` etc. 
6. (this pure react app works after applying [this fix](https://github.com/facebook/create-react-app/issues/8808))
7. Add blueprintjs to the app: `yarn workspace app add @blueprintjs/core`, `yarn install`
8. Use a blueprint component in `index.tsx` e.g.
```ts
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import { Button } from "@blueprintjs/core";
import * as serviceWorker from './serviceWorker';

ReactDOM.render(
  <React.StrictMode>
    <App />
    <Button text="Button"/>
  </React.StrictMode>,
  document.getElementById('root')
);
```
9. Run `yarn workspace app run start`

#### Actual behavior

```
TypeScript error in U:/Temp/test/packages/app/src/index.tsx(11,5):
JSX element type 'Button' is not a constructor function for JSX elements.
  Type 'Button' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, refs  TS2605

     9 |   <React.StrictMode>
    10 |     <App />
  > 11 |     <Button text="Button"/>
       |     ^
    12 |   </React.StrictMode>,
    13 |   document.getElementById('root')
    14 | );
```

#### Expected behavior

App compiles & runs.

**Comment by justinbhopper** [comment]
I just pulled your repro and it works just fine.  

```
root> yarn install
root> cd packages/app
root/packages/app> npm start
```

![image](https://user-images.githubusercontent.com/29075873/79028279-fec4c880-7b54-11ea-98bd-1a1e420a65c6.png)

**Comment by w1th0utnam3** [comment]
Interesting. Are you sure you used a yarn 2.0 release? I'll try it reproduce it on other machines that I don't usually use for development.

**Comment by w1th0utnam3** [comment]
I confirm that this is related to the yarn version. I switched to my Linux machine with Node 13.9, and yarn 1.22.4 installed with `apt`. I updated my repro repository to locally use yarn berry using `yarn set version berry` (also commited this). Now I get the error shown in the issue. When I clone the repository again, go to the previous commit, so that it uses the global yarn 1.22.4 installation, I don't get the error.

I don't get the error with yarn berry, when I the project is not in a workspace. So I gess it's related to changes in yarn on how it handles workspaces.

**Comment by justinbhopper** [comment]
@w1th0utnam3 Do you get the same issue with another typescript-based library, such as Material-UI?  The reason I ask is because Blueprint's typescript definitions and module system are pretty much identical to just about every other react library out there.  I myself use it in a Lerna/Yarn monorepo (with workspaces) without issue.  Monorepos do sometimes take some effort to setup correctly, especially with CRA, so I'm curious if this is really just a symptom of your workspace setup.

**Comment by w1th0utnam3** [comment]
Thanks, I will try it out if I get the same problems with Material-UI. However it still annoying that it works out of the box with Yarn 1.x and not with 2.x. 
To be fair, I'm totally new to Javascript development (mainly want to use it to build a UI for a Rust backend) and it's hard to troubleshoot problems that occur only because of a specific combination of components in the toolchain (Yarn 2 + TypeScript + Create React App + monorepo...)

**Comment by justinbhopper** [comment]
@w1th0utnam3 One thing I would suggest is starting out just with CRA without the monorepo, if that is an option for you.  CRA is wonderful mainly because it helps developers avoid the mess of setting up a bundler/build process (webpack, rollup, etc).  It supports TypeScript natively, and adds a ton of cool features like hot-reloading.  

In order to get a monorepo setup, you need to have a fair bit of knowledge of how to setup a build process for each of your packages independently.  This is usually a huge experience wall.  It can be extremely frustrating.  

My team spent a year just developing our packages in separate git repos (each with its own separate build) until we were ready to take on the monorepo challenge.  By the time we were ready, we at least had our regular builds sorted out and understood a bit more about webpack.

**Comment by w1th0utnam3** [comment]
Ok, thanks for the insight. I'll first try to develop the packages separately like you recommended. This way I don't have an additional layer obscuring problems with my project.

With Material-UI I get different errors in the same setup (again working with yarn 1.x). So, if you don't think Blueprint should work out of the box in the setup I described, feel free to close the issue.

**Comment by adidahiya** [comment]
This sounds like a yarn 2.x bug, have you raised the issue with them at all? As @justinbhopper mentioned, Blueprint publishes with a fairly standard package structure for TypeScript projects.

**Comment by Poolshark** [comment]
If this is still an issue - I had a similar problem with `react-rnd` and I could fix it with adding

```yaml
packageExtensions:
  'react-rnd@*':
    peerDependencies:
      'react': '*'
```

to your `.yarnrc.yml` file. The reason probably is that `blueberry` is lacking a peer dependency and the [import of it fails.](https://github.com/bokuweb/react-rnd/blob/042eb3d221100b650dd1fb605ffa22d6d72fdd58/src/index.tsx#L1).

The reason it works without workspaces is due to https://yarnpkg.com/features/pnp/#fallback-mode
