### ISSUE TITLE
Usage of deprecated UIEvent.which field

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#4165]
We probably use [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) instead. The relevant code is 3 years old, it makes assumptions about this field not being reliable in all browsers in `onKeyDown` which should be revisited.

**Comment by adidahiya** [comment]
Note that [`keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and [`charChode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode) are also deprecated, so we should not use those. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46574

**Comment by rubenlg** [comment]
Also `which` is being misused by assuming that the key codes always map to the same printable character in the `KeyCodes` array of `packages/core/src/components/hotkeys/hotkeyParser.ts`. That's not true, it depends on the keyboard layout. The same key prints different characters depending on the layout of the keyboard being used by the user.

This makes hotkey support in blueprint partially broken outside of the US, because all the keys that don't hold a fixed position in the keyboard across layouts are misidentified (especially those that require pressing `Shift` in some layouts but not others).

See #4849 for a particularly troubling example, in which the help dialog of the hotkey library is broken in many keyboards across the world :(

**Comment by dlech** [comment]
This also breaks testing with https://testing-library.com/docs/ecosystem-user-event#keyboardtext-options since it doesn't set `which`.

**Comment by adidahiya** [comment]
Fixed in v5 branch by #6106
