### ISSUE TITLE
DatePicker: Selecting "Year" then "Month" on iOS causes component to throw error

### ISSUE THREAD

**Issue by flatlevel** [palantir/blueprint#4178]
#### Environment

- __Package version(s)__: verified on both 3.22.2 and 3.28.2
- __Operating System__: iOS 13.5
- __Browser name and version__: Safari Mobile 13.1

#### Code Sandbox

Can be reproduced on Blueprint's site: https://blueprintjs.com/docs/#datetime/datepicker 

![bug](https://user-images.githubusercontent.com/2308582/84641823-36be0280-af2e-11ea-9726-2ce0d94b2ee3.gif)

#### Steps to reproduce

1. Add blueprint's date picker
2. Open date picker on iOS safari mobile 
3. Select year "iOS scroll wheel" but do not choose a year
4. Select month
5. White screen, JS error

#### Actual behavior

Screen turns white, error

```
TypeError: undefined is not an object (evaluating 'd.length')
```

#### Expected behavior

I will see the month iOS scroll wheel and choose the appropriate month.

#### Possible solution

I believe this issue is related: https://github.com/palantir/blueprint/issues/3603

**Comment by adidahiya** [comment]
Blueprint is not tested for mobile usage, it is designed for desktop applications, so this is low priority for the project. Open to bugfix PRs, though.

**Comment by jez321** [comment]
I've had a look into this and found a couple of things
- It seems that safari on iOS fires onChange events for select boxes when they are focused and blurred, even if the value doesn't change
 -> Codesandbox here: https://codesandbox.io/s/hidden-hooks-y5k00?file=/src/App.js
      Visit in iOS safari and tap each select box alternately, notice the console messages.
      You'll also notice the value of the select box on screen changes when you focus it. On blur it returns to the correct value if you don't select a new one so it's not a huge deal and I don't think we can do much about it anyway but wait for a fix to safari/iOS.
       
- This itself shouldn't result in a crash but the value for e.target safari passes with these change events in some cases (the case above) is an empty string, which results in an Invalid date and crash.

- I'm not sure why we get an empty string sometimes as this doesn't happen in the codesandbox, perhaps someone with more knowledge of DatePicker can shed some light on it (maybe due to some of the custom focus/blur handling?)

- A simple way to stop the crashes at least would be to just ignore the change event if the value passed is an invalid date or empty string. If this seems acceptable I can make a PR for it.

**Comment by adidahiya** [comment]
> A simple way to stop the crashes at least would be to just ignore the change event if the value passed is an invalid date or empty string. If this seems acceptable I can make a PR for it.

Sure, I would accept a PR for this. Make sure to include a code comment about how this change is iOS-specific
