### ISSUE TITLE
DatePicker does not passthrough required attribute to input element

### ISSUE THREAD

**Issue by FallingSnow** [palantir/blueprint#4181]
#### Environment

- __Package version(s)__: @blueprintjs/core@^3.28.1

#### Steps to reproduce

1. Add `required={true}` prop to `DatePicker`.
1. Submit form without filling out datepicker element.
1. Form is submitted.

#### Actual behavior

Form is submitted without required field. The `required` attribute is not added to the input element.

#### Expected behavior

An error message is displayed to enter a value into the required field.

#### Possible solution

Pass through `required` prop to input element. 

#### Notes

This also affects `Suggest`.

**Comment by adidahiya** [comment]
Do you mean `DateInput`? From an API perspective, I feel like `<DateInput required={true}>` would have a more standardized expectation for that kind of functionality inside a form. If that is the case, you can use `inputProps={{ required: true }}` to accomplish this. Same goes for the `Suggest` component. We added that `inputProps` prop to the API for this purpose, because we did not want to predict / prescribe every possible variation of the input API.

If your request is actually for `DatePicker` to add a `required` prop and the associated visual feedback, then that is a larger feature request, and would require a design proposal.

**Comment by FallingSnow** [comment]
Sorry yes, I did mean `DateInput`. I was looking at the documentation for `DatePicker` when looking for something like `inputProps`. I anticipate this will work as expected. I'll update this issue if not.

Thank you @adidahiya!
