### ISSUE TITLE
Select search input not focusing on popover opening

### ISSUE THREAD

**Issue by moorerc** [palantir/blueprint#4184]
#### Environment

I'm noticing the discrepancy when switching from @blueprintjs/select version 3.12.3 (expected behavior) and version 3.13.0 (buggy behavior)

#### Code Sandbox

https://codesandbox.io/s/blueprint-sandbox-zzxdw?file=/src/index.tsx

#### Steps to reproduce

1.  Open the select component by clicking on the button 

#### Actual behavior

In version 3.13.0 and higher, the search input in the popover does not gain focus on initial opening of the popover (requiring a separate click).

#### Expected behavior

In version 3.12.3 and prior, the search input would automatically gain focus on initial open.

#### Possible solution

no ideas yet

**Comment by adidahiya** [comment]
Sounds like an issue caused by this commit diff: https://github.com/palantir/blueprint/commit/263d4df334b3539ad58f042d0520e61dbbe8425b#diff-62d2c728ba1cf17d4cd33a5f99155b17

There were some other tweaks and fixes to the component released later in the 3.13.x range, though, and it looks like upgrading to latest 3.13.3 fixes the problem in your sandbox. Can you verify?

**Comment by moorerc** [comment]
yup, verified this is fixed in the latest version. thanks!
