### ISSUE TITLE
Table enableFocusedCell causes text to be written in a previous unfocused cell (regression between 3.8.0 and 3.8.1)

### ISSUE THREAD

**Issue by kezakez** [palantir/blueprint#4311]
#### Environment

- __Package version(s)__: 3.8.1 and above
- __Operating System__: Mac
- __Browser name and version__: Chrome

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-forked-gen08?file=/src/index.tsx

#### Steps to reproduce

1. in the first cell type 6
1. press enter
1. press 7
1. press enter

#### Actual behavior

7 will override 6 but focus will be in row 3

#### Expected behavior

in version 3.8.0 "6" will be input into the first row and 7 will be input into the second row.

#### Possible solution

Check for a regression between 3.8.0 and 3.8.1

**Comment by adidahiya** [comment]
Was this working before 3.8.0? https://github.com/palantir/blueprint/commit/69882d36d1f1c8a0eb83859d714fc80a5ed98a53 is the only change between those two versions, it is a commit which tried to _fix_ some regressions in table lifecycle methods introduced in table v3.8.0.

Note that there are still lingering issues with table lifecycle methods in the 3.8.x version range: https://github.com/palantir/blueprint/milestone/41. For now the recommendation is to downgrade to 3.7.x

**Comment by kezakez** [comment]
Yes, it was working before 3.8.0.

To test I went into the codesandbox https://codesandbox.io/s/blueprint-sandbox-forked-gen08?file=/src/index.tsx and changed the version and retested the steps above.

The result:
3.8.1 fails
3.8.0 works ok
3.7.1 works ok
3.4.0 works ok
3.2.0 works ok
3.1.1 the code sandbox doesn't compile

**Comment by adidahiya** [comment]
Forked and updated your sandbox to table v4.0.0-rc.2 and `<Table2>`... looks like the behavior is at least a little better since "6" is not overwritten, but the second cell never goes into editing state to accept the "7", it's just blank:

![2022-03-16 11 35 51](https://user-images.githubusercontent.com/723999/158628852-ea9cafc9-3556-4848-878a-f7cc9658fa55.gif)

https://codesandbox.io/s/blueprint-sandbox-forked-dlbgl1?file=/src/index.tsx

this seems like a different issue, though... if it's still present after upgrading to v4.0 stable (releasing soon), I'd be happy to take another look at this issue or a new one.
