### ISSUE TITLE
Remove default icon color

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#437]
Icons have a color specified in every context. It has caused some trouble in a few places, for instance when displaying text with a custom color (e.g. green or red) and adding an icon to it, the icon would remain grey.

Note that this change would make icons slightly darker since they'd follow the default body text color.

@pkwi what do you think about this change?

**Comment by cmslewis** [comment]
Yessss. This change bit me (minorly) in a past project.

**Comment by pkwi** [comment]
Currently, icons are using 'muted' text colour. I'm not a fan of making them the same colour as the default text. Because of solid style, in some cases, they would appear darker and more dominant than the text next to it. Using a lighter colour help to tone down the contrast.
We could remove the default colour and strongly recommend using a muted text class for icons.
