### ISSUE TITLE
Range Slider inside Popover flows out of component

### ISSUE THREAD

**Issue by arunmmanoharan** [palantir/blueprint#4404]
#### Environment

- __Package version(s)__: 3.35.0
- __Operating System__: Windows 10
- __Browser name and version__: Chromw

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/vibrant-hugle-s93zw?file=/src/App.js

#### Steps to reproduce

1. Click the button

#### Actual behavior

The slider displays but the control buttons are out of bounds of the  Popover

#### Expected behavior

The whole slider including the drag handles should be inside the popover

**Comment by adidahiya** [comment]
Popover doesn't know about its contents, and sometimes those contents can use layouts which spill out of their bounding boxes, like Slider in this case. Rather than adding complex implementation logic to Popover to have it detect its contents, you're better off simply adding padding to this popover's contents. Select this _specific_ popover by adding `popoverClassName="my-popover"`:

```
.my-popover .bp3-popover-content {
  padding: 10px 20px;
}
```

<img width="231" alt="image" src="https://user-images.githubusercontent.com/723999/98749883-a4117a80-238a-11eb-9ded-b14d7a298d29.png">
