### ISSUE TITLE
Range Slider Handles inside a popover not fixed properly onOpen

### ISSUE THREAD

**Issue by arunmmanoharan** [palantir/blueprint#4417]
#### Environment

- __Package version(s)__: 3.35.0
- __Operating System__: Windows 10
- __Browser name and version__:  Chrome

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/vibrant-hugle-s93zw?file=/src/App.js

#### Steps to reproduce

1. Open the popover by clicking the button
1. 
1. 

#### Actual behavior

![image](https://user-images.githubusercontent.com/4927454/99009903-dd76f100-2516-11eb-916f-9fd9904513e3.png)

#### Expected behavior

the right slider handle should be fixed to the slider bar. If we move it around, it works properly. Issue just on first load.

#### Possible solution

`.rangeSliderInsidePopover > span.bp3-slider-handle.bp3-end {
  left: calc(100% - 8px) !important;
}`

Make left: calc(100% - 8px) from .bp3-slider-handle.bp3-end seems to fix this. But doesnt make the slider moveable

**Comment by adidahiya** [comment]
I think this is a measurement issue that occurs upon first mount of the component, similar to https://github.com/palantir/blueprint/issues/4109... it needs further investigation

**Comment by lwouis** [comment]
I can confirm I'm running into the same issue.

I think the issue is at this line: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/slider/handle.tsx#L158

This function returns 0 somehow: https://github.com/palantir/blueprint/blob/241b20d5b45a62ef90c91d795f78d429adbda47f/packages/core/src/components/slider/handle.tsx#L234

Maybe an easy fix is to replace the default value from 0 to 8px? Maybe it conflicts when use-case without slider handles though, not sure. It should be an easy fix though I imagine.

**Comment by lwouis** [comment]
Hi everyone!

Can we get a review from a maintainer? I'd like to know if there is a chance this issue gets looked at, or if we should fork and make our fix here.

Thanks!

**Comment by adidahiya** [comment]
@lwouis maintainer here, acknowledging that it's a bug. This is a lower priority issue compared to some other things I'm working on at the moment, but I would accept a bugfix PR :)

**Comment by adidahiya** [comment]
I ported the code sandbox to Blueprint v5.x, can confirm it's still an issue: https://codesandbox.io/p/sandbox/blueprint-rangeslider-bug-repro-4417-crx4dl
