### ISSUE TITLE
NumericInput crashes docs app when changing locale

### ISSUE THREAD

**Issue by jlismore** [palantir/blueprint#4424]
it's possible to cause the [docs app](https://blueprintjs.com/docs/#core/components/numeric-input) to crash with `Uncaught RangeError: invalid language tag: ""`
Repro steps:

- Enter 0.5 in numeric input
- Change locale to anything else
- Change locale back to Default
- Crash

**Comment by lwouis** [comment]
I reproduce this. I also observe that whatever locale I select (when it doesn't crash), the UI is not affected.

![image](https://user-images.githubusercontent.com/106195/115811471-b956fe80-a42a-11eb-8ccf-ef08a8df93ca.png)

Here for instance, I would expect to see `100,001` instead of `100001`, since the locale is set to English. All values show the same number.

Copy-pasting `100,000` in the box works correctly in the French locale where it becomes `100`, and the English locale where it become `100000`.

However, the number on display is not formatted

**Comment by riwu** [comment]
@adidahiya it seems like the bug reported by @lwouis hasn't been fixed?
