### ISSUE TITLE
[Dateinput] Month/Year selects don't work when in Overlay

### ISSUE THREAD

**Issue by PLSFIX** [palantir/blueprint#4439]
#### Environment

- __Package version(s)__: 3.31.0 core, 3.20 datetime, 3.13.7 select
- __Operating System__: Windows
- __Browser name and version__: Chrome 87.0.4280.66

#### Code Sandbox

[Link](https://codesandbox.io/s/dateinput-bug-2g53q?file=/src/DatetimeExample.tsx)

#### Steps to reproduce

1. Click on "Without Overlay" Dateinput -> Month and Day selects work
2. Click on any "Open" button to toggle respective section's overlay -> check those selects again

#### Actual behavior

Selects don't open, no ability to select a value

#### Expected behavior

Selects open, ability to select a Month/Year value

#### Possible solution

Possibly, a bug with events handling/propagation. `usePortal` option has no effect as well.

**Comment by adidahiya** [comment]
The blueprint package versions in your sandbox are incompatible. You used the latest version of datetime (3.20), which requires a newer version of core.

I tried your code with the latest versions of the blueprint packages and the bug is no longer present: https://codesandbox.io/s/blueprint-sandbox-forked-0rpku?file=/src/index.tsx
