### ISSUE TITLE
HTML Select icon missing

### ISSUE THREAD

**Issue by mfonsatti** [palantir/blueprint#4466]
#### Environment

- __Package version(s)__: Core 3.36.0
- __Operating System__: BigSur
- __Browser name and version__: Chrome Version 87.0.4280.88

#### Actual behavior

Using the HTML Select with className={``` `${Classes.HTML_SELECT` ```} the icon is missing

#### Expected behavior

Using Classes.HTML_SELECT the icon should appear

#### Possible solution

Add the deprecated class Classes.SELECT --> className={`${Classes.SELECT} ${Classes.HTML_SELECT}`}

**Comment by adidahiya** [comment]
Can you please demonstrate the issue with a code sandbox? It's linked from the issue template and makes debugging a lot faster.

**Comment by adidahiya** [comment]
I can repro this bug. It looks like the `.bp3-html-select` CSS API never worked correctly with its icon, as it was never rendered in the docs. If I use this class I can see the icon goes missing:

![image](https://user-images.githubusercontent.com/723999/125141466-1d609900-e0e3-11eb-96ba-a6d3e5ea0b0e.png)

In general I encourage everyone to move towards the React component API rather than this CSS API (`<HTMLSelect>`). However, I can fix the example for the CSS API -- you'll need to add markup for the icon yourself.
