### ISSUE TITLE
NumericInput up/down keypress/button click breaks on stepsize smaller than 0.001

### ISSUE THREAD

**Issue by cybae0804** [palantir/blueprint#4497]
#### Environment

- __Package version(s)__: @blueprintjs/core: "3.38.1"
- __Operating System__: Ubuntu 20.04 LTS
- __Browser name and version__: Chrome 87.0.4280.141 

#### Code Sandbox

https://codesandbox.io/s/blueprint-sandbox-forked-98i26

#### Steps to reproduce

Provide a stepSize and minorStepSize such as 0.0001, and try to modify the input using the up/down button or the keypress. It will lock up and won't fire onValueChange correctly.

#### Actual behavior

Freezes

#### Expected behavior

Increments/Decrements value correctly

#### Possible solution

Tried to investigate a bit but couldn't figure it out. The count decimals util function seems to be working correctly however.

**Comment by tonooo71** [comment]
I'm using the v4.0.0-alpha version and I also encountered the same bug.

I think the cause of this bug is **num.toLocaleString(locale)** in the **toLocaleString** function of **numericInputUtils.ts**.
The numeric string obtained by **num.toLocaleString(locale)** is truncated to the fourth decimal place.
[Number.prototype.toLocaleString(): MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)

So, for example, by using **num.toLocaleString(locale, { maximumSignificantDigits: 10 })**, I think the number up to the tenth decimal place will work on **NumericInput**.

**Comment by SquareByte** [comment]
Issue still exists in v5.0.0

**Comment by Rafael-Martins** [comment]
> I'm using the v4.0.0-alpha version and I also encountered the same bug.
> 
> I think the cause of this bug is **num.toLocaleString(locale)** in the **toLocaleString** function of **numericInputUtils.ts**. The numeric string obtained by **num.toLocaleString(locale)** is truncated to the fourth decimal place. [Number.prototype.toLocaleString(): MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)
> 
> So, for example, by using **num.toLocaleString(locale, { maximumSignificantDigits: 10 })**, I think the number up to the tenth decimal place will work on **NumericInput**.

Opened a pr based on this solution, but I'm not assured why this is happening :thinking: I will do more investigation tomorrow, but, the solution is working and I wrote some tests to cover it

**Comment by TheRayTracer** [comment]
Does this also resolve?: https://github.com/palantir/blueprint/issues/4045
