### ISSUE TITLE
Seems 'fill' property not work in InputGroup component

### ISSUE THREAD

**Issue by wisdomG** [palantir/blueprint#4514]
#### Environment

- __Package version(s)__: 3.9.0
- __Operating System__: windows 10
- __Browser name and version__: Chrome 88

#### Code Sandbox

The minimal repro: https://codesandbox.io/s/blueprint-sandbox-forked-5nd5u?file=/src/index.tsx

#### Actual behavior

Two InputGroup has the same width

#### Expected behavior

If I don't set `fill` to true, the InputGroup should have a default width .
If I set `fill` to true, the InputGroup will fill the container.

#### BTW

There is another minimal repro: https://codesandbox.io/s/blueprint-sandbox-forked-hfpff?file=/src/index.tsx

I use the InputGroup inside the FormGroup and set the inline property.

Then I set `fill` to true, but the InputGroup does not fill the left space.

**Comment by adidahiya** [comment]
These both seem like sort of contrived examples. In the first one I'm not sure what you expect; the InputGroup is `display: block` so that is expected behavior. There are lots of custom layout styles you could set on these components, and you are usually expected to use flex layout on top of what Blueprint provides out of the box. Similar for your second sandbox example. A `<FormGroup inline>` will not expand to fill space, no matter what its child components do.
