### ISSUE TITLE
ContextMenu2 with Tree - wrong open position

### ISSUE THREAD

**Issue by davidskuza** [palantir/blueprint#4537]
#### Environment

- __Package version(s)__: @blueprintjs/popover2 0.3.0 (other versions below in codesandbox)
- __Operating System__: Windows 10
- __Browser name and version__: Chrome 88.0.4324.182

#### Code Sandbox

Link to a minimal repro: [https://codesandbox.io/s/blueprint-sandbox-forked-l8i73?file=/src/TreeView.tsx](https://codesandbox.io/s/blueprint-sandbox-forked-l8i73?file=/src/TreeView.tsx)

#### Steps to reproduce

1. Make ContextMenu2 on label in Tree, in child nodes
2. Open ContextMenu2

#### Actual behavior

ContextMenu2 opens in wrong place. Seems to go deeper and deeper with nested Tree items. Root level is correct.

#### Expected behavior

ContextMenu2 to open at mouse position.

#### Possible solution

Maybe I am using this wrong because I see there is an contextMenu event on Tree but idk how I could connect it to ContextMenu2.

**Comment by adidahiya** [comment]
Thanks for the bug report.

First off, since you're using the popover2 package, you have to make sure to import its CSS in your app / codesandbox:

```
import "@blueprintjs/popover2/lib/css/blueprint-popover2.css";
```

After doing that, I can still repro your bug, though, so it's definitely something I will look into. Here's the menu at the tree root:

![image](https://user-images.githubusercontent.com/723999/108724800-bce60c00-74f3-11eb-856d-22a18743529e.png)

and here's the menu 3 levels deep in the tree:

![image](https://user-images.githubusercontent.com/723999/108724868-ca9b9180-74f3-11eb-9db0-9ee48844b20b.png)

looks like there may be some issue with measuring the ContextMenu2 target element position when CSS transforms are used...
