### ISSUE TITLE
[select] Select component does not support controlled `selectedItem`

### ISSUE THREAD

**Issue by bocong** [palantir/blueprint#4561]
#### Environment

- __Package version(s)__: @blueprintjs/select@3.15.5

#### Question

I'm using the Select component, and noticed it does not support controlling the selected item, while Suggest seems to (https://github.com/palantir/blueprint/blob/develop/packages/select/src/components/select/suggest.tsx#L77)

Wondering if this is intentional due to some limitations, and if not, are there plans to support controlling selected item in Select?

**Comment by adidahiya** [comment]
What do you mean by "selected item"? You get to render the `<Select>` children, so you have control over what is displayed as the "selected item". You don't need a new prop to do that: https://github.com/palantir/blueprint/blob/0750f4d5fd9775bbada07feb588abf9666d55ad6/packages/docs-app/src/examples/select-examples/selectExample.tsx#L120

`<Suggest>` is different because the component renders the text input for you.

**Comment by bocong** [comment]
Ah, that makes more sense -- sorry, must have missed that about `<Select>`. Thanks!
