### ISSUE TITLE
Popover2: menuItem does not execute onClick() when menuItem parent was clicked

### ISSUE THREAD

**Issue by pcclickbit** [palantir/blueprint#4600]
#### Environment

- __Package version(s)__: @blueprintjs/popover2 0.3.0 (other versions below in codesandbox)
- __Operating System__: Windows 10
- __Browser name and version__: Chrome 89.0.4389.90 (Official Build) (64-bit)

#### Code Sandbox

https://codesandbox.io/s/blueprint-popover2-v7c57?file=/src/App.tsx

#### Steps to reproduce

1. Click menu button "Popover2"
2. Click menu item "Kiosk"
3. Click menu item "Report"

#### Actual behavior

The onClick in menu item "Report"  was not executed

#### Expected behavior

The onClick in menu item "Report"  should have executed and shown the Alert "clicked".
Like in the "old" Popover.
Added another menu "Popover" that uses the same menu, and the Popover from @blueprintjs/core

**Comment by adidahiya** [comment]
First, note that you need to include the popover2 CSS import when you use Popover2:

```
import "@blueprintjs/popover2/lib/css/blueprint-popover2.css";
```

There is no menu item labeled "Report" in your sandbox. I assume you mean this submenu item:

![image](https://user-images.githubusercontent.com/723999/112070124-76f88400-8b43-11eb-993a-b5182dad4b68.png)

I can repro the bug you're talking about, I will try to fix it when I merge Popover2 into core on the `v4` branch.

**Comment by adidahiya** [comment]
Also, this seems related to #3095

**Comment by adidahiya** [comment]
Tried to debug this a bit and it looks like it's still a problem in v4.0.0-alpha.0, where MenuItem submenus use the new Popover implementation: https://codesandbox.io/s/blueprint-sandbox-forked-0pckz?file=/src/index.tsx

Not exactly sure what the problem is but the [popover click handler](https://github.com/palantir/blueprint/blob/c91f71b6ea62d165a597854dca6ab06dfb352422/packages/popover2/src/popover2.tsx#L562) is not getting invoked when clicking the submenu item which is... weird. This needs further investigation.

**Comment by JoseLion** [comment]
@adidahiya I think the reason why [this popover click handler](https://github.com/palantir/blueprint/blob/c91f71b6ea62d165a597854dca6ab06dfb352422/packages/popover2/src/popover2.tsx#L562) is not getting invoked is because the submenus are not using `Popover2`, they still use the deprecated Popover😅 
https://github.com/palantir/blueprint/blob/81147fc2b5edb3a1ed36fe959c03b568c7461b68/packages/core/src/components/menu/menuItem.tsx#L262-L278

I noticed this because I ran into a different issue with submenus when testing with `@testing-library/react` and `@testing-library/user-event`.

The problem is that the deprecated Popover creates a `div` with the class `.bp4-transition-container`, which starts with the style `pointer-events: none`. This style gets removed (somehow) almost immediately, but the test runs faster, and `userEvent.click(..)` finds the `pointer-event: none` and assumes the element is not-clickable. The problem does not happen with Popover2 because it uses the class `bp4-popover2-transition-container` for that same `div` element.

It looks like the inconsistent behaviors we're seeing are because of using Popover2 for the base menu and the deprecated Popover for the submenus. Is migrating the submenus to Popover2 a possibility?

Cheers!

**Comment by adidahiya** [comment]
> Is migrating the submenus to Popover2 a possibility

Yes, this is the plan, we will provide a MenuItem2 which uses Popover2 instead of Popover. When I wrote my previous comment in this issue thread, we were still planning to include the Popover2 breaking changes in v4.0. Since then, those changes were pushed back to v5.0 (see https://github.com/palantir/blueprint/wiki/Blueprint-v4.0-&-v5.0-semantic-swap). At the moment MenuItem still uses the deprecated Popover component.

**Comment by JoseLion** [comment]
I see, so right now the only option we have is to wait for v5, right?

The thing is that I was able to track down the issue regarding `pointer-events: none`. It seems that `react-popper` includes `pointer-events: none` on its initial style props in `v1.3.11`, the version used by the deprecated Popover. Popover2 uses `react-popper@2.3.0`, which removed `pointer-events` from the initial styles.

This issue means that as long as anything uses the deprecated Popover, any tests using `@testing-library/user-event@14.x.x` will fail because of the `pointer-event` check 😞

**Comment by adidahiya** [comment]
We'll have MenuItem2 available in v4.x before v5.0 is released. You can expect MenuItem2 in the next few weeks.

**Comment by JoseLion** [comment]
That's awesome news, thanks! I'll be looking forward to it 🎉🙂

**Comment by cdomigan** [comment]
@JoseLion I am encountering the same issue using @testing-library/user-event. Did you find any workarounds for this issue?

EDIT: https://github.com/testing-library/user-event/issues/662#issuecomment-904365493 seems to solve it for me

**Comment by JoseLion** [comment]
@cdomigan that's true, the problem can be solved with the solution presented in that comment:
```ts
await waitFor(() => userEvent.click(element))
```

But the code above is waiting for the element to become clickable, which shouldn't be necessary. The real issue is that **react-popper@1.3.11** adds `pointer-events: none` to the parent element, making the whole popover unclickable for a few milliseconds. Then the `pointer-events: none` style is removed.

For me, changing all the tests to wait for popovers to be clickable was not ideal. Not only because we should never need to do that on the test, but also because the problem is solved on **react-popper v2**.

The initial `pointer-events: none` is not necessary, so my solution was to use Yarn2's patch protocol to patch the `react-popper@1.3.11` dependency (you can also use [patch-package](https://github.com/ds300/patch-package) to achieve this). The patch just removes the `pointer-events: none` from the initial styles:
```diff
diff --git a/lib/cjs/Popper.js b/lib/cjs/Popper.js
index 1da9e8b1a5e4c331f598a2633d0920aafa317693..ae32f3754e88189be328e639c674d308c0714411 100644
--- a/lib/cjs/Popper.js
+++ b/lib/cjs/Popper.js
@@ -34,8 +34,7 @@ var initialStyle = {
   position: 'absolute',
   top: 0,
   left: 0,
-  opacity: 0,
-  pointerEvents: 'none'
+  opacity: 0
 };
 var initialArrowStyle = {};
```

You can do the same for the `esm`, `umd`, `flow`, and `umd.min` distributable files. I'm attaching the full patch file in case anyone is interested (had to zip the file because GitHub does allow to upload `.patch` extension files 😅).

🩹 [react-popper-npm-1.3.11-7eb852583d.zip](https://github.com/palantir/blueprint/files/9195106/react-popper-npm-1.3.11-7eb852583d.zip)  

I hope this helps! At least until `MenuItem2` is available in v4.x 🙂

**Comment by cdomigan** [comment]
@JoseLion Thanks - that's the first I'd heard of the patch protocol :)

**Comment by pcclickbit** [comment]
The issue is fixed using MenuItem2 and Popover2
@blueprintjs/popover2 1.5.0

**Comment by adidahiya** [comment]
Great, thanks for the fix verification @pcclickbit.
