### ISSUE TITLE
Selecting a menu item closes popover2 automatically

### ISSUE THREAD

**Issue by riwu** [palantir/blueprint#4695]
#### Environment

- __Package version(s)__: core: 3.44.1, popover2: 0.7.1, select: 3.16.1, react: 17.0.2
- __Operating System__: Windows
- __Browser name and version__: Chrome Version 90.0.4430.93 (Official Build) (64-bit)

#### Code Sandbox

https://codesandbox.io/s/flamboyant-smoke-i7y6m

#### Steps to reproduce

1. Click on Popover button
2. Select "item1" from the Select dropdown

#### Actual behavior
Entire Popover closes

#### Expected behavior
Item should be selected and Popover should not close

#### Possible solution
This can be fixed by adding `event.stopPropagation()` but I'm unsure if it should be fixed at the library level.

**Comment by adidahiya** [comment]
`captureDismiss` allows you to achieve the kind of interaction you want -- it's designed to prevent a click inside a popover from closing _parent_ popovers in addition to the current one. see my fork of your sandbox https://codesandbox.io/s/trusting-taussig-lv927?file=/src/App.js

alas, the problem still persists after adding `popoverProps={{ captureDismiss: true }}`. this is because Select uses Popover, which doesn't coordinate with Popover2 in its `captureDismiss` implementation. it's possible that there's an easy fix we can do here to make these two components work with each other; I think it would help users with the migration to Popover2.

**Comment by no-stack-dub-sack** [comment]
@adidahiya Should this issue still be open, or should a new issue to be opened to track the fact that Selects with `popoverProps={{ captureDismiss: true }}` will not work correctly nested inside Popover2's since Select is still using Popover1 internally?

**EDIT:** As a follow up:

With the following versions, this **DOES NOT** work as expected:
- @blueprintjs/core@3.51.3
- @bluerintjs/select@3.18.10
- @blueprinths/popover2@0.12.9
- See [codesandbox repro](https://codesandbox.io/s/select-capturedismiss-w-popover2-not-working-ptnbr?file=/src/App.tsx)

With the following versions, this **DOES** work as expected:
- @blueprintjs/core@3.52.0
- @bluerintjs/select@3.18.11
- @blueprinths/popover2@0.12.9
- see [codesandbox repro](https://codesandbox.io/s/select-capturedismiss-w-popover2-working-tx3jj?file=/src/App.tsx)

even though both versions use @blueprintjs/popover2@0.12.9 which contains the code that fixed this issue from #4736
