### ISSUE TITLE
ContextMenu2 not opening in the correct location

### ISSUE THREAD

**Issue by jsimonrichard** [palantir/blueprint#4708]
#### Environment

- __Package version(s)__: @blueprintjs/core (3.44.2), @blueprintjs/popover2 (0.4.0)
- __Operating System__: Pop!_OS 20.10
- __Browser name and version__: Firefox 87.0

#### Code Sandbox

Link to a minimal repo: https://codesandbox.io/s/blueprint-sandbox-forked-zb55b?file=/src/index.tsx

#### Steps to reproduce

1. Use `ContextMenu2` as described in the docs.
1. I think that's it unless I'm missing something...

#### Actual behavior

The menu appears outside of the parent of `<ContextMenu2>`.

#### Expected behavior

I expect the menu to be right underneath the click of the mouse, as shown in the docs: https://blueprintjs.com/docs/#popover2-package/context-menu2.

#### Possible solution

I don't have any ideas, but I did notice (through inspect element) that the inset CSS property seemed to be working--it was just putting the context menu in the wrong spot.

**Comment by adidahiya** [comment]
@jsimonrichard you forgot to import `blueprint-popover2.css`. It works after you do this. I've forked your sandbox and fixed the example here: https://codesandbox.io/s/blueprint-sandbox-forked-b7mni?file=/src/index.tsx

Note that I also had to make a small CSS tweak to make the context menu wrapper element `display: inline-block` in order to contain the target area for the right-click interaction, but this is expected and some tweaks like this may have to be made on a case-by-case basis with ContextMenu2's generated wrapper element.
