### ISSUE TITLE
ContextMenu2 does not dismiss tooltip on open

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#4719]
#### Environment

- __Package version(s)__: popover2 0.8.0, core 3.44.2
- __Operating System__: macOS
- __Browser name and version__: Chrome

#### Code Sandbox

https://codesandbox.io/s/blueprint-sandbox-forked-w5nv6?file=/src/CoreExample.tsx

#### Steps to reproduce

Attach a ContextMenu2 to the same target as a Tooltip or Tooltip2, as in the above sandbox.

Hover over and right click on the various tags in the sandbox.

#### Actual behavior

The ones using ContextMenu2 do not dismiss their tooltips when opened

![image](https://user-images.githubusercontent.com/723999/118197665-636bea00-b41d-11eb-862a-5902c9f38161.png)

#### Expected behavior

They _should_ dismiss their tooltips when opened, like the tags using the legacy `@ContextMenuTarget` API:

![image](https://user-images.githubusercontent.com/723999/118197690-6c5cbb80-b41d-11eb-84eb-cba835e75864.png)

**Comment by adidahiya** [comment]
On second thought, this may not be a bug per se. If you look at native context menus, we allow those to pop up while the underlying Tooltip or Tooltip2 is left open:

![image](https://user-images.githubusercontent.com/723999/118860332-41ed8100-b8a9-11eb-9976-1cfe893f4a93.png)

**Comment by aycai** [comment]
To me, the browser context menu appears as a control point coming from outside the page (the browser itself); the right click isn't scoped to the page. Having two different interactions from two separate scopes isn't graceful, but not unreasonable.

ContextMenu2 is an intentional override that is scoped within the page. This means there are two interactions within a single scope, which then makes them feel both ungraceful AND unintended.

I'd opt to dismiss the tooltip when using ContextMenu2, but not so with the browser context menu.
