### ISSUE TITLE
Icons do not have `<desc>` anymore

### ISSUE THREAD

**Issue by santomegonzalo** [palantir/blueprint#4948]
#### Environment

- __Package version(s)__: latest

#### Question

We used to have an old version of every BlueprintJS library but recently we decided to update to the latest version and now all our tests are breaking because the SVG does not include the `<desc>` field that used to have.

Is there any feature to enable this again?

**Expected **

```
            <svg
              data-icon="annotation"
              height="16"
              viewBox="0 0 16 16"
              width="16"
            >
              <desc>
                annotation
              </desc>
              <path
                d="M15.52 2.77c.3-.29.48-.7.48-1.15C16 .73 15.27 0 14.38 0c-.45 0-.85.18-1.15.48l-1.34 1.34 2.3 2.3 1.33-1.35zM7.4 10.9l6.21-6.21-2.3-2.3L5.1 8.6l2.3 2.3zM14 14H2V2h6.34l2-2H1C.45 0 0 .45 0 1v14c0 .55.45 1 1 1h14c.55 0 1-.45 1-1V5.66l-2 2V14zM3 13l3.58-1.29-2.29-2.27L3 13z"
                fill-rule="evenodd"
              />
            </svg>
```

**Current**

```
            <svg
              data-icon="annotation"
              height="16"
              viewBox="0 0 16 16"
              width="16"
            >
              <path
                d="M15.52 2.77c.3-.29.48-.7.48-1.15C16 .73 15.27 0 14.38 0c-.45 0-.85.18-1.15.48l-1.34 1.34 2.3 2.3 1.33-1.35zM7.4 10.9l6.21-6.21-2.3-2.3L5.1 8.6l2.3 2.3zM14 14H2V2h6.34l2-2H1C.45 0 0 .45 0 1v14c0 .55.45 1 1 1h14c.55 0 1-.45 1-1V5.66l-2 2V14zM3 13l3.58-1.29-2.29-2.27L3 13z"
                fill-rule="evenodd"
              />
            </svg>
```

**Comment by evansjohnson** [comment]
hey @santomegonzalo sorry this probably isn't the answer you're looking for but this issue caught my eye since it was removed in this PR I authored as part of Blueprint accessibility efforts: https://github.com/palantir/blueprint/pull/4835/files#diff-83c7c4c4e01f94dfe32f0f5a46660cd8c58fb51cfe6d587df6e60a4547350ea0R74-R76

The `desc` that was set previously was an the icon name with no additional formatting. [\<desc>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc) is an accessible text description for an svg container element so it didn't seem appropriate to set this to something like `"less-than-or-equal-to"`

You may get the same DOM structure by adding `title={iconName}` to your icons but don't know if that is possible everywhere since some components render icons

**Comment by adidahiya** [comment]
@santomegonzalo yeah, as @evansjohnson suggested, I think you should migrate from querying for `<desc>` in your tests to querying for the `[data-icon="..."]` attribute instead.

**Comment by santomegonzalo** [comment]
Thanks @evansjohnson and @adidahiya for your reply! I will close this issue now!
