### ISSUE TITLE
[v4] Items in control group have gaps and rounded borders

### ISSUE THREAD

**Issue by zachkirsch** [palantir/blueprint#5140]
#### Environment

- __Package version(s)__: 4.0.0-beta13
- __Operating System__: OS X
- __Browser name and version__: Chrome Version 98.0.4758.102 (Official Build) (x86_64)

#### Steps to reproduce

Repro is on the docs.

V3 looks great:

<img width="808" alt="Screen Shot 2022-02-23 at 6 48 26 PM" src="https://user-images.githubusercontent.com/8902272/155448289-28d16dbe-05d4-43f2-8719-89c38382c552.png">

https://blueprintjs.com/docs/#core/components/control-group

V4 has gaps and rounded borders

<img width="801" alt="Screen Shot 2022-02-23 at 6 48 12 PM" src="https://user-images.githubusercontent.com/8902272/155448413-eb1274b8-ffce-4916-97f1-10c314e6bb66.png">

https://blueprintjs.com/docs/versions/4/#core/components/control-group

#### Possible solution

¯\\\_(ツ)\_/¯

**Comment by adidahiya** [comment]
This is an intentional design change with the updated color palette. We had to change the border styles for inputs to fulfill color contrast accessibility requirements, and this visual change was necessary to make the elements look good next to each other with the new border styles. It looks worse when there's no gap between the elements.

**Comment by zachkirsch** [comment]
Ah makes sense!
