### ISSUE TITLE
Upgrade to @blueprintjs/core v3.54.0 and @blueprintjs/popover2 v0.14.0 is causing syntax error

### ISSUE THREAD

**Issue by dlech** [palantir/blueprint#5185]
#### Environment

- __Package version(s)__: @blueprintjs/core v3.54.0 , @blueprintjs/popover2 v0.14.0
- __Operating System__: Ubuntu 20.04
- __Browser name and version__: N/A

#### Code Sandbox

N/A

#### Steps to reproduce

N/A

#### Actual behavior

There is a CI error when dependabot attempted to upgrade.

```
 ./node_modules/@blueprintjs/core/lib/esnext/common/abstractComponent.js
SyntaxError: /home/runner/work/pybricks-code/pybricks-code/node_modules/@blueprintjs/core/lib/esnext/common/abstractComponent.js: Missing class properties transform.
  24 | export class AbstractComponent extends React.Component {
  25 |     /** Component displayName should be `public static`. This property exists to prevent incorrect usage. */
> 26 |     displayName;
     |     ^^^^^^^^^^^^
  27 |     // Not bothering to remove entries when their timeouts finish because clearing invalid ID is a no-op
  28 |     timeoutIds = [];
  29 |     constructor(props, context) {
```

https://github.com/pybricks/pybricks-code/runs/5630817758?check_suite_focus=true#step:9:15

The only thing in the popover2 changelog is that the typscript package was updated, so I assume this is the cause.

https://github.com/palantir/blueprint/wiki/3.x-Changelog#blueprintjspopover2-0140

#### Expected behavior

Package should be able to upgrade without error.

**Comment by adidahiya** [comment]
I'm not familiar with your build tool [craco](https://github.com/pybricks/pybricks-code/blob/master/craco.config.js) but from quick googling it looks like you just need to update your Babel config to [process some additional syntax with `@babel/plugin-proposal-class-properties`](https://stackoverflow.com/questions/35517245/error-missing-class-properties-transform)? When consuming the `lib/esnext/` folder of Blueprint NPM packages, there may be some small breaking changes when we upgrade TS versions. I'm not sure it's worth it for us to work around this break on the Blueprint side, but I'm open to suggestions if it turns out to be a widespread issue.

**Comment by dlech** [comment]
Thanks for the hint. I agree, this doesn't sound like a blueprint bug in that case.
