### ISSUE TITLE
Do any React components use the new font icon in BP 4?

### ISSUE THREAD

**Issue by maclockard** [palantir/blueprint#5197]
#### Environment

- __Package version(s)__: blueprint 4

#### Question

Blueprint 4 brings back icon fonts when using the CSS API https://blueprintjs.com/docs/#core/components/icon.css.

Do any of the exported React components use the CSS API for setting icons or do they all use `<Icon />` under the hood?

I'm asking since I'm thinking of overriding some of the built in blueprint icons such as 'cog' with my own SVGs and was curious if replacing the files in `@blueprintjs/icons/lib/{esm|esnext|cjs}/generated/{16|20}px/paths` with my own would be adequate? (I realize this use case might not be fully supported in the future)

**Comment by adidahiya** [comment]
> Do any of the exported React components use the CSS API for setting icons or do they all use <Icon /> under the hood?

Good question. The React components do not use the icon font. I will add this clarification to the docs.

> I realize this use case might not be fully supported in the future

This is changing pretty soon, btw... in v5, in order to support tree shaking, icons will be exported as components in addition to those path strings at `/generated/{16|20}px/paths/...` like this: https://unpkg.com/browse/@blueprintjs/icons@4.0.0-alpha.0/lib/esm/generated/components/add-column-left.js. Those icon components will be used within other BP components.

The `<Icon icon="..." />` API will still be available, and that will use the generated paths files under the hood (your replacement strategy ought to continue working there).

**Comment by maclockard** [comment]
Curious why not have the generated component just directly import from the generated file paths (`/generated/{16|20}px/paths/add-column-left.js`)? seems like it would result even smaller bundle sizes from only having the paths defined once

**Comment by adidahiya** [comment]
> Curious why not have the generated component just directly import from the generated file paths

Actually, I misspoke earlier. The generated component modules are _replacing_ the path strings; they are not in addition to the path strings. The `<Icon icon="..." />` API loads those generated component modules on-demand.

**Comment by maclockard** [comment]
ah gotcha, makes sense!
