### ISSUE TITLE
Don't allow "clear" button on datepicker action bar when "canClearSelection" is set

### ISSUE THREAD

**Issue by AlMck2** [palantir/blueprint#5228]
#### Environment

- __Package version(s)__: 3.23.1
- __Browser and OS versions__: Google Chrome 99.0.4844.74 on Mac OS 12.3.1

#### Feature request

It would be really nice (and I initially assumed it would until testing) if when `canClearSelection` is set, the "Clear" button on the action bar would be disabled

**Comment by adidahiya** [comment]
I assume you're talking about the DatePicker component in @blueprintjs/datetime v3.23.1 (in the future, please be more specific in issue reports, as we have multiple packages and they have independent versioning... ideally you should create a code sandbox as linked in the bug report issue template).

<img width="272" alt="image" src="https://user-images.githubusercontent.com/723999/161812744-b90d184d-3cac-4732-a56d-aafdc974a1e5.png">

I don't think the actions bar (shown above) is designed for the kind of use case you're proposing. It would look unbalanced if we just removed the "Clear" button, with "Today" hanging out on the left side.

What if you enabled the shortcuts menu instead of the actions bar?

<img width="406" alt="image" src="https://user-images.githubusercontent.com/723999/161812896-19d300f8-583f-4ab9-8cf4-eb6c4b4b36f8.png">

**Comment by AlMck2** [comment]
> in the future, please be more specific in issue reports, as we have multiple packages and they have independent versioning... ideally you should create a code sandbox as linked in the bug report issue template

Apologies, I did mention the datepicker in the title, but could have been more clear. 

> It would look unbalanced if we just removed the "Clear" button, with "Today" hanging out on the left side.

Well, I was suggesting disabling it rather than removing it completely. Although it might be an idea to allow more flexibility around the action bar, like you do with the shortcuts bar. 

> What if you enabled the shortcuts menu instead of the actions bar?

The reason we want the action bar is because we have a number of different date inputs, and the clear button is very useful, but there are 1 or 2 that we don't want people to be able to clear, and removing the entire bar for those ones (or enabling the shortcuts bar instead) would look a bit confusing having them look quite significantly different, when they are next to each other.

**Comment by adidahiya** [comment]
Ok, that's fair. I would accept a PR which disabled the clear button in the actions bar in this case, that sounds like a reasonable UX approach which a Blueprint user can opt-in to 👍🏽
