### ISSUE TITLE
When using columnWidths prop in Table, new columns have no width

### ISSUE THREAD

**Issue by nllevin** [palantir/blueprint#5264]
#### Environment
@blueprintjs/table 4.1.2

#### Code Sandbox

Link to a minimal repro: [sandbox](https://cwjgwe.csb.app)

#### Steps to reproduce

1. Create a table with `columnWidths` prop
2. On a subsequent render, add additional columns with `undefined` in the `columnWidths` array.

#### Actual behavior

The new columns have no width, aside from padding. The header cells render in the correct position, but the body cells have no `left` CSS property, so they render on top of the first column.

#### Expected behavior

New columns should be assigned a default or best-guess width, the same as happens on a first render when the `columnWidths` array contains `undefined`.

**Comment by adidahiya** [comment]
I tried swapping Table with Table2 (where we've been making a number of improvements/fixes lately), and the issue is still there: https://codesandbox.io/s/blueprint-table-adding-columns-i5obss?file=/src/index.tsx

I'll look into a bugfix this week.

**Comment by N1kto** [comment]
Hello!
Looks like there is still some issue with `columnWidths` prop.

**Environment**
"@blueprintjs/table": "4.7.9"

**Code Sandbox**
Link to a minimal repro: [demo](https://codesandbox.io/s/zealous-johnson-7y0jc5?file=/src/App.js:0-23)

**Steps to reproduce**
Checkout the demo code:
- initially `colWidths` contains `null` value for the 1st column width and 230 for the 2nd column;
- further we have an effect which updates `colWidths`: we set 400 width for the 1st column, 2nd column remains the same;
- finally we have a toggle which allows to set both columns' widths to 300;

Now follow these steps:
1. Load the page
2. Click the "Set all cols 300 width" button 
3. Click "Set all cols 300 width" again

**Actual behavior**
1. Once loaded column widths are: some "default" value for 1st col and 230 for the 2nd one
2. Upon 1st click column widths are: 400 and 230
3. Upon 2nd click column widths are: 300 and 300

**Expected behavior**
1. Once loaded, column width should be 400 and 230 due to effect we ran on mount
2. Upon 1st click on "Set all cols 300 width" rendered columns should have 300 and 300 widths

**Observations**
1. It seems like `Table2` uses _previous_ value of  `columnWidths`, hence lagging the most recent value;
2. If you try scrolling the table, it "forces" table to re-render with proper column widths;
3. Adding `colWidths` (which is passed via `columnWidths` prop) to `cellRendererDependencies` "fixes" the issue;

I think it would be natural if table would re-render as soon as `columnWidths` is updated without the need to add `columnWidths` to `cellRendererDependencies`.

**Comment by adidahiya** [comment]
> I think it would be natural if table would re-render as soon as `columnWidths` is updated without the need to add `columnWidths` to `cellRendererDependencies`.

@N1kto this is actually the intent of the component implementation, see https://github.com/palantir/blueprint/blob/13be38868ed90c2543bb0e4d29f82ed56b8e97e2/packages/table/src/table2.tsx#L576-L579

Can you please file a new issue for your problem? I have some feedback on the sandbox you shared. First: I think you need to wait until Table2's `onCompleteRender` is called once before running your effect to update columnWidths, or supply the initial widths as the original props. We can continue discussion about this in a new issue.
