### ISSUE TITLE
Disabled button still opens Popover menu

### ISSUE THREAD

**Issue by benny-medflyt** [palantir/blueprint#530]
When clicking the button itself, nothing happens (good).

But when clicking precisely on the "caret" icon inside the button, the menu opens up (bad).

<img width="326" alt="screenshot" src="https://cloud.githubusercontent.com/assets/24827547/22205840/3c1aa4c8-e181-11e6-8fd4-d8c375f55297.png">

```
                    <Popover
                        content={
                            <Menu>
                                <MenuItem
                                    text="Test"
                                    />
                            </Menu>
                        }>

                        <button disabled={true} type="button" className="pt-button pt-intent-primary">
                            Action
                            <span className="pt-icon-standard pt-icon-caret-down pt-align-right"></span>
                        </button>
                    </Popover>
```

**Comment by giladgray** [comment]
The correct way to disable a Popover is with the `disabled` prop on
`<Popover>` itself. Disabling the button is merely for appearance here (you
must do that yourself, as you have). This is because Popover still captures
events from elements inside the button.

We could improve the query to detect disabled elements... That'd be nice.

**Comment by benny-medflyt** [comment]
Thanks, setting `isDisabled` on the Popover does indeed do the trick.
I suppose this issue can be closed
