### ISSUE TITLE
Spinner item does not take other props

### ISSUE THREAD

**Issue by bvandrc** [palantir/blueprint#5317]
#### Environment

- __Package version(s)__: 4.3.2
- __Operating System__: Windows 10
- __Browser name and version__: Chrome / All

#### Steps to reproduce

Trying to pass other props to the `Spinner` item, and they don't take effect. Specifically, trying to add `aria-label` to the `Spinner` item, and that prop is not being implemented.

#### Expected behavior

Ability to pass various other props to the Spinner item

**Comment by bvandrc** [comment]
This is essential for accessibility given the `aria-progressbar-name` rule: https://accessibilityinsights.io/info-examples/web/aria-progressbar-name/ .

So since `Spinner` automatically has `role="progressbar"`, and `"progressbar"` needs `aria-label` or `aria-labelledby`, and you can't pass either of these to `Spinner`, there's no way to get it to pass a11y rules.

**Comment by adidahiya** [comment]
1. I'm all for a11y markup; we should add the required markup attributes to Spinner by default
2. I would also support spreading arbitrary HTML attrs to Spinner, open to a PR for that

**Comment by bvandrc** [comment]
@adidahiya would you like me to contribute the PR? 

Also regarding #1, what do you mean by this? I'm not sure we could have a default `aria-label` for `Spinner`, as a dev would always want to set their own unique value, and would sometimes want to use `aria-labelledby` instead of `aria-label`

**Comment by adidahiya** [comment]
Ah ok, right, you'd want to set a custom `aria-labelledby` or `aria-label`. I was more so suggesting that we should add the suggested a11y markup attrs out of the box, if there are any we are missing which we can set statically. If there are no more we can do out of the box, that makes sense.

Yes I would be happy to review a PR from you which adds support for arbitrary attributes on the Spinner element. It might be tricky because we support the custom `tagName` prop, so those attributes could be of type `HTMLAttributes<any> | SVGAttributes<any>`... but it should be doable.

**Comment by bvandrc** [comment]
@adidahiya see my PR-- I didn't change the types, I just did it like how other elements that have both `tagName` and `htmlProps` do it

**Comment by adidahiya** [comment]
Ah, that's right, I forgot that `aria-` props are [built-in to JSX for React](https://reactjs.org/docs/accessibility.html). That makes it easier to add this feature.
