### ISSUE TITLE
Control Group is not applying styles correctly to descendant inputs

### ISSUE THREAD

**Issue by rneogy** [palantir/blueprint#5373]
This is visible right on the documentation: https://blueprintjs.com/docs/#core/components/control-group

![image](https://user-images.githubusercontent.com/10761674/173673266-7e2dfc54-d6c9-48bd-a917-09a1144bfe13.png)

You can see how it is supposed to look like on the v3 documentation:

![image](https://user-images.githubusercontent.com/10761674/173673354-f9a03f56-c8e2-494f-8687-3df43770e264.png)

**Comment by adidahiya** [comment]
This was an intentional change made to ControlGroup in Blueprint v4.0, see [this wiki page](https://github.com/palantir/blueprint/wiki/Blueprint-4.0#control-group-borders).

Looks like we need to update the documentation for ControlGroup, though, as it still references the old visual style:

> A control group renders several distinct form controls as one unit, _squaring the borders between them_.

I'll make that documentation fix.

**Comment by rneogy** [comment]
Ah okay, good to know. Thanks!
