### ISSUE TITLE
it would be great to see all ui elements in one place

### ISSUE THREAD

**Issue by liesislukas** [palantir/blueprint#568]
in documentation i see only sketch file. i'm not user of sketch. Had to download this app just to make export to pdf/png of all that view. Would be great to be able to just download pdf/png in future releases. Also made PR with these files for current version:

https://github.com/palantir/blueprint/pull/567

**Comment by llorca** [comment]
@liesislukas how is a PDF or a PNG helping at all? The purpose of the Sketch file is to help you mock up high fidelity views with Sketch. A PNG or PDF file is a static image and cannot be considered a resource or asset. If you need to browse all the components, simply [go look at them live](http://blueprintjs.com/docs/). We're also tracking https://github.com/palantir/blueprint/issues/125 to provide a single page preview of all the interactive components.

**Comment by giladgray** [comment]
@liesislukas we're not interested in maintaining static image files of the components because they're so highly interactive. Sketch supports this through its reusable styles (feels a lot like CSS classes). It's a terrific tool for interface design (much friendlier than Photoshop); perhaps you should give it a shot!

related: #125 proposes adding a demo page to see components without all the docs text.

**Comment by liesislukas** [comment]
#125 is great, i look forward. It would be best.
