### ISSUE TITLE
InputGroup incorrectly forces a 30px right padding that can't be overriden

### ISSUE THREAD

**Issue by colbycheeze** [palantir/blueprint#569]
### Bug report

- __Package version(s)__: 1.7.0
- __Browser and OS versions__: All

#### Steps to reproduce

InputGroup incorrectly forces a 30 pixel right padding on anything without a "rightElement"
It looks like the bug is happening here.  
https://github.com/palantir/blueprint/blob/master/packages/core/src/components/forms/inputGroup.tsx#L53-L55  
This default value should be zero if no rightElement exists.

There is no way to override this functionality to fix styles without using a hack of passing in a blank string for `rightElement` every time we don't want an actual element there, which ends up rendering useless elements.

![c71033eaecc116cafde8f8a34516f005 _screen 20shot 202017-01-29 20at 2011 03 45 20am](https://cloud.githubusercontent.com/assets/8884298/22406142/c53bf244-e612-11e6-9881-e8961af9c48f.png)

**Comment by giladgray** [comment]
your blank string is _causing_ the empty element to appear because it is a defined value. use `rightElement={undefined}` (or `null` if you must) instead so it will pass [this check](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/forms/inputGroup.tsx#L103-L105) and omit the `.pt-input-action` element.

**Comment by giladgray** [comment]
for the record, the 30px right padding is coming from [the CSS](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/forms/_input-group.scss#L79) in this case because of the empty `.pt-input-action` element.

the correct fix here is for @colbycheeze to ensure that his usage of `InputGroup` will not output this element, by either omitting `rightElement` or by setting it to `undefined` explicitly.

**Comment by colbycheeze** [comment]
That's not correct I must have explained wrong. Let me give another screenshot where I **don't** pass in rightElement, and it adds right padding to the `style` tag (not the css)

![51b22a05fde680f95f88a7ea91af5f43 _screen 20shot 202017-01-29 20at 2012 33 05 20pm](https://cloud.githubusercontent.com/assets/8884298/22406808/42af0192-e61f-11e6-93fc-e32f16355f11.png)

The screenshot above shows what happens AFTER I apply the hack of passing in a blank string for rightElement to fix it

**Comment by llorca** [comment]
Our example passes `undefined` to the `rightElement` prop, works fine: https://github.com/palantir/blueprint/blob/master/packages/core/examples/inputGroupExample.tsx#L53

What are you doing differently?

**Comment by colbycheeze** [comment]
@llorca Okay I apologize, I **thought** I was on 1.7, but apparently I needed to redo my `yarn install` (I had 1.6)...it seems to be fixed in latest. Thanks for looking into it anyhow :)
