### ISSUE TITLE
Select2 does not open properly with space or enter when focused

### ISSUE THREAD

**Issue by jrafidi** [palantir/blueprint#5775]
#### Environment

- __Package version(s)__: 4.12.0
- __Operating System__: OSX
- __Browser name and version__: Chrome 107.0.5304.121

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://blueprintjs.com/docs/#select/select2

#### Steps to reproduce

1. Get focus on the select in the docs page
2. Press space or enter

#### Actual behavior

Popover opens and closes instantly.

#### Expected behavior

Popover stays open.

#### Possible solution

Probably combination of a key listener and the DOMs general handling of space/enter on buttons, since `ArrowDown` seems to work fine.

**Comment by justinbhopper** [comment]
@adidahiya I believe I've discovered the root cause of this issue.  However, I'm not sure of a good solution or workaround that doesn't impact existing behavior.

The following happens in single keystroke (up and down) when pressing Enter on a button that is wrapped within a popover:
1. `onKeyDown` "Enter" occurs on `AbstractButton`, which bubbles to the Popover2.  Popover2 [handles this and opens as a result](https://github.com/palantir/blueprint/blob/develop/packages/popover2/src/popover2.tsx#L356-L358).
2. `onKeyUp` "Enter" occurs on `AbstractButton`, which it is [programmed to dispatch a click event](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/button/abstractButton.tsx#L198).
3. The click event [reaches `Popover2`](https://github.com/palantir/blueprint/blob/develop/packages/popover2/src/popover2.tsx#L354), which causes it to immediately toggle back to close.

The only way I can imagine this getting fixed is if either AbstractButton stops dispatching a click event onKeyUp, or if Popover2 somehow knew that the click event it is handling was a result of the same keydown/keyup combination that already occurred previously within its target element.
