### ISSUE TITLE
Clicking Table Column Header Menu Button Selects Column

### ISSUE THREAD

**Issue by OliverWales** [palantir/blueprint#5929]
#### Environment

- __Package version(s)__: 4.15.1
- __Operating System__: MacOS
- __Browser name and version__: Chrome 109.0.5414.119

#### Code Sandbox

Can be reproduced on the table sorting example [here](https://blueprintjs.com/docs/#table/features.sorting).

#### Steps to reproduce

1. Create a table with `menuRenderer` set
2. Click on the chevron to open the menu

#### Actual behavior

The whole column is selected, triggering onSelect listeners etc.

#### Expected behavior

The selection is not modified.

#### Possible solution

Add `preventDefault` and `stopPropagation` to the open menu button `onClick`

**Comment by adidahiya** [comment]
It looks like we don't have any option to customize the selection behavior when clicking on column header cell menu targets. Currently, if column selection is enabled, opening the menu will always select that column.

Here's a quick sketch of one approach to implementing a new feature that allows users to customize whether clicking on the menu dropdown selects the cells in that column (one that does _not_ involve `stopPropagation`, which I often discourage because of its unintended side-effects): 

1. add a prop to `<ColumnHeaderCell2>` which adds a new CSS class (let's say `TABLE_TH_MENU_SELECT_CELLS`) to the `TABLE_TH_MENU_CONTAINER` element. it will have to be true by default to preserve existing behavior.

```ts
/**
 * Whether clicks on the header menu target element should cause the column's cells to be selected.
 *
 * @default true
 */
selectCellsOnMenuClick?: boolean;
```

2. add some handler logic in TableBody2 (probably in the [`locateClick`](https://github.com/palantir/blueprint/blob/c54d5ac7530cb770fa4ab321fce3a13878b46006/packages/table/src/tableBody2.tsx#L157-L160) function) to ignore clicks when the `event.target` is inside a `TABLE_TH_MENU_CONTAINER` which does _not_ have the `TABLE_TH_MENU_SELECT_CELLS` class.

**Comment by OliverWales** [comment]
Thanks @adidahiya! Will give this a go if I find the time this week 💪🏻
