### ISSUE TITLE
DateInput2 timezone selection test failures on some PRs

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#6041]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/723999/227949756-e0e708e4-0823-4c4b-8aa9-0dd0c5e3d121.png">

https://app.circleci.com/pipelines/github/palantir/blueprint/4066/workflows/b9767d1c-bb7b-43fb-9183-0633869191f1/jobs/69863

https://github.com/palantir/blueprint/pull/6039

Possibly related to daylight savings time changes...

**Comment by bvandercar-vt** [comment]
I started to look into this, definitely due to daylight savings time changes, Paris is now in GMT+2 not GMT+1.

In looking at this, I also noticed something else: https://github.com/palantir/blueprint/blob/develop/packages/datetime2/test/components/dateInput2Tests.tsx#L226 Line 266 if the default time is 10:30 UTC and the timezone is changed to -05:00 , shouldn't the time also be changed to 5:30 to make it equivalent to the existing time value? In other words, if the timezone is changed but the hours are not, the time gets changed to 5 hours in the future instead of staying current.
