### ISSUE TITLE
DATETIME: max date selection is 11/03/2023 ?!

### ISSUE THREAD

**Issue by darkopetrovic** [palantir/blueprint#6118]
Bug with the date selection. We cannot select a date beyond 11/03/2023. 

Got the problem locally but seems the same with the examples in the doc.

![image](https://user-images.githubusercontent.com/1554288/235870602-48d2b2cb-761d-4b26-a356-8bcb2308e5ac.png)

**Comment by qcz** [comment]
It works like this because of this PR: https://github.com/palantir/blueprint/pull/5091 Before that the default max date was the end of the year which I think was a better default (with a little tweaking, like use the end of next year if the end of this year is too close).

However you can change it for yourself with the `maxDate` prop.

**Comment by adidahiya** [comment]
Use the `maxDate` prop.

Open to PRs to change the default max date = the end of the year (or the end of next year, if the current date is within 3 months of the end of the year.
