### ISSUE TITLE
Missing examples for toasts in functional components

### ISSUE THREAD

**Issue by Lippiece** [palantir/blueprint#6133]
#### Environment

- __Package version(s)__: 4.18.0
- __Browser and OS versions__: Chromium 112.0.5615.165

#### Question

I don't see any examples about using toasts with modern React component syntax. With the help of a neural network, I figured out that there are 2 main points:

<details>
<summary>Use `useRef`</summary>

```tsx
const Component = () => {
...
  const toaster  = useRef<Toaster>( null )
...
return <>
...
  <Toaster ref={ toaster }/>
</>

```
</details>

<details>
<summary>Then call its `show` function to create toasts</summary>

```tsx
  toaster.current?.show( toastProperties )
```

</details>

I'd suggest reflect that in docs if functional components are "supported" by Blueprint.

**Comment by adidahiya** [comment]
@Lippiece there is documentation [here](https://blueprintjs.com/docs/#core/components/toast.overlaytoaster) demonstrating the same API you have just described (attach a ref to an OverlayToaster and use the `.show()` instance method on it).

![image](https://github.com/palantir/blueprint/assets/723999/443354eb-3234-499c-a7c2-fab6c286ec61)

There is no specific mention of function components since it is generally implied that all Blueprint APIs work with function components (unless stated otherwise).
