### ISSUE TITLE
KeyCombo renders mod as ^ instead of Ctrl on Windows

### ISSUE THREAD

**Issue by alexbrt** [palantir/blueprint#6211]
#### Environment

- __Package version(s)__: 4.20.1
- __Operating System__: macOS Ventura 13.4 (22F66)
- __Browser name and version__: Version 114.0.5735.106 (Official Build) (arm64)

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/p/sandbox/blueprint-sandbox-2023-fjo3z4)): 

#### Steps to reproduce

N/A

#### Actual behavior

`^` is rendered instead of `Ctrl` on Windows.

#### Expected behavior

I expected `Ctrl` to be rendered instead of `^`.

#### Possible solution

Check for `mod` instead of `meta` [here](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/hotkeys/hotkeyParser.ts#L292-L298)?

**Comment by adidahiya** [comment]
@alexbrt do you have the same issue with Blueprint v5? Any bugfix for this is unlikely to be backported to v4.x.

**Comment by Zaida-3dO** [comment]
Hello, this issue still exists on Blueprint v5

#### Code Sandbox

Link to a minimal repro https://codesandbox.io/p/devbox/rough-microservice-gdctt3

#### Screenshots


| Mac | Windows |
| --- | ------- |
| <img width="248" alt="image" src="https://github.com/user-attachments/assets/a780282b-dfc6-40d2-a716-98e5f0c09ea2">   | ![image](https://github.com/user-attachments/assets/0eed85af-ae62-4e3a-940a-5f70a4819d89) |



#### Expected behavior

I expected `Ctrl` to be rendered instead of `^ Ctrl` on the standard `KeyComboTag`. This is because `^` icon doesn't mean much to windows users so it is unnecessary here

A bigger issue is on the minimal version, I expected `Ctrl A` instead of `^ A` because the latter would be completely unreadable for most windows users as they would have no idea what the `^` icon means
