### ISSUE TITLE
Is it expected that the icon-related files are output when built even if icons are not imported dynamically?

### ISSUE THREAD

**Issue by tonooo71** [palantir/blueprint#6249]
#### Environment

- __Package version(s)__: 5.0.0
- __Browser and OS versions__: Windows 10 and Microsoft Edge 113.0.1774.42

#### Question

Is it expected that the icon-related files are output when built even if icons are not imported dynamically?
For example, if I add only a Button component without icon prop to my project and build, 

```ts
<Button>Text</Button>
```
the following file will be output even though icons are not used.
```
dist/index.html
dist/index.css
dist/index.js
dist/assets/allPaths-b5d12eca.js
dist/assets/allPathsLoader-2e1a132b.js
dist/assets/splitPathsBySizeLoader-c0b3533e.js
dist/assets/index-5aa9ee64.js                   
dist/assets/index-c332d9fb.js
``` 
(The latest Vite template was used in the example above.)

After a little investigation, I found that the above files are loaded in the Icon component when the icon prop is specified as string, and that a Button component contains an Icon component.
In the above case, icons are not imported dynamically, so I would like the files to be removed by the bundler's tree shaking, but is this behavior a spec?

**Comment by adidahiya** [comment]
The "allPaths", "allPathsLoader", "splitPathsbySizeLoader" files will be output by your bundler but they won't be loaded in the browser since they're dynamically imported. They're small files anyway. This gives you the _option_ to use the `icon="some-icon"` prop on `<Button>` and other Blueprint components.

It's exceedingly rare to use Blueprint to build a UI _without_ icons (they are quite useful in the design system), so icon support is tightly integrated into many components with this approach. Blueprint v5 gives you the option to tree-shake and dynamically import icons so that you can optimized your bundle size at runtime.

**Comment by tonooo71** [comment]
Thank you for your answer.

> It's exceedingly rare to use Blueprint to build a UI without icons (they are quite useful in the design system)

Yes, I agree and I thought I was using Blueprint with static import icons only.
So it was wondering why the icon files used by dinamically imported icons was being output and loaded.
But I noticed that `<Callout intent={Intent.WARNING} >` imports `warning-sign` icon dynamically.
By changing to `<Callout intent={Intent.WARNING} icon={<WarningSign />}>`, the files are now output but not loaded.

**Comment by adidahiya** [comment]
@tonooo71 good catch, I forgot to change the Callout implementation to use the static icon imports. I'll go ahead and make that change.
