### ISSUE TITLE
React 18 StrictMode Compatibility Plan/State

### ISSUE THREAD

**Issue by jkillian** [palantir/blueprint#6572]
#### Question

Hello! More of a general question here than a bug/feature request. I was wondering if there's a place to see the current state of Blueprint [React 18 StrictMode](https://react.dev/reference/react/StrictMode) compatibility?

I see that [the v5.0 migration guide mentions that some compatibility changes won't come until v6](https://github.com/palantir/blueprint/wiki/Blueprint-5.0#coming-in-v6):

<img width="883" alt="image" src="https://github.com/palantir/blueprint/assets/1400151/731e2b32-776e-41d8-93d4-decc52079743">

However, for the overlay issue for example, https://github.com/palantir/blueprint/issues/3979#issuecomment-1548331152 indicates that `Overlay2` can be added in Blueprint v5.x.  I also see there are some other related open issues, like this one about ContextMenu positioning: https://github.com/palantir/blueprint/issues/5503. It seems like these all maybe just comes back to resolving https://github.com/palantir/blueprint/issues/3979, which could be done in 5.x, before BP has full compatibility?

Given all this, I was curious if these changes were planned for an upcoming BP 5.x release or still going to be deferred until BP v6? And if the latter, if there was a rough estimate on when BP v6 was planned for?

My main motivation for asking these questions is I just wanted to get a grasp on the feasibility of using Blueprint with React 18's concurrency features (which StrictMode should help test compatibility for). Thanks for any information!

**Comment by adidahiya** [comment]
I'm getting pretty close with the Overlay2 implementation which ditches `ReactDOM.findDOMNode`, expect this to land in a release by end of this month: https://github.com/palantir/blueprint/pull/6656

And then that only leaves Portal which uses legacy context (I think that wiki page you screenshotted is outdated, since @blueprintjs/table doesn't use context right now).

~The current Portal component which is backwards-compatible with legacy context seems to be rendering fine inside `<React.StrictMode>` in #6656, so I think Blueprint should be compatible with strict mode in v5.x with the release of Overlay2.~

Edit: Portal produces a deprecation warning in strict mode, but I don't think this will prohibit the rest of your application from being strict mode compatible. The checks only run in development anyway:

![image](https://github.com/palantir/blueprint/assets/723999/6ce8d7b8-c0a0-4311-b8f2-e16641bb982a)

**Comment by jkillian** [comment]
Amazing, thanks for the updates and work @adidahiya!
