### ISSUE TITLE
EditableText not firing an onChange on esc

### ISSUE THREAD

**Issue by a-k-g** [palantir/blueprint#687]
### Bug report

- __Package version(s)__: 1.9.0
- __Browser and OS versions__:  56.0.2924.87 (64-bit) Mac

#### Steps to reproduce

1. Start with your `EditableText` component empty
1. Click on it
1. Type "MyText"
1. Press `esc`

#### Actual behavior

1. onChange fires on each keystroke when typing "MyText"
1. onChange doesn't fire on `esc`
1. `EditableText` component goes out of focus and retains the text "MyText"

#### Expected behavior

1. onChange fires on each keystroke when typing "MyText"
1. onChange fires again on `esc`
1. `EditableText` component goes out of focus and goes back to being empty

This was fine in 1.8.0. Seems related to the various `EditableText` fixes that went into 1.9.0.

**Comment by giladgray** [comment]
This is actually no longer expected behavior, indeed to the fixes from 1.9.0. Per the [release notes for 1.9.0](https://github.com/palantir/blueprint/releases):

- :star2: __Changed__ `EditableText` event handling #629 #573 #483
  - `onChange` is called only when the input's value changes
  - `onConfirm` is called on <kbd>enter</kbd> or blur; `onCancel` is called on <kbd>esc</kbd>

**Comment by giladgray** [comment]
Yowie after a closer reading of the issue and some fiddling with the example, there's definitely a bug here. So sorry for shutting that down prematurely.
