### ISSUE TITLE
Toast link action design issues

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#693]
Aggregating some feedback we've had for toasts
"I didn't know I could click on “View X” - it was non obvious that it was a button / clickable versus the other text"

Some users would like the link to be blue to indicate that it is a link
-If the action has an `href` - make it blue, for link consistency 

" we were worried that the link had the exact same visual styling as the content and thus didn’t feel actionable"

Also received feedback to make toasts have max width

**Comment by llorca** [comment]
- We could increase the spacing between the toast message and the toast action to make it more obvious.
- Toasts already have both a `min-width` and `max-width`:
```css.scss
$toast-min-width: $pt-grid-size * 30 !default;
$toast-max-width: $pt-grid-size * 50 !default;
```

**Comment by thisisalessandro** [comment]
A few thoughts:
- Increasing the space is going to make it clearer that the action is not part of the content, but it's not going to make it look any more clickable
- `if href: blue` isn't super solid in my opinion because other common uses of that action (like Undo) are not covered and would look just as un-clickable
- We could say that actions in toasts should have a `pt-intent-primary` to make them more clickable, but how should that adapt to a toast with an intent?

**Comment by tonypoor** [comment]
I think this problem is exacerbated in toasts. They're usually transient, so it's even more important that you can quickly parse them.

> Increasing the space is going to make it clearer that the action is not part of the content, but it's not going to make it look any more clickable

Yeah, agree w/ this.

> We could say that actions in toasts should have a ``pt-intent-primary`` to make them more clickable, but how should that adapt to a toast with an intent?

What if normal toasts had ``pt-intent-primary`` and other toasts didn't? I get that it's not as theoretically pure and maybe violates the semantics of that intent, but maybe that's okay?

FWIW, @thisisalessandro and I took a look through all the existing Blueprint components for other examples of buttons/links on colored backgrounds. Only thing we found was callouts (which don't currently support that but not insane that they someday could).

**Comment by thisisalessandro** [comment]
@tonypoor https://github.com/palantir/blueprint/issues/699

**Comment by llorca** [comment]
Worth noting that colored toasts and colored callouts are different: toasts get the solid color, while callouts get the color with a 15% opacity.

We've mostly been ignoring buttons on top of colored background, we don't have a good story for it. What kind of modifier does a button need to be legible on top of a colored background? `pt-white`? `pt-colored-background`? Colored toasts have [specific CSS rules](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/toast/_toast.scss#L256) that makes minimal buttons look good no matter what the background color

**Comment by celinenguyen** [comment]
Can I ask what the process was for redesigning the toasts? The older Blueprint toasts had a very clear divider between the toast text and the action area, which I appreciated. I'm curious what other tradeoffs/considerations were involved

**Comment by llorca** [comment]
@celinenguyen Previous version was using custom elements/styling, new one uses Blueprint minimal buttons. We simply dropped the previous custom implementation and went for a straightforward minimal button composition inside toasts.

**Comment by thisisalessandro** [comment]
@celinenguyen a few (1 or 2) colorblind people mentioned they couldn't tell apart red and green intents, so we went full Rambo and made the whole toast colored.

![rambo.gif](http://stream1.gifsoup.com/view2/20151212/5276396/rambo-o.gif)

**Comment by adidahiya** [comment]
@llorca Is this still relevant? I haven't seen much feedback around this so I'm inclined to close it.
