### ISSUE TITLE
Stacking issue with navbar and control groups

### ISSUE THREAD

**Issue by llorca** [palantir/blueprint#700]
### Bug report

- __Package version(s)__: 1.9.0
- __Browser and OS versions__: Chrome 56, macOS

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/199754/23043066/ed12bef6-f44f-11e6-8d34-d3e2f1c38de3.png)

#### Expected behavior

![image](https://cloud.githubusercontent.com/assets/199754/23046940/79aafa34-f461-11e6-8df9-8d9f9c24da7b.png)

**Comment by llorca** [comment]
cc @cmslewis

**Comment by cmslewis** [comment]
Look into `transform: translate3d(0, 0, 0)`

**Comment by llorca** [comment]
Also look into:
- Bump z-indices range from 10 to 100 (level 1 = 0, level 2 = 100, level 3 = 200, etc...)
- (@ggray) non-integer z-indices, though spec says integers only: https://www.w3.org/TR/CSS2/visuren.html#z-index

**Comment by giladgray** [comment]
as easy as [we-already-have-this-mixin](https://github.com/palantir/blueprint/pull/854/files#diff-5d8651263a156dc076b116e34a0c5991R89)

**Comment by adidahiya** [comment]
> Bump z-indices range from 10 to 100 (level 1 = 0, level 2 = 100, level 3 = 200, etc...)

how does this help?

don't we just have to put the button group example and navbar in separate stacking contexts?

**Comment by llorca** [comment]
Global z-indices are always safe and explicit. The bigger the range, the more elements you can play with in your stack (see control groups). I'm personally not a fan of the hacky `translateZ`, and I'm extremely confused with how multiple `translateZ`'d elements would interact with each other. But, it'll do the trick for now!

**Comment by adidahiya** [comment]
> Global z-indices are always safe and explicit

I'm pretty opposed to this. I think it's a backwards step in the wrong direction. I was always confused / concerned in the bootstrap or foundation CSS world where there was a _global_ z-index scale to follow. Why not scope stacking concerns to local components if we can?

**Comment by llorca** [comment]
Well, I'm not sure what's confusing about z-indices since it's a single unified scale across your system, really can't get easier. For instance: let's say we have that control group stack with specific z-indices; we also have a navbar that's conceptually always on top of everything, so we give it a greater z-index; now put your control group in the navbar and they will now be on top of the navbar. Done deal.

As I said previously, I'm cool with Gilad's fix, but I'd be curious to hear your take on these two things:
- the hacky `translateZ` solution: `z-index` is made for stacking, and AFAIK `translateZ` isn't
- how do you safely control stacking for multiple `translateZ`d elements?

**Comment by adidahiya** [comment]
Multiple `translateZ` elements don't get the _same_ stacking context; they create a new one. [MDN has good docs on this](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

We've experienced a number of problems around the global nature of CSS in building applications which feature multiple versions of Blueprint on the same page; I don't want to add z-indices to that list of concerns.

**Comment by giladgray** [comment]
@llorca i hate to say it, but this is not a battle you want to fight. 

**the global-ness of `z-index` is its Achilles' Heel and has bitten us (and every other CSS developer) at least once.** case in point: remember the first time we increased the z-index layer spacing? and now you want to do it again? when does it end? 

**stacking context and z-index isolation is our primary defense _against_ the global-ness of `z-index`.** it lets us safely use this powerful layering tool such that we're sure layers won't leak out of some scope. "layer leakage" is the root cause of this bug, and stacking context isolation is the solution to that bug. 

it's important to note that `transformZ` is _merely one way_ of creating a new stacking context; [MDN lists twelve separate ways](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) to do it. my initial implementation used `will-change: opacity` (even though the styles don't actually set opacity) and worked perfectly. (i chose opacity instead of transform because of #854, but there didn't seem to be a difference between the two in my testing.)

by the way, that [MDN article linked above](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) is the holy grail for stacking context questions. i re-read it monthly and there's been a link to it [in our docs](http://localhost:9000/packages/site-docs/dist/?examples#core/variables.layering) since the very early days.

**Comment by erikwiffin** [comment]
I see that this is closed, and I'm probably too late, but I'd like to put in a vote _against_ local stacking contexts, especially in this situation. Since 1.16 was released, I've been trying to hunt down a bug where a react-select dropdown inside a control group was showing up _below_ elements further down the page. Yes, they could attach the dropdown menu to the document body like you do with the Popover, but since creating local stacking contexts isn't standard, I don't think most libraries are likely to do that.

On the plus side, I learned about stacking contexts, so at least that's something.
