### ISSUE TITLE
Remove pt-popover-target element completely

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#724]
Related tickets: #630, #512

`pt-popover-target` causes a lot of issues and is very complex. Let's discuss replacing it completely

**Comment by adidahiya** [comment]
Hm, yeah so I've thought about this and would love to try to remove the target wrapper element completely. We could make `Popover` attach its behavior to the React children it gets (we already enforce that there is exactly one child node) by cloning and adding classes, event handlers, etc. This might be a relatively major break depending on what people are doing with `.pt-popover-target` styling, but is probably worth it in the next major version. I suggest polling users about this API break.

**Comment by giladgray** [comment]
A few thoughts here:

1. It will not be possible to remove `.pt-popover-target` for inline popovers because we need a common parent / components can only return one element from `render`. 

1. However, we could remove `.pt-popover-target` for non-inline popovers and just clone the target (which we already do in most cases) to inject our handlers. 

    1. Except that imposes the requirement that the target _support_ our handlers. For instance, if the given target element doesn't support `onClick` then CLICK interactions will never work. This could happen pretty easily if someone passes a custom component which doesn't implement an `onClick` prop or spread HTML props. 
    1. ⬆️ _This is the main rationale behind the target element_: I know it supports the events I need because I know it's a `span`.

1. In React 16, we'll be able to return multiple elements from `render` so that'll be awesome.

**Comment by adidahiya** [comment]
> In React 16, we'll be able to return multiple elements from render so that'll be awesome.

I don't think this actually helps us address this issue... I'm inclined to close this unless there is a real proposal on the table.

tagging @zerovox who might have ideas / opinions about the wrapper element
