### ISSUE TITLE
Enable FocusStyleManager by default

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#773]
> Blueprint has a bug with a bad default. No app will ever want this to not show up on Tab only.

Making apps opt into `FocusStyleManager.onlyShowFocusOnTabs();` seems excessive. Make this the default instead

**Comment by adidahiya** [comment]
This comes up often. We're not going to do anything automatically for you on module load, that's just a bad thing for any JS library to do.

**Comment by leebyp** [comment]
What’s the reason to not do anything on module load? I can see how this is bad practice in general, but there are no side-effects to the code that’s being run. We’re touching the DOM, but not manipulating it more than adding and removing classes. We’re making an assumption to go against browser defaults, but the same can be said for all stylings - BP is more than a JS library.

That being said, I can see that we could want the default to err on the side of accessibility, since a lot of Blueprint decisions are based on that eg. the colour palettes, and we’re getting more requests for other accessibility features.

**Comment by giladgray** [comment]
The primary argument against doing this on module load is that that in itself is precisely a [side effect](https://en.wikipedia.org/wiki/Side_effect_(computer_science)).

Imagine if you went to `import { Utils } from "@blueprintjs/core"` because you really dig `safeInvoke` (and that's the only thing you want from the library), and suddenly there's this extra class on `document.body`. You just wanted to use a cool function and I went in there and mucked up your DOM. 😞

So we made it as simple as possible: make one explicit function call once during app initialization.

**Comment by giladgray** [comment]
Implementation-wise, we could swap from `.pt-focus-disabled` to `.pt-focus-enabled` 😮

**Comment by leebyp** [comment]
I guess my question is: Is a `pt-` class _actually_ messing up the DOM in practice?
I don't see anyone encountering the `safeInvoke` scenario because that's not how I envision BP as a tool. It's not a standard library with things you can choose here and there, it's a design ecosystem, and you buy into that when you use it.

Side note, agreed with the `pt-focus-enabled` change.

**Comment by adidahiya** [comment]
+1 for pt-focus-enabled change. As per https://github.com/palantir/blueprint/issues/244#issuecomment-263678215, we should make all our global styles opt-in wherever we can https://github.com/palantir/blueprint/blob/0239587d5a53d7e01ffeb14b69f0331a8671a479/packages/core/src/_accessibility.scss#L57

**Comment by llorca** [comment]
@adidahiya Today the behavior shows strong visual outlines by default everywhere, which indirectly forces consumers to enable `FocusStyleManager`. My fear with this change is that nobody is going to enable `FocusStyleManager.onlyShowFocusOnTabs();` anymore because they won't be bothered by all the focus outlines. 

We've been biasing towards accessibility this whole time, which still sounds like a good move to me. In addition to global styles concerns, we should consider accessibility out-of-the-box if we're thinking about the `pt-focus-enabled` change

**Comment by leebyp** [comment]
Ah, if we're actively making all our global styles opt-in then I buy the reason for the focus to be that way.

**Comment by giladgray** [comment]
side effects are essentially banned in this new world of tree shaking, so i think this is safe to close.
