### ISSUE TITLE
[Overlay] Overlays do not correctly add pt-overlay-content class to child if child is a React component

### ISSUE THREAD

**Issue by jasonma** [palantir/blueprint#872]
### Bug report

- __Package version(s)__: 1.12

#### Steps to reproduce

Create the following:
```ts
<Overlay
    isOpen={true}
>
    <SomeOtherReactComponent />
</Overlay>
```

`SomeOtherReactComponent.tsx`:

```ts
class SomeOtherReactComponent extends React.Component<{}, {}> {
    render() {
        return <div className="my-content">
            Some Text Here
        </div>;
    }
}
```

#### Actual behavior

DOM:
```html
<div data-reactroot="" class="pt-overlay pt-overlay-open">
    <span>
        <div class="pt-overlay-backdrop" tabindex="0"></div>
        <div class="my-content">Some Text Here</div>
    </span>
</div>
```

#### Expected behavior

```html
<div data-reactroot="" class="pt-overlay pt-overlay-open">
    <span>
        <div class="pt-overlay-backdrop" tabindex="0"></div>
        <div class="my-content pt-overlay-content">Some Text Here</div>
    </span>
</div>
```

Note the absence of the `pt-overlay-content` class on the `my-content` element.

**Comment by cmslewis** [comment]
@jasonma Found the problem.

**Comment by cmslewis** [comment]
Perhaps not so quick...

The issue is that `Overlay` decorates its immediate child with `"pt-overlay-content"`, but in this case, your `SomeOtherReactComponent` is not propagating that `className` down to the `div`.

Components could be arbitrarily nested before we get to one with a relevant `className`:

```js
<Overlay isOpen={true}>
    <A />
</Overlay>

const A: React.SFC<{}> = () => <B />;
const B: React.SFC<{}> = () => <C />;
const C: React.SFC<{}> = () => <D />;
const D: React.SFC<{}> = () => <div className="my-content">Some text here</div>
```

We'd need the deeply nested `div` to receive the additional `pt-overlay-content` class in this case. Not sure how best to handle this without exploring the entire tree of children. It's also not clear which child we should apply the class to in the end (perhaps passing `className` to some higher-level child would suffice). 

Seems like the `React.cloneElement` approach that we're using is bad and that we're doing a poor job crafting what essentially needs to be a higher-order "overlay content" component. I'll play with solutions as I have time.

**Comment by giladgray** [comment]
@jasonma does your component support the `className` prop? that's step 1 here: if your overlay child component doesn't respect the `className` it is given then there's _nothing_ we can do.

**Comment by giladgray** [comment]
@cmslewis in your example above if each of ABCD received `className` and passed it down to child then it should work as expected.

**Comment by giladgray** [comment]
@jasonma component definition should look like the following (note explicit `className` support):

```tsx
class SomeOtherReactComponent extends React.Component<{ className: string }, {}> {
    render() {
        return <div className={classNames("my-content", this.props.className)}>
            Some Text Here
        </div>;
    }
}
```

**Comment by jasonma** [comment]
@giladgray: cool, that makes sense. I wasn't aware that React components must have a `classNames` prop which gets propagated down to the top level elements. In fact, I'm nearly positive that none of our React components do that. Is that a common thing that I'm just ignorant of?

**Comment by leebyp** [comment]
damn that sucks, i would've expected extending from `React.Component` to have done that for me...

**Comment by leebyp** [comment]
If there's nothing we can do, then we should at least have a note / warning in our docs for components that we're doing this for - user's should not need to know about the implementation in BP when they're using the components.

**Comment by giladgray** [comment]
well sure, if you don't explicitly support a prop (or spread all `{...this.props}`) then it's simply not supported. React won't go jamming class names in for you.

this is why every Blueprint component props interface `extends IProps` which defines _only_ `className?: string;`.
