### ISSUE TITLE
Question: An example for full row selection

### ISSUE THREAD

**Issue by brsanthu** [palantir/blueprint#958]
I have been trying but in vain on how to select full row when user clicks in a cell. Is there any example I can refer to? Appreciate your help.

**Comment by gscshoyru** [comment]
There is, actually!

What you want to use is the `selectedRegionTransform` to do this. There isn't an example in the docs (though there plausibly should be...) but there is an example in our own test document -- the code for it is here: https://github.com/palantir/blueprint/blob/master/packages/table/preview/index.tsx#L276 . This has it working in controlled mode, but you shouldn't need to do that -- merely specifying the transform should be sufficient to do what you want.

**Comment by brsanthu** [comment]
@gscshoyru awesome. That example helped. Selecting full row something many folks may need, so adding an example to the docs would be really helpful.

**Comment by dwoske** [comment]
I probably shouldn't be commenting on a closed ticket to index.tsx, but I have this exact need, and I can't find any documentation or examples.  The link in this ticket is dead.  I found some tests where this seems to be happening, but I can't make heads or tails out of how to do this.

I think there should be an option to enable row selection when clicking anywhere in a row, instead of selecting the cell, this is a very common pattern.
