### ISSUE TITLE
[Feature Request] Bug Report Icon

### ISSUE THREAD

**Issue by scottfr** [palantir/blueprint#989]
It would be nice to have an icon to indicate bug reporting.

E.g. https://material.io/icons/#ic_bug_report

**Comment by llorca** [comment]
Hi Scott! It's unlikely that we'll get to this, unless we have a need for it internally. The good news is that one of our main priorities is to switch to an SVG implementation instead of an icon font, which will allow for custom icons and icon sets imports. Follow along here: https://github.com/palantir/blueprint/issues/365

**Comment by giladgray** [comment]
closing as we do not accept icon requests
