### ISSUE TITLE
Deprecation warning with React 15.5

### ISSUE THREAD

**Issue by anurag** [palantir/blueprint#991]
### Bug report

- __Package version(s)__: 1.14.0
- __Browser and OS versions__: All

With React 15.5, importing `PropTypes` from React has been [deprecated](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) in favor of the new `prop-types` package. Blueprint still imports `PropTypes` from React and leads to deprecation warnings in the console. 

An example from [menuItem.tsx](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/menu/menuItem.tsx#L67):
```
const REACT_CONTEXT_TYPES = { alignLeft: React.PropTypes.bool };
```

#### Steps to reproduce

Use Blueprint in a React app with React version >= 15.5.0 in debug mode.

#### Actual behavior
A warning is displayed in the browser console:

```Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.```

#### Expected behavior

The warning should not be displayed.

**Comment by giladgray** [comment]
ugh i'm not sure we can fix this happily in the short term because we support `"react": "^15.0.1 || ^0.14"` and changing that version string would likely constitute a major version bump.

fortunately, we are planning 2.0 as we speak so this may not have to wait _long_. you'll just have to ignore those warnings for the time being.
