### ISSUE TITLE
Add modifier styles as props instead of through className

### ISSUE THREAD

**Issue by eyalw** [palantir/blueprint#992]
I was wondering why you decided to have components like Spinner get their style using classNames instead of custom props. e.g. className="pt-large" vs size="large".

This method follows the [Style Components pattern](https://vasanthk.gitbooks.io/react-bits/patterns/11.style-component.html), and 
- prevents classNames from being hardcoded all over the codebase, 
- Also encapsulates CSS/classNames altogether from the user.
=> Nicer component API

So I guess my question is what do you think about this?

**Comment by giladgray** [comment]
good question @eyalw! 

we wrote most of the CSS APIs long before the JS APIs (particularly for `Spinner`) so the class names existed before the React props. we did not introduce props for classes initially because we figured they're already covered by our CSS classes (and the `Classes` constants object), which can be passed to `classNames()` just like that example you linked. 

we have wide support for some core concepts like `intent` or `iconName`. you'll also notice, perhaps, that _some_ components do support specific props like you're asking: `Button` has `active` #712 and `loading` #349. (you'll also notice that those were both PRs from outside the team so there's precedent for such contributions! 🎩)

we don't support `style` everywhere because it goes against the fundamental first word of Cascading Style Sheets: if you define all your styles inline on each element then nothing is reusable by the browser rendering engine and nothing can cascade to child elements (see: [dark theme](http://blueprintjs.com/docs/#core/typography.dark-theme)). note that some basic components (`Button`, `InputGroup`, `Checkbox`, etc) extend the full HTML props so those _do_ support `style`.

i'm going to rename this issue to focus on the question, not the replacement of `className` (cuz that ain't happening).

**Comment by giladgray** [comment]
oh also please see #248 for more discussion on this question of how to support custom styles. (spoiler: just use `className` with a library like [typestyle](http://typestyle.io) that generates actual CSS classes from your JS style objects.)

**Comment by giladgray** [comment]
hey guess what, most components now support props for modifiers!
